// Generated by generate_wasm_bridge.ts. Do not edit.

#include "raylib.h"
#include "raymath.h"
#include "rlgl.h"
#include "rcamera.h"
#include <emscripten/emscripten.h>

EMSCRIPTEN_KEEPALIVE
void dr_InitWindow(int p0, int p1, const char * p2) { InitWindow(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_CloseWindow(void) { CloseWindow(); }

EMSCRIPTEN_KEEPALIVE
bool dr_WindowShouldClose(void) { return WindowShouldClose(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowReady(void) { return IsWindowReady(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowFullscreen(void) { return IsWindowFullscreen(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowHidden(void) { return IsWindowHidden(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowMinimized(void) { return IsWindowMinimized(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowMaximized(void) { return IsWindowMaximized(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowFocused(void) { return IsWindowFocused(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowResized(void) { return IsWindowResized(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWindowState(unsigned int p0) { return IsWindowState(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowState(unsigned int p0) { SetWindowState(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ClearWindowState(unsigned int p0) { ClearWindowState(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ToggleFullscreen(void) { ToggleFullscreen(); }

EMSCRIPTEN_KEEPALIVE
void dr_ToggleBorderlessWindowed(void) { ToggleBorderlessWindowed(); }

EMSCRIPTEN_KEEPALIVE
void dr_MaximizeWindow(void) { MaximizeWindow(); }

EMSCRIPTEN_KEEPALIVE
void dr_MinimizeWindow(void) { MinimizeWindow(); }

EMSCRIPTEN_KEEPALIVE
void dr_RestoreWindow(void) { RestoreWindow(); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowIcon(const Image *p0) { SetWindowIcon(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowIcons(Image * p0, int p1) { SetWindowIcons(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowTitle(const char * p0) { SetWindowTitle(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowPosition(int p0, int p1) { SetWindowPosition(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowMonitor(int p0) { SetWindowMonitor(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowMinSize(int p0, int p1) { SetWindowMinSize(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowMaxSize(int p0, int p1) { SetWindowMaxSize(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowSize(int p0, int p1) { SetWindowSize(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowOpacity(float p0) { SetWindowOpacity(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetWindowFocused(void) { SetWindowFocused(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetScreenWidth(void) { return GetScreenWidth(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetScreenHeight(void) { return GetScreenHeight(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetRenderWidth(void) { return GetRenderWidth(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetRenderHeight(void) { return GetRenderHeight(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorCount(void) { return GetMonitorCount(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetCurrentMonitor(void) { return GetCurrentMonitor(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetMonitorPosition(Vector2 *result, int p0) { *result = GetMonitorPosition(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorWidth(int p0) { return GetMonitorWidth(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorHeight(int p0) { return GetMonitorHeight(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorPhysicalWidth(int p0) { return GetMonitorPhysicalWidth(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorPhysicalHeight(int p0) { return GetMonitorPhysicalHeight(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMonitorRefreshRate(int p0) { return GetMonitorRefreshRate(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetWindowPosition(Vector2 *result) { *result = GetWindowPosition(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetWindowScaleDPI(Vector2 *result) { *result = GetWindowScaleDPI(); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetMonitorName(int p0) { return GetMonitorName(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetClipboardText(const char * p0) { SetClipboardText(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetClipboardText(void) { return GetClipboardText(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetClipboardImage(Image *result) { *result = GetClipboardImage(); }

EMSCRIPTEN_KEEPALIVE
void dr_EnableEventWaiting(void) { EnableEventWaiting(); }

EMSCRIPTEN_KEEPALIVE
void dr_DisableEventWaiting(void) { DisableEventWaiting(); }

EMSCRIPTEN_KEEPALIVE
void dr_ShowCursor(void) { ShowCursor(); }

EMSCRIPTEN_KEEPALIVE
void dr_HideCursor(void) { HideCursor(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsCursorHidden(void) { return IsCursorHidden(); }

EMSCRIPTEN_KEEPALIVE
void dr_EnableCursor(void) { EnableCursor(); }

EMSCRIPTEN_KEEPALIVE
void dr_DisableCursor(void) { DisableCursor(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsCursorOnScreen(void) { return IsCursorOnScreen(); }

EMSCRIPTEN_KEEPALIVE
void dr_ClearBackground(const Color *p0) { ClearBackground(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginDrawing(void) { BeginDrawing(); }

EMSCRIPTEN_KEEPALIVE
void dr_EndDrawing(void) { EndDrawing(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginMode2D(const Camera2D *p0) { BeginMode2D(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndMode2D(void) { EndMode2D(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginMode3D(const Camera3D *p0) { BeginMode3D(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndMode3D(void) { EndMode3D(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginTextureMode(const RenderTexture2D *p0) { BeginTextureMode(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndTextureMode(void) { EndTextureMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginShaderMode(const Shader *p0) { BeginShaderMode(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndShaderMode(void) { EndShaderMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginBlendMode(int p0) { BeginBlendMode(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndBlendMode(void) { EndBlendMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginScissorMode(int p0, int p1, int p2, int p3) { BeginScissorMode(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_EndScissorMode(void) { EndScissorMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_BeginVrStereoMode(const VrStereoConfig *p0) { BeginVrStereoMode(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_EndVrStereoMode(void) { EndVrStereoMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadVrStereoConfig(VrStereoConfig *result, const VrDeviceInfo *p0) { *result = LoadVrStereoConfig(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadVrStereoConfig(const VrStereoConfig *p0) { UnloadVrStereoConfig(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadShader(Shader *result, const char * p0, const char * p1) { *result = LoadShader(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadShaderFromMemory(Shader *result, const char * p0, const char * p1) { *result = LoadShaderFromMemory(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsShaderValid(const Shader *p0) { return IsShaderValid(*p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetShaderLocation(const Shader *p0, const char * p1) { return GetShaderLocation(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_GetShaderLocationAttrib(const Shader *p0, const char * p1) { return GetShaderLocationAttrib(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetShaderValueMatrix(const Shader *p0, int p1, const Matrix *p2) { SetShaderValueMatrix(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_SetShaderValueTexture(const Shader *p0, int p1, const Texture2D *p2) { SetShaderValueTexture(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadShader(const Shader *p0) { UnloadShader(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetScreenToWorldRay(Ray *result, const Vector2 *p0, const Camera *p1) { *result = GetScreenToWorldRay(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetScreenToWorldRayEx(Ray *result, const Vector2 *p0, const Camera *p1, int p2, int p3) { *result = GetScreenToWorldRayEx(*p0, *p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GetWorldToScreen(Vector2 *result, const Vector3 *p0, const Camera *p1) { *result = GetWorldToScreen(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetWorldToScreenEx(Vector2 *result, const Vector3 *p0, const Camera *p1, int p2, int p3) { *result = GetWorldToScreenEx(*p0, *p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GetWorldToScreen2D(Vector2 *result, const Vector2 *p0, const Camera2D *p1) { *result = GetWorldToScreen2D(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetScreenToWorld2D(Vector2 *result, const Vector2 *p0, const Camera2D *p1) { *result = GetScreenToWorld2D(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraMatrix(Matrix *result, const Camera *p0) { *result = GetCameraMatrix(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraMatrix2D(Matrix *result, const Camera2D *p0) { *result = GetCameraMatrix2D(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetTargetFPS(int p0) { SetTargetFPS(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_GetFrameTime(void) { return GetFrameTime(); }

EMSCRIPTEN_KEEPALIVE
double dr_GetTime(void) { return GetTime(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetFPS(void) { return GetFPS(); }

EMSCRIPTEN_KEEPALIVE
void dr_SwapScreenBuffer(void) { SwapScreenBuffer(); }

EMSCRIPTEN_KEEPALIVE
void dr_PollInputEvents(void) { PollInputEvents(); }

EMSCRIPTEN_KEEPALIVE
void dr_WaitTime(double p0) { WaitTime(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetRandomSeed(unsigned int p0) { SetRandomSeed(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetRandomValue(int p0, int p1) { return GetRandomValue(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_TakeScreenshot(const char * p0) { TakeScreenshot(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetConfigFlags(unsigned int p0) { SetConfigFlags(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_OpenURL(const char * p0) { OpenURL(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetTraceLogLevel(int p0) { SetTraceLogLevel(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_LoadFileText(const char * p0) { return LoadFileText(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadFileText(char * p0) { UnloadFileText(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_SaveFileText(const char * p0, const char * p1) { return SaveFileText(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_FileRename(const char * p0, const char * p1) { return FileRename(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_FileRemove(const char * p0) { return FileRemove(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_FileCopy(const char * p0, const char * p1) { return FileCopy(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_FileMove(const char * p0, const char * p1) { return FileMove(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_FileTextReplace(const char * p0, const char * p1, const char * p2) { return FileTextReplace(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
int dr_FileTextFindIndex(const char * p0, const char * p1) { return FileTextFindIndex(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_FileExists(const char * p0) { return FileExists(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_DirectoryExists(const char * p0) { return DirectoryExists(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsFileExtension(const char * p0, const char * p1) { return IsFileExtension(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_GetFileLength(const char * p0) { return GetFileLength(p0); }

EMSCRIPTEN_KEEPALIVE
long dr_GetFileModTime(const char * p0) { return GetFileModTime(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetFileExtension(const char * p0) { return GetFileExtension(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetFileName(const char * p0) { return GetFileName(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetFileNameWithoutExt(const char * p0) { return GetFileNameWithoutExt(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetDirectoryPath(const char * p0) { return GetDirectoryPath(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetPrevDirectoryPath(const char * p0) { return GetPrevDirectoryPath(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetWorkingDirectory(void) { return GetWorkingDirectory(); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetApplicationDirectory(void) { return GetApplicationDirectory(); }

EMSCRIPTEN_KEEPALIVE
int dr_MakeDirectory(const char * p0) { return MakeDirectory(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ChangeDirectory(const char * p0) { return ChangeDirectory(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsPathFile(const char * p0) { return IsPathFile(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsFileNameValid(const char * p0) { return IsFileNameValid(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadDirectoryFiles(FilePathList *result, const char * p0) { *result = LoadDirectoryFiles(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadDirectoryFilesEx(FilePathList *result, const char * p0, const char * p1, bool p2) { *result = LoadDirectoryFilesEx(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadDirectoryFiles(const FilePathList *p0) { UnloadDirectoryFiles(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsFileDropped(void) { return IsFileDropped(); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadDroppedFiles(FilePathList *result) { *result = LoadDroppedFiles(); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadDroppedFiles(const FilePathList *p0) { UnloadDroppedFiles(*p0); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_GetDirectoryFileCount(const char * p0) { return GetDirectoryFileCount(p0); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_GetDirectoryFileCountEx(const char * p0, const char * p1, bool p2) { return GetDirectoryFileCountEx(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadAutomationEventList(AutomationEventList *result, const char * p0) { *result = LoadAutomationEventList(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadAutomationEventList(const AutomationEventList *p0) { UnloadAutomationEventList(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportAutomationEventList(const AutomationEventList *p0, const char * p1) { return ExportAutomationEventList(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAutomationEventList(AutomationEventList * p0) { SetAutomationEventList(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAutomationEventBaseFrame(int p0) { SetAutomationEventBaseFrame(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_StartAutomationEventRecording(void) { StartAutomationEventRecording(); }

EMSCRIPTEN_KEEPALIVE
void dr_StopAutomationEventRecording(void) { StopAutomationEventRecording(); }

EMSCRIPTEN_KEEPALIVE
void dr_PlayAutomationEvent(const AutomationEvent *p0) { PlayAutomationEvent(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsKeyPressed(int p0) { return IsKeyPressed(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsKeyPressedRepeat(int p0) { return IsKeyPressedRepeat(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsKeyDown(int p0) { return IsKeyDown(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsKeyReleased(int p0) { return IsKeyReleased(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsKeyUp(int p0) { return IsKeyUp(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetKeyPressed(void) { return GetKeyPressed(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetCharPressed(void) { return GetCharPressed(); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetKeyName(int p0) { return GetKeyName(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetExitKey(int p0) { SetExitKey(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGamepadAvailable(int p0) { return IsGamepadAvailable(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_GetGamepadName(int p0) { return GetGamepadName(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGamepadButtonPressed(int p0, int p1) { return IsGamepadButtonPressed(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGamepadButtonDown(int p0, int p1) { return IsGamepadButtonDown(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGamepadButtonReleased(int p0, int p1) { return IsGamepadButtonReleased(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGamepadButtonUp(int p0, int p1) { return IsGamepadButtonUp(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_GetGamepadButtonPressed(void) { return GetGamepadButtonPressed(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetGamepadAxisCount(int p0) { return GetGamepadAxisCount(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_GetGamepadAxisMovement(int p0, int p1) { return GetGamepadAxisMovement(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_SetGamepadMappings(const char * p0) { return SetGamepadMappings(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetGamepadVibration(int p0, float p1, float p2, float p3) { SetGamepadVibration(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMouseButtonPressed(int p0) { return IsMouseButtonPressed(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMouseButtonDown(int p0) { return IsMouseButtonDown(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMouseButtonReleased(int p0) { return IsMouseButtonReleased(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMouseButtonUp(int p0) { return IsMouseButtonUp(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMouseX(void) { return GetMouseX(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetMouseY(void) { return GetMouseY(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetMousePosition(Vector2 *result) { *result = GetMousePosition(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetMouseDelta(Vector2 *result) { *result = GetMouseDelta(); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMousePosition(int p0, int p1) { SetMousePosition(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMouseOffset(int p0, int p1) { SetMouseOffset(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMouseScale(float p0, float p1) { SetMouseScale(p0, p1); }

EMSCRIPTEN_KEEPALIVE
float dr_GetMouseWheelMove(void) { return GetMouseWheelMove(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetMouseWheelMoveV(Vector2 *result) { *result = GetMouseWheelMoveV(); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMouseCursor(int p0) { SetMouseCursor(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetTouchX(void) { return GetTouchX(); }

EMSCRIPTEN_KEEPALIVE
int dr_GetTouchY(void) { return GetTouchY(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetTouchPosition(Vector2 *result, int p0) { *result = GetTouchPosition(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetTouchPointId(int p0) { return GetTouchPointId(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetTouchPointCount(void) { return GetTouchPointCount(); }

EMSCRIPTEN_KEEPALIVE
void dr_SetGesturesEnabled(unsigned int p0) { SetGesturesEnabled(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsGestureDetected(unsigned int p0) { return IsGestureDetected(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetGestureDetected(void) { return GetGestureDetected(); }

EMSCRIPTEN_KEEPALIVE
float dr_GetGestureHoldDuration(void) { return GetGestureHoldDuration(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetGestureDragVector(Vector2 *result) { *result = GetGestureDragVector(); }

EMSCRIPTEN_KEEPALIVE
float dr_GetGestureDragAngle(void) { return GetGestureDragAngle(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetGesturePinchVector(Vector2 *result) { *result = GetGesturePinchVector(); }

EMSCRIPTEN_KEEPALIVE
float dr_GetGesturePinchAngle(void) { return GetGesturePinchAngle(); }

EMSCRIPTEN_KEEPALIVE
void dr_UpdateCamera(Camera * p0, int p1) { UpdateCamera(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_UpdateCameraPro(Camera * p0, const Vector3 *p1, const Vector3 *p2, float p3) { UpdateCameraPro(p0, *p1, *p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_SetShapesTexture(const Texture2D *p0, const Rectangle *p1) { SetShapesTexture(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetShapesTexture(Texture2D *result) { *result = GetShapesTexture(); }

EMSCRIPTEN_KEEPALIVE
void dr_GetShapesTextureRectangle(Rectangle *result) { *result = GetShapesTextureRectangle(); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPixel(int p0, int p1, const Color *p2) { DrawPixel(p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPixelV(const Vector2 *p0, const Color *p1) { DrawPixelV(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLine(int p0, int p1, int p2, int p3, const Color *p4) { DrawLine(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLineV(const Vector2 *p0, const Vector2 *p1, const Color *p2) { DrawLineV(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLineEx(const Vector2 *p0, const Vector2 *p1, float p2, const Color *p3) { DrawLineEx(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLineBezier(const Vector2 *p0, const Vector2 *p1, float p2, const Color *p3) { DrawLineBezier(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLineDashed(const Vector2 *p0, const Vector2 *p1, int p2, int p3, const Color *p4) { DrawLineDashed(*p0, *p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircle(int p0, int p1, float p2, const Color *p3) { DrawCircle(p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleV(const Vector2 *p0, float p1, const Color *p2) { DrawCircleV(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleGradient(const Vector2 *p0, float p1, const Color *p2, const Color *p3) { DrawCircleGradient(*p0, p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleSector(const Vector2 *p0, float p1, float p2, float p3, int p4, const Color *p5) { DrawCircleSector(*p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleSectorLines(const Vector2 *p0, float p1, float p2, float p3, int p4, const Color *p5) { DrawCircleSectorLines(*p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleLines(int p0, int p1, float p2, const Color *p3) { DrawCircleLines(p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircleLinesV(const Vector2 *p0, float p1, const Color *p2) { DrawCircleLinesV(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawEllipse(int p0, int p1, float p2, float p3, const Color *p4) { DrawEllipse(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawEllipseV(const Vector2 *p0, float p1, float p2, const Color *p3) { DrawEllipseV(*p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawEllipseLines(int p0, int p1, float p2, float p3, const Color *p4) { DrawEllipseLines(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawEllipseLinesV(const Vector2 *p0, float p1, float p2, const Color *p3) { DrawEllipseLinesV(*p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRing(const Vector2 *p0, float p1, float p2, float p3, float p4, int p5, const Color *p6) { DrawRing(*p0, p1, p2, p3, p4, p5, *p6); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRingLines(const Vector2 *p0, float p1, float p2, float p3, float p4, int p5, const Color *p6) { DrawRingLines(*p0, p1, p2, p3, p4, p5, *p6); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangle(int p0, int p1, int p2, int p3, const Color *p4) { DrawRectangle(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleV(const Vector2 *p0, const Vector2 *p1, const Color *p2) { DrawRectangleV(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleRec(const Rectangle *p0, const Color *p1) { DrawRectangleRec(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectanglePro(const Rectangle *p0, const Vector2 *p1, float p2, const Color *p3) { DrawRectanglePro(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleGradientV(int p0, int p1, int p2, int p3, const Color *p4, const Color *p5) { DrawRectangleGradientV(p0, p1, p2, p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleGradientH(int p0, int p1, int p2, int p3, const Color *p4, const Color *p5) { DrawRectangleGradientH(p0, p1, p2, p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleGradientEx(const Rectangle *p0, const Color *p1, const Color *p2, const Color *p3, const Color *p4) { DrawRectangleGradientEx(*p0, *p1, *p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleLines(int p0, int p1, int p2, int p3, const Color *p4) { DrawRectangleLines(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleLinesEx(const Rectangle *p0, float p1, const Color *p2) { DrawRectangleLinesEx(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleRounded(const Rectangle *p0, float p1, int p2, const Color *p3) { DrawRectangleRounded(*p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleRoundedLines(const Rectangle *p0, float p1, int p2, const Color *p3) { DrawRectangleRoundedLines(*p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRectangleRoundedLinesEx(const Rectangle *p0, float p1, int p2, float p3, const Color *p4) { DrawRectangleRoundedLinesEx(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTriangle(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Color *p3) { DrawTriangle(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTriangleLines(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Color *p3) { DrawTriangleLines(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPoly(const Vector2 *p0, int p1, float p2, float p3, const Color *p4) { DrawPoly(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPolyLines(const Vector2 *p0, int p1, float p2, float p3, const Color *p4) { DrawPolyLines(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPolyLinesEx(const Vector2 *p0, int p1, float p2, float p3, float p4, const Color *p5) { DrawPolyLinesEx(*p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSplineSegmentLinear(const Vector2 *p0, const Vector2 *p1, float p2, const Color *p3) { DrawSplineSegmentLinear(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSplineSegmentBasis(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4, const Color *p5) { DrawSplineSegmentBasis(*p0, *p1, *p2, *p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSplineSegmentCatmullRom(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4, const Color *p5) { DrawSplineSegmentCatmullRom(*p0, *p1, *p2, *p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSplineSegmentBezierQuadratic(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, float p3, const Color *p4) { DrawSplineSegmentBezierQuadratic(*p0, *p1, *p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSplineSegmentBezierCubic(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4, const Color *p5) { DrawSplineSegmentBezierCubic(*p0, *p1, *p2, *p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_GetSplinePointLinear(Vector2 *result, const Vector2 *p0, const Vector2 *p1, float p2) { *result = GetSplinePointLinear(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetSplinePointBasis(Vector2 *result, const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4) { *result = GetSplinePointBasis(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GetSplinePointCatmullRom(Vector2 *result, const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4) { *result = GetSplinePointCatmullRom(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GetSplinePointBezierQuad(Vector2 *result, const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, float p3) { *result = GetSplinePointBezierQuad(*p0, *p1, *p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GetSplinePointBezierCubic(Vector2 *result, const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, float p4) { *result = GetSplinePointBezierCubic(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionRecs(const Rectangle *p0, const Rectangle *p1) { return CheckCollisionRecs(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionCircles(const Vector2 *p0, float p1, const Vector2 *p2, float p3) { return CheckCollisionCircles(*p0, p1, *p2, p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionCircleRec(const Vector2 *p0, float p1, const Rectangle *p2) { return CheckCollisionCircleRec(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionCircleLine(const Vector2 *p0, float p1, const Vector2 *p2, const Vector2 *p3) { return CheckCollisionCircleLine(*p0, p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionPointRec(const Vector2 *p0, const Rectangle *p1) { return CheckCollisionPointRec(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionPointCircle(const Vector2 *p0, const Vector2 *p1, float p2) { return CheckCollisionPointCircle(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionPointTriangle(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3) { return CheckCollisionPointTriangle(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionPointLine(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, int p3) { return CheckCollisionPointLine(*p0, *p1, *p2, p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionLines(const Vector2 *p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, Vector2 * p4) { return CheckCollisionLines(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCollisionRec(Rectangle *result, const Rectangle *p0, const Rectangle *p1) { *result = GetCollisionRec(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadImage(Image *result, const char * p0) { *result = LoadImage(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadImageRaw(Image *result, const char * p0, int p1, int p2, int p3, int p4) { *result = LoadImageRaw(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadImageFromTexture(Image *result, const Texture2D *p0) { *result = LoadImageFromTexture(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadImageFromScreen(Image *result) { *result = LoadImageFromScreen(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsImageValid(const Image *p0) { return IsImageValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadImage(const Image *p0) { UnloadImage(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportImage(const Image *p0, const char * p1) { return ExportImage(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportImageAsCode(const Image *p0, const char * p1) { return ExportImageAsCode(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageColor(Image *result, int p0, int p1, const Color *p2) { *result = GenImageColor(p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageGradientLinear(Image *result, int p0, int p1, int p2, const Color *p3, const Color *p4) { *result = GenImageGradientLinear(p0, p1, p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageGradientRadial(Image *result, int p0, int p1, float p2, const Color *p3, const Color *p4) { *result = GenImageGradientRadial(p0, p1, p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageGradientSquare(Image *result, int p0, int p1, float p2, const Color *p3, const Color *p4) { *result = GenImageGradientSquare(p0, p1, p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageChecked(Image *result, int p0, int p1, int p2, int p3, const Color *p4, const Color *p5) { *result = GenImageChecked(p0, p1, p2, p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageWhiteNoise(Image *result, int p0, int p1, float p2) { *result = GenImageWhiteNoise(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImagePerlinNoise(Image *result, int p0, int p1, int p2, int p3, float p4) { *result = GenImagePerlinNoise(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageCellular(Image *result, int p0, int p1, int p2) { *result = GenImageCellular(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenImageText(Image *result, int p0, int p1, const char * p2) { *result = GenImageText(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageCopy(Image *result, const Image *p0) { *result = ImageCopy(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageFromImage(Image *result, const Image *p0, const Rectangle *p1) { *result = ImageFromImage(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageFromChannel(Image *result, const Image *p0, int p1) { *result = ImageFromChannel(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageText(Image *result, const char * p0, int p1, const Color *p2) { *result = ImageText(p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageTextEx(Image *result, const Font *p0, const char * p1, float p2, float p3, const Color *p4) { *result = ImageTextEx(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageFormat(Image * p0, int p1) { ImageFormat(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageToPOT(Image * p0, const Color *p1) { ImageToPOT(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageCrop(Image * p0, const Rectangle *p1) { ImageCrop(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageAlphaCrop(Image * p0, float p1) { ImageAlphaCrop(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageAlphaClear(Image * p0, const Color *p1, float p2) { ImageAlphaClear(p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageAlphaMask(Image * p0, const Image *p1) { ImageAlphaMask(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageAlphaPremultiply(Image * p0) { ImageAlphaPremultiply(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageBlurGaussian(Image * p0, int p1) { ImageBlurGaussian(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageResize(Image * p0, int p1, int p2) { ImageResize(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageResizeNN(Image * p0, int p1, int p2) { ImageResizeNN(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageResizeCanvas(Image * p0, int p1, int p2, int p3, int p4, const Color *p5) { ImageResizeCanvas(p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageMipmaps(Image * p0) { ImageMipmaps(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDither(Image * p0, int p1, int p2, int p3, int p4) { ImageDither(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageFlipVertical(Image * p0) { ImageFlipVertical(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageFlipHorizontal(Image * p0) { ImageFlipHorizontal(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageRotate(Image * p0, int p1) { ImageRotate(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageRotateCW(Image * p0) { ImageRotateCW(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageRotateCCW(Image * p0) { ImageRotateCCW(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorTint(Image * p0, const Color *p1) { ImageColorTint(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorInvert(Image * p0) { ImageColorInvert(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorGrayscale(Image * p0) { ImageColorGrayscale(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorContrast(Image * p0, float p1) { ImageColorContrast(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorBrightness(Image * p0, int p1) { ImageColorBrightness(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageColorReplace(Image * p0, const Color *p1, const Color *p2) { ImageColorReplace(p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
Color * dr_LoadImageColors(const Image *p0) { return LoadImageColors(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadImageColors(Color * p0) { UnloadImageColors(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadImagePalette(Color * p0) { UnloadImagePalette(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetImageAlphaBorder(Rectangle *result, const Image *p0, float p1) { *result = GetImageAlphaBorder(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetImageColor(Color *result, const Image *p0, int p1, int p2) { *result = GetImageColor(*p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageClearBackground(Image * p0, const Color *p1) { ImageClearBackground(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawPixel(Image * p0, int p1, int p2, const Color *p3) { ImageDrawPixel(p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawPixelV(Image * p0, const Vector2 *p1, const Color *p2) { ImageDrawPixelV(p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawLine(Image * p0, int p1, int p2, int p3, int p4, const Color *p5) { ImageDrawLine(p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawLineV(Image * p0, const Vector2 *p1, const Vector2 *p2, const Color *p3) { ImageDrawLineV(p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawLineEx(Image * p0, const Vector2 *p1, const Vector2 *p2, int p3, const Color *p4) { ImageDrawLineEx(p0, *p1, *p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawCircle(Image * p0, int p1, int p2, int p3, const Color *p4) { ImageDrawCircle(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawCircleV(Image * p0, const Vector2 *p1, int p2, const Color *p3) { ImageDrawCircleV(p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawCircleLines(Image * p0, int p1, int p2, int p3, const Color *p4) { ImageDrawCircleLines(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawCircleLinesV(Image * p0, const Vector2 *p1, int p2, const Color *p3) { ImageDrawCircleLinesV(p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawRectangle(Image * p0, int p1, int p2, int p3, int p4, const Color *p5) { ImageDrawRectangle(p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawRectangleV(Image * p0, const Vector2 *p1, const Vector2 *p2, const Color *p3) { ImageDrawRectangleV(p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawRectangleRec(Image * p0, const Rectangle *p1, const Color *p2) { ImageDrawRectangleRec(p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawRectangleLines(Image * p0, const Rectangle *p1, int p2, const Color *p3) { ImageDrawRectangleLines(p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawTriangle(Image * p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, const Color *p4) { ImageDrawTriangle(p0, *p1, *p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawTriangleEx(Image * p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, const Color *p4, const Color *p5, const Color *p6) { ImageDrawTriangleEx(p0, *p1, *p2, *p3, *p4, *p5, *p6); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawTriangleLines(Image * p0, const Vector2 *p1, const Vector2 *p2, const Vector2 *p3, const Color *p4) { ImageDrawTriangleLines(p0, *p1, *p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDraw(Image * p0, const Image *p1, const Rectangle *p2, const Rectangle *p3, const Color *p4) { ImageDraw(p0, *p1, *p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawText(Image * p0, const char * p1, int p2, int p3, int p4, const Color *p5) { ImageDrawText(p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_ImageDrawTextEx(Image * p0, const Font *p1, const char * p2, const Vector2 *p3, float p4, float p5, const Color *p6) { ImageDrawTextEx(p0, *p1, p2, *p3, p4, p5, *p6); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadTexture(Texture2D *result, const char * p0) { *result = LoadTexture(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadTextureFromImage(Texture2D *result, const Image *p0) { *result = LoadTextureFromImage(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadTextureCubemap(TextureCubemap *result, const Image *p0, int p1) { *result = LoadTextureCubemap(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadRenderTexture(RenderTexture2D *result, int p0, int p1) { *result = LoadRenderTexture(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsTextureValid(const Texture2D *p0) { return IsTextureValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadTexture(const Texture2D *p0) { UnloadTexture(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsRenderTextureValid(const RenderTexture2D *p0) { return IsRenderTextureValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadRenderTexture(const RenderTexture2D *p0) { UnloadRenderTexture(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GenTextureMipmaps(Texture2D * p0) { GenTextureMipmaps(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetTextureFilter(const Texture2D *p0, int p1) { SetTextureFilter(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetTextureWrap(const Texture2D *p0, int p1) { SetTextureWrap(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTexture(const Texture2D *p0, int p1, int p2, const Color *p3) { DrawTexture(*p0, p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextureV(const Texture2D *p0, const Vector2 *p1, const Color *p2) { DrawTextureV(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextureEx(const Texture2D *p0, const Vector2 *p1, float p2, float p3, const Color *p4) { DrawTextureEx(*p0, *p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextureRec(const Texture2D *p0, const Rectangle *p1, const Vector2 *p2, const Color *p3) { DrawTextureRec(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTexturePro(const Texture2D *p0, const Rectangle *p1, const Rectangle *p2, const Vector2 *p3, float p4, const Color *p5) { DrawTexturePro(*p0, *p1, *p2, *p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextureNPatch(const Texture2D *p0, const NPatchInfo *p1, const Rectangle *p2, const Vector2 *p3, float p4, const Color *p5) { DrawTextureNPatch(*p0, *p1, *p2, *p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
bool dr_ColorIsEqual(const Color *p0, const Color *p1) { return ColorIsEqual(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Fade(Color *result, const Color *p0, float p1) { *result = Fade(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_ColorToInt(const Color *p0) { return ColorToInt(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorNormalize(Vector4 *result, const Color *p0) { *result = ColorNormalize(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorFromNormalized(Color *result, const Vector4 *p0) { *result = ColorFromNormalized(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorToHSV(Vector3 *result, const Color *p0) { *result = ColorToHSV(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorFromHSV(Color *result, float p0, float p1, float p2) { *result = ColorFromHSV(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorTint(Color *result, const Color *p0, const Color *p1) { *result = ColorTint(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorBrightness(Color *result, const Color *p0, float p1) { *result = ColorBrightness(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorContrast(Color *result, const Color *p0, float p1) { *result = ColorContrast(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorAlpha(Color *result, const Color *p0, float p1) { *result = ColorAlpha(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorAlphaBlend(Color *result, const Color *p0, const Color *p1, const Color *p2) { *result = ColorAlphaBlend(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_ColorLerp(Color *result, const Color *p0, const Color *p1, float p2) { *result = ColorLerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetColor(Color *result, unsigned int p0) { *result = GetColor(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetPixelDataSize(int p0, int p1, int p2) { return GetPixelDataSize(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetFontDefault(Font *result) { *result = GetFontDefault(); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadFont(Font *result, const char * p0) { *result = LoadFont(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadFontFromImage(Font *result, const Image *p0, const Color *p1, int p2) { *result = LoadFontFromImage(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsFontValid(const Font *p0) { return IsFontValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadFontData(GlyphInfo * p0, int p1) { UnloadFontData(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadFont(const Font *p0) { UnloadFont(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportFontAsCode(const Font *p0, const char * p1) { return ExportFontAsCode(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawFPS(int p0, int p1) { DrawFPS(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawText(const char * p0, int p1, int p2, int p3, const Color *p4) { DrawText(p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextEx(const Font *p0, const char * p1, const Vector2 *p2, float p3, float p4, const Color *p5) { DrawTextEx(*p0, p1, *p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextPro(const Font *p0, const char * p1, const Vector2 *p2, const Vector2 *p3, float p4, float p5, float p6, const Color *p7) { DrawTextPro(*p0, p1, *p2, *p3, p4, p5, p6, *p7); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTextCodepoint(const Font *p0, int p1, const Vector2 *p2, float p3, const Color *p4) { DrawTextCodepoint(*p0, p1, *p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_SetTextLineSpacing(int p0) { SetTextLineSpacing(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_MeasureText(const char * p0, int p1) { return MeasureText(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MeasureTextEx(Vector2 *result, const Font *p0, const char * p1, float p2, float p3) { *result = MeasureTextEx(*p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
int dr_GetGlyphIndex(const Font *p0, int p1) { return GetGlyphIndex(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetGlyphInfo(GlyphInfo *result, const Font *p0, int p1) { *result = GetGlyphInfo(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetGlyphAtlasRec(Rectangle *result, const Font *p0, int p1) { *result = GetGlyphAtlasRec(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadUTF8(char * p0) { UnloadUTF8(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_GetCodepointCount(const char * p0) { return GetCodepointCount(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_TextCopy(char * p0, const char * p1) { return TextCopy(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_TextIsEqual(const char * p0, const char * p1) { return TextIsEqual(p0, p1); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_TextLength(const char * p0) { return TextLength(p0); }

EMSCRIPTEN_KEEPALIVE
const char * dr_TextSubtext(const char * p0, int p1, int p2) { return TextSubtext(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
const char * dr_TextRemoveSpaces(const char * p0) { return TextRemoveSpaces(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_GetTextBetween(const char * p0, const char * p1, const char * p2) { return GetTextBetween(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextReplace(const char * p0, const char * p1, const char * p2) { return TextReplace(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextReplaceAlloc(const char * p0, const char * p1, const char * p2) { return TextReplaceAlloc(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextReplaceBetween(const char * p0, const char * p1, const char * p2, const char * p3) { return TextReplaceBetween(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextReplaceBetweenAlloc(const char * p0, const char * p1, const char * p2, const char * p3) { return TextReplaceBetweenAlloc(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextInsert(const char * p0, const char * p1, int p2) { return TextInsert(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextInsertAlloc(const char * p0, const char * p1, int p2) { return TextInsertAlloc(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
int dr_TextFindIndex(const char * p0, const char * p1) { return TextFindIndex(p0, p1); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextToUpper(const char * p0) { return TextToUpper(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextToLower(const char * p0) { return TextToLower(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextToPascal(const char * p0) { return TextToPascal(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextToSnake(const char * p0) { return TextToSnake(p0); }

EMSCRIPTEN_KEEPALIVE
char * dr_TextToCamel(const char * p0) { return TextToCamel(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_TextToInteger(const char * p0) { return TextToInteger(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_TextToFloat(const char * p0) { return TextToFloat(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawLine3D(const Vector3 *p0, const Vector3 *p1, const Color *p2) { DrawLine3D(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPoint3D(const Vector3 *p0, const Color *p1) { DrawPoint3D(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCircle3D(const Vector3 *p0, float p1, const Vector3 *p2, float p3, const Color *p4) { DrawCircle3D(*p0, p1, *p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawTriangle3D(const Vector3 *p0, const Vector3 *p1, const Vector3 *p2, const Color *p3) { DrawTriangle3D(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCube(const Vector3 *p0, float p1, float p2, float p3, const Color *p4) { DrawCube(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCubeV(const Vector3 *p0, const Vector3 *p1, const Color *p2) { DrawCubeV(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCubeWires(const Vector3 *p0, float p1, float p2, float p3, const Color *p4) { DrawCubeWires(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCubeWiresV(const Vector3 *p0, const Vector3 *p1, const Color *p2) { DrawCubeWiresV(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSphere(const Vector3 *p0, float p1, const Color *p2) { DrawSphere(*p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSphereEx(const Vector3 *p0, float p1, int p2, int p3, const Color *p4) { DrawSphereEx(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawSphereWires(const Vector3 *p0, float p1, int p2, int p3, const Color *p4) { DrawSphereWires(*p0, p1, p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCylinder(const Vector3 *p0, float p1, float p2, float p3, int p4, const Color *p5) { DrawCylinder(*p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCylinderEx(const Vector3 *p0, const Vector3 *p1, float p2, float p3, int p4, const Color *p5) { DrawCylinderEx(*p0, *p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCylinderWires(const Vector3 *p0, float p1, float p2, float p3, int p4, const Color *p5) { DrawCylinderWires(*p0, p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCylinderWiresEx(const Vector3 *p0, const Vector3 *p1, float p2, float p3, int p4, const Color *p5) { DrawCylinderWiresEx(*p0, *p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCapsule(const Vector3 *p0, const Vector3 *p1, float p2, int p3, int p4, const Color *p5) { DrawCapsule(*p0, *p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawCapsuleWires(const Vector3 *p0, const Vector3 *p1, float p2, int p3, int p4, const Color *p5) { DrawCapsuleWires(*p0, *p1, p2, p3, p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawPlane(const Vector3 *p0, const Vector2 *p1, const Color *p2) { DrawPlane(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawRay(const Ray *p0, const Color *p1) { DrawRay(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawGrid(int p0, float p1) { DrawGrid(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadModel(Model *result, const char * p0) { *result = LoadModel(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadModelFromMesh(Model *result, const Mesh *p0) { *result = LoadModelFromMesh(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsModelValid(const Model *p0) { return IsModelValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadModel(const Model *p0) { UnloadModel(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetModelBoundingBox(BoundingBox *result, const Model *p0) { *result = GetModelBoundingBox(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawModel(const Model *p0, const Vector3 *p1, float p2, const Color *p3) { DrawModel(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawModelEx(const Model *p0, const Vector3 *p1, const Vector3 *p2, float p3, const Vector3 *p4, const Color *p5) { DrawModelEx(*p0, *p1, *p2, p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawModelWires(const Model *p0, const Vector3 *p1, float p2, const Color *p3) { DrawModelWires(*p0, *p1, p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawModelWiresEx(const Model *p0, const Vector3 *p1, const Vector3 *p2, float p3, const Vector3 *p4, const Color *p5) { DrawModelWiresEx(*p0, *p1, *p2, p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawBoundingBox(const BoundingBox *p0, const Color *p1) { DrawBoundingBox(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawBillboard(const Camera *p0, const Texture2D *p1, const Vector3 *p2, float p3, const Color *p4) { DrawBillboard(*p0, *p1, *p2, p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawBillboardRec(const Camera *p0, const Texture2D *p1, const Rectangle *p2, const Vector3 *p3, const Vector2 *p4, const Color *p5) { DrawBillboardRec(*p0, *p1, *p2, *p3, *p4, *p5); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawBillboardPro(const Camera *p0, const Texture2D *p1, const Rectangle *p2, const Vector3 *p3, const Vector3 *p4, const Vector2 *p5, const Vector2 *p6, float p7, const Color *p8) { DrawBillboardPro(*p0, *p1, *p2, *p3, *p4, *p5, *p6, p7, *p8); }

EMSCRIPTEN_KEEPALIVE
void dr_UploadMesh(Mesh * p0, bool p1) { UploadMesh(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadMesh(const Mesh *p0) { UnloadMesh(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_DrawMesh(const Mesh *p0, const Material *p1, const Matrix *p2) { DrawMesh(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetMeshBoundingBox(BoundingBox *result, const Mesh *p0) { *result = GetMeshBoundingBox(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshTangents(Mesh * p0) { GenMeshTangents(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportMesh(const Mesh *p0, const char * p1) { return ExportMesh(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportMeshAsCode(const Mesh *p0, const char * p1) { return ExportMeshAsCode(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshPoly(Mesh *result, int p0, float p1) { *result = GenMeshPoly(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshPlane(Mesh *result, float p0, float p1, int p2, int p3) { *result = GenMeshPlane(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshCube(Mesh *result, float p0, float p1, float p2) { *result = GenMeshCube(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshSphere(Mesh *result, float p0, int p1, int p2) { *result = GenMeshSphere(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshHemiSphere(Mesh *result, float p0, int p1, int p2) { *result = GenMeshHemiSphere(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshCylinder(Mesh *result, float p0, float p1, int p2) { *result = GenMeshCylinder(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshCone(Mesh *result, float p0, float p1, int p2) { *result = GenMeshCone(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshTorus(Mesh *result, float p0, float p1, int p2, int p3) { *result = GenMeshTorus(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshKnot(Mesh *result, float p0, float p1, int p2, int p3) { *result = GenMeshKnot(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshHeightmap(Mesh *result, const Image *p0, const Vector3 *p1) { *result = GenMeshHeightmap(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GenMeshCubicmap(Mesh *result, const Image *p0, const Vector3 *p1) { *result = GenMeshCubicmap(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadMaterialDefault(Material *result) { *result = LoadMaterialDefault(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMaterialValid(const Material *p0) { return IsMaterialValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadMaterial(const Material *p0) { UnloadMaterial(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMaterialTexture(Material * p0, int p1, const Texture2D *p2) { SetMaterialTexture(p0, p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_SetModelMeshMaterial(Model * p0, int p1, int p2) { SetModelMeshMaterial(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_UpdateModelAnimation(const Model *p0, const ModelAnimation *p1, float p2) { UpdateModelAnimation(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_UpdateModelAnimationEx(const Model *p0, const ModelAnimation *p1, float p2, const ModelAnimation *p3, float p4, float p5) { UpdateModelAnimationEx(*p0, *p1, p2, *p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadModelAnimations(ModelAnimation * p0, int p1) { UnloadModelAnimations(p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsModelAnimationValid(const Model *p0, const ModelAnimation *p1) { return IsModelAnimationValid(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionSpheres(const Vector3 *p0, float p1, const Vector3 *p2, float p3) { return CheckCollisionSpheres(*p0, p1, *p2, p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionBoxes(const BoundingBox *p0, const BoundingBox *p1) { return CheckCollisionBoxes(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_CheckCollisionBoxSphere(const BoundingBox *p0, const Vector3 *p1, float p2) { return CheckCollisionBoxSphere(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetRayCollisionSphere(RayCollision *result, const Ray *p0, const Vector3 *p1, float p2) { *result = GetRayCollisionSphere(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetRayCollisionBox(RayCollision *result, const Ray *p0, const BoundingBox *p1) { *result = GetRayCollisionBox(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetRayCollisionMesh(RayCollision *result, const Ray *p0, const Mesh *p1, const Matrix *p2) { *result = GetRayCollisionMesh(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_GetRayCollisionTriangle(RayCollision *result, const Ray *p0, const Vector3 *p1, const Vector3 *p2, const Vector3 *p3) { *result = GetRayCollisionTriangle(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GetRayCollisionQuad(RayCollision *result, const Ray *p0, const Vector3 *p1, const Vector3 *p2, const Vector3 *p3, const Vector3 *p4) { *result = GetRayCollisionQuad(*p0, *p1, *p2, *p3, *p4); }

EMSCRIPTEN_KEEPALIVE
void dr_InitAudioDevice(void) { InitAudioDevice(); }

EMSCRIPTEN_KEEPALIVE
void dr_CloseAudioDevice(void) { CloseAudioDevice(); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsAudioDeviceReady(void) { return IsAudioDeviceReady(); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMasterVolume(float p0) { SetMasterVolume(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_GetMasterVolume(void) { return GetMasterVolume(); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadWave(Wave *result, const char * p0) { *result = LoadWave(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsWaveValid(const Wave *p0) { return IsWaveValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadSound(Sound *result, const char * p0) { *result = LoadSound(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadSoundFromWave(Sound *result, const Wave *p0) { *result = LoadSoundFromWave(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadSoundAlias(Sound *result, const Sound *p0) { *result = LoadSoundAlias(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsSoundValid(const Sound *p0) { return IsSoundValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadWave(const Wave *p0) { UnloadWave(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadSound(const Sound *p0) { UnloadSound(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadSoundAlias(const Sound *p0) { UnloadSoundAlias(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportWave(const Wave *p0, const char * p1) { return ExportWave(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
bool dr_ExportWaveAsCode(const Wave *p0, const char * p1) { return ExportWaveAsCode(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_PlaySound(const Sound *p0) { PlaySound(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_StopSound(const Sound *p0) { StopSound(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_PauseSound(const Sound *p0) { PauseSound(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ResumeSound(const Sound *p0) { ResumeSound(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsSoundPlaying(const Sound *p0) { return IsSoundPlaying(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetSoundVolume(const Sound *p0, float p1) { SetSoundVolume(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetSoundPitch(const Sound *p0, float p1) { SetSoundPitch(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetSoundPan(const Sound *p0, float p1) { SetSoundPan(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_WaveCopy(Wave *result, const Wave *p0) { *result = WaveCopy(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_WaveCrop(Wave * p0, int p1, int p2) { WaveCrop(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_WaveFormat(Wave * p0, int p1, int p2, int p3) { WaveFormat(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadMusicStream(Music *result, const char * p0) { *result = LoadMusicStream(p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMusicValid(const Music *p0) { return IsMusicValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadMusicStream(const Music *p0) { UnloadMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_PlayMusicStream(const Music *p0) { PlayMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsMusicStreamPlaying(const Music *p0) { return IsMusicStreamPlaying(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UpdateMusicStream(const Music *p0) { UpdateMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_StopMusicStream(const Music *p0) { StopMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_PauseMusicStream(const Music *p0) { PauseMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ResumeMusicStream(const Music *p0) { ResumeMusicStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SeekMusicStream(const Music *p0, float p1) { SeekMusicStream(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMusicVolume(const Music *p0, float p1) { SetMusicVolume(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMusicPitch(const Music *p0, float p1) { SetMusicPitch(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetMusicPan(const Music *p0, float p1) { SetMusicPan(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
float dr_GetMusicTimeLength(const Music *p0) { return GetMusicTimeLength(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_GetMusicTimePlayed(const Music *p0) { return GetMusicTimePlayed(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_LoadAudioStream(AudioStream *result, unsigned int p0, unsigned int p1, unsigned int p2) { *result = LoadAudioStream(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsAudioStreamValid(const AudioStream *p0) { return IsAudioStreamValid(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_UnloadAudioStream(const AudioStream *p0) { UnloadAudioStream(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsAudioStreamProcessed(const AudioStream *p0) { return IsAudioStreamProcessed(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_PlayAudioStream(const AudioStream *p0) { PlayAudioStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_PauseAudioStream(const AudioStream *p0) { PauseAudioStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_ResumeAudioStream(const AudioStream *p0) { ResumeAudioStream(*p0); }

EMSCRIPTEN_KEEPALIVE
bool dr_IsAudioStreamPlaying(const AudioStream *p0) { return IsAudioStreamPlaying(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_StopAudioStream(const AudioStream *p0) { StopAudioStream(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAudioStreamVolume(const AudioStream *p0, float p1) { SetAudioStreamVolume(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAudioStreamPitch(const AudioStream *p0, float p1) { SetAudioStreamPitch(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAudioStreamPan(const AudioStream *p0, float p1) { SetAudioStreamPan(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_SetAudioStreamBufferSizeDefault(int p0) { SetAudioStreamBufferSizeDefault(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Clamp(float p0, float p1, float p2) { return Clamp(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
float dr_Lerp(float p0, float p1, float p2) { return Lerp(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
float dr_Normalize(float p0, float p1, float p2) { return Normalize(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
float dr_Remap(float p0, float p1, float p2, float p3, float p4) { return Remap(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
float dr_Wrap(float p0, float p1, float p2) { return Wrap(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
int dr_FloatEquals(float p0, float p1) { return FloatEquals(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Zero(Vector2 *result) { *result = Vector2Zero(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2One(Vector2 *result) { *result = Vector2One(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Add(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Add(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2AddValue(Vector2 *result, const Vector2 *p0, float p1) { *result = Vector2AddValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Subtract(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Subtract(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2SubtractValue(Vector2 *result, const Vector2 *p0, float p1) { *result = Vector2SubtractValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2Length(const Vector2 *p0) { return Vector2Length(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2LengthSqr(const Vector2 *p0) { return Vector2LengthSqr(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2DotProduct(const Vector2 *p0, const Vector2 *p1) { return Vector2DotProduct(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2CrossProduct(const Vector2 *p0, const Vector2 *p1) { return Vector2CrossProduct(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2Distance(const Vector2 *p0, const Vector2 *p1) { return Vector2Distance(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2DistanceSqr(const Vector2 *p0, const Vector2 *p1) { return Vector2DistanceSqr(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2Angle(const Vector2 *p0, const Vector2 *p1) { return Vector2Angle(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector2LineAngle(const Vector2 *p0, const Vector2 *p1) { return Vector2LineAngle(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Scale(Vector2 *result, const Vector2 *p0, float p1) { *result = Vector2Scale(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Multiply(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Multiply(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Negate(Vector2 *result, const Vector2 *p0) { *result = Vector2Negate(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Divide(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Divide(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Normalize(Vector2 *result, const Vector2 *p0) { *result = Vector2Normalize(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Transform(Vector2 *result, const Vector2 *p0, const Matrix *p1) { *result = Vector2Transform(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Lerp(Vector2 *result, const Vector2 *p0, const Vector2 *p1, float p2) { *result = Vector2Lerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Reflect(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Reflect(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Min(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Min(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Max(Vector2 *result, const Vector2 *p0, const Vector2 *p1) { *result = Vector2Max(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Rotate(Vector2 *result, const Vector2 *p0, float p1) { *result = Vector2Rotate(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2MoveTowards(Vector2 *result, const Vector2 *p0, const Vector2 *p1, float p2) { *result = Vector2MoveTowards(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Invert(Vector2 *result, const Vector2 *p0) { *result = Vector2Invert(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Clamp(Vector2 *result, const Vector2 *p0, const Vector2 *p1, const Vector2 *p2) { *result = Vector2Clamp(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2ClampValue(Vector2 *result, const Vector2 *p0, float p1, float p2) { *result = Vector2ClampValue(*p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
int dr_Vector2Equals(const Vector2 *p0, const Vector2 *p1) { return Vector2Equals(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector2Refract(Vector2 *result, const Vector2 *p0, const Vector2 *p1, float p2) { *result = Vector2Refract(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Zero(Vector3 *result) { *result = Vector3Zero(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3One(Vector3 *result) { *result = Vector3One(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Add(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Add(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3AddValue(Vector3 *result, const Vector3 *p0, float p1) { *result = Vector3AddValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Subtract(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Subtract(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3SubtractValue(Vector3 *result, const Vector3 *p0, float p1) { *result = Vector3SubtractValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Scale(Vector3 *result, const Vector3 *p0, float p1) { *result = Vector3Scale(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Multiply(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Multiply(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3CrossProduct(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3CrossProduct(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Perpendicular(Vector3 *result, const Vector3 *p0) { *result = Vector3Perpendicular(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3Length(const Vector3 *p0) { return Vector3Length(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3LengthSqr(const Vector3 *p0) { return Vector3LengthSqr(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3DotProduct(const Vector3 *p0, const Vector3 *p1) { return Vector3DotProduct(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3Distance(const Vector3 *p0, const Vector3 *p1) { return Vector3Distance(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3DistanceSqr(const Vector3 *p0, const Vector3 *p1) { return Vector3DistanceSqr(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector3Angle(const Vector3 *p0, const Vector3 *p1) { return Vector3Angle(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Negate(Vector3 *result, const Vector3 *p0) { *result = Vector3Negate(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Divide(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Divide(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Normalize(Vector3 *result, const Vector3 *p0) { *result = Vector3Normalize(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Project(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Project(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Reject(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Reject(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3OrthoNormalize(Vector3 * p0, Vector3 * p1) { Vector3OrthoNormalize(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Transform(Vector3 *result, const Vector3 *p0, const Matrix *p1) { *result = Vector3Transform(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3RotateByQuaternion(Vector3 *result, const Vector3 *p0, const Quaternion *p1) { *result = Vector3RotateByQuaternion(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3RotateByAxisAngle(Vector3 *result, const Vector3 *p0, const Vector3 *p1, float p2) { *result = Vector3RotateByAxisAngle(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3MoveTowards(Vector3 *result, const Vector3 *p0, const Vector3 *p1, float p2) { *result = Vector3MoveTowards(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Lerp(Vector3 *result, const Vector3 *p0, const Vector3 *p1, float p2) { *result = Vector3Lerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3CubicHermite(Vector3 *result, const Vector3 *p0, const Vector3 *p1, const Vector3 *p2, const Vector3 *p3, float p4) { *result = Vector3CubicHermite(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Reflect(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Reflect(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Min(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Min(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Max(Vector3 *result, const Vector3 *p0, const Vector3 *p1) { *result = Vector3Max(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Barycenter(Vector3 *result, const Vector3 *p0, const Vector3 *p1, const Vector3 *p2, const Vector3 *p3) { *result = Vector3Barycenter(*p0, *p1, *p2, *p3); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Unproject(Vector3 *result, const Vector3 *p0, const Matrix *p1, const Matrix *p2) { *result = Vector3Unproject(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3ToFloatV(float3 *result, const Vector3 *p0) { *result = Vector3ToFloatV(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Invert(Vector3 *result, const Vector3 *p0) { *result = Vector3Invert(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Clamp(Vector3 *result, const Vector3 *p0, const Vector3 *p1, const Vector3 *p2) { *result = Vector3Clamp(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3ClampValue(Vector3 *result, const Vector3 *p0, float p1, float p2) { *result = Vector3ClampValue(*p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
int dr_Vector3Equals(const Vector3 *p0, const Vector3 *p1) { return Vector3Equals(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector3Refract(Vector3 *result, const Vector3 *p0, const Vector3 *p1, float p2) { *result = Vector3Refract(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Zero(Vector4 *result) { *result = Vector4Zero(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4One(Vector4 *result) { *result = Vector4One(); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Add(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Add(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4AddValue(Vector4 *result, const Vector4 *p0, float p1) { *result = Vector4AddValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Subtract(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Subtract(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4SubtractValue(Vector4 *result, const Vector4 *p0, float p1) { *result = Vector4SubtractValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector4Length(const Vector4 *p0) { return Vector4Length(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector4LengthSqr(const Vector4 *p0) { return Vector4LengthSqr(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector4DotProduct(const Vector4 *p0, const Vector4 *p1) { return Vector4DotProduct(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector4Distance(const Vector4 *p0, const Vector4 *p1) { return Vector4Distance(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_Vector4DistanceSqr(const Vector4 *p0, const Vector4 *p1) { return Vector4DistanceSqr(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Scale(Vector4 *result, const Vector4 *p0, float p1) { *result = Vector4Scale(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Multiply(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Multiply(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Negate(Vector4 *result, const Vector4 *p0) { *result = Vector4Negate(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Divide(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Divide(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Normalize(Vector4 *result, const Vector4 *p0) { *result = Vector4Normalize(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Min(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Min(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Max(Vector4 *result, const Vector4 *p0, const Vector4 *p1) { *result = Vector4Max(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Lerp(Vector4 *result, const Vector4 *p0, const Vector4 *p1, float p2) { *result = Vector4Lerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4MoveTowards(Vector4 *result, const Vector4 *p0, const Vector4 *p1, float p2) { *result = Vector4MoveTowards(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_Vector4Invert(Vector4 *result, const Vector4 *p0) { *result = Vector4Invert(*p0); }

EMSCRIPTEN_KEEPALIVE
int dr_Vector4Equals(const Vector4 *p0, const Vector4 *p1) { return Vector4Equals(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
float dr_MatrixDeterminant(const Matrix *p0) { return MatrixDeterminant(*p0); }

EMSCRIPTEN_KEEPALIVE
float dr_MatrixTrace(const Matrix *p0) { return MatrixTrace(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixTranspose(Matrix *result, const Matrix *p0) { *result = MatrixTranspose(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixInvert(Matrix *result, const Matrix *p0) { *result = MatrixInvert(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixIdentity(Matrix *result) { *result = MatrixIdentity(); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixAdd(Matrix *result, const Matrix *p0, const Matrix *p1) { *result = MatrixAdd(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixSubtract(Matrix *result, const Matrix *p0, const Matrix *p1) { *result = MatrixSubtract(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixMultiply(Matrix *result, const Matrix *p0, const Matrix *p1) { *result = MatrixMultiply(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixMultiplyValue(Matrix *result, const Matrix *p0, float p1) { *result = MatrixMultiplyValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixTranslate(Matrix *result, float p0, float p1, float p2) { *result = MatrixTranslate(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotate(Matrix *result, const Vector3 *p0, float p1) { *result = MatrixRotate(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotateX(Matrix *result, float p0) { *result = MatrixRotateX(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotateY(Matrix *result, float p0) { *result = MatrixRotateY(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotateZ(Matrix *result, float p0) { *result = MatrixRotateZ(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotateXYZ(Matrix *result, const Vector3 *p0) { *result = MatrixRotateXYZ(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixRotateZYX(Matrix *result, const Vector3 *p0) { *result = MatrixRotateZYX(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixScale(Matrix *result, float p0, float p1, float p2) { *result = MatrixScale(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixFrustum(Matrix *result, double p0, double p1, double p2, double p3, double p4, double p5) { *result = MatrixFrustum(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixPerspective(Matrix *result, double p0, double p1, double p2, double p3) { *result = MatrixPerspective(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixOrtho(Matrix *result, double p0, double p1, double p2, double p3, double p4, double p5) { *result = MatrixOrtho(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixLookAt(Matrix *result, const Vector3 *p0, const Vector3 *p1, const Vector3 *p2) { *result = MatrixLookAt(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixToFloatV(float16 *result, const Matrix *p0) { *result = MatrixToFloatV(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionAdd(Quaternion *result, const Quaternion *p0, const Quaternion *p1) { *result = QuaternionAdd(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionAddValue(Quaternion *result, const Quaternion *p0, float p1) { *result = QuaternionAddValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionSubtract(Quaternion *result, const Quaternion *p0, const Quaternion *p1) { *result = QuaternionSubtract(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionSubtractValue(Quaternion *result, const Quaternion *p0, float p1) { *result = QuaternionSubtractValue(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionIdentity(Quaternion *result) { *result = QuaternionIdentity(); }

EMSCRIPTEN_KEEPALIVE
float dr_QuaternionLength(const Quaternion *p0) { return QuaternionLength(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionNormalize(Quaternion *result, const Quaternion *p0) { *result = QuaternionNormalize(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionInvert(Quaternion *result, const Quaternion *p0) { *result = QuaternionInvert(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionMultiply(Quaternion *result, const Quaternion *p0, const Quaternion *p1) { *result = QuaternionMultiply(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionScale(Quaternion *result, const Quaternion *p0, float p1) { *result = QuaternionScale(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionDivide(Quaternion *result, const Quaternion *p0, const Quaternion *p1) { *result = QuaternionDivide(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionLerp(Quaternion *result, const Quaternion *p0, const Quaternion *p1, float p2) { *result = QuaternionLerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionNlerp(Quaternion *result, const Quaternion *p0, const Quaternion *p1, float p2) { *result = QuaternionNlerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionSlerp(Quaternion *result, const Quaternion *p0, const Quaternion *p1, float p2) { *result = QuaternionSlerp(*p0, *p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionCubicHermiteSpline(Quaternion *result, const Quaternion *p0, const Quaternion *p1, const Quaternion *p2, const Quaternion *p3, float p4) { *result = QuaternionCubicHermiteSpline(*p0, *p1, *p2, *p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionFromVector3ToVector3(Quaternion *result, const Vector3 *p0, const Vector3 *p1) { *result = QuaternionFromVector3ToVector3(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionFromMatrix(Quaternion *result, const Matrix *p0) { *result = QuaternionFromMatrix(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionToMatrix(Matrix *result, const Quaternion *p0) { *result = QuaternionToMatrix(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionFromAxisAngle(Quaternion *result, const Vector3 *p0, float p1) { *result = QuaternionFromAxisAngle(*p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionFromEuler(Quaternion *result, float p0, float p1, float p2) { *result = QuaternionFromEuler(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionToEuler(Vector3 *result, const Quaternion *p0) { *result = QuaternionToEuler(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_QuaternionTransform(Quaternion *result, const Quaternion *p0, const Matrix *p1) { *result = QuaternionTransform(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
int dr_QuaternionEquals(const Quaternion *p0, const Quaternion *p1) { return QuaternionEquals(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixCompose(Matrix *result, const Vector3 *p0, const Quaternion *p1, const Vector3 *p2) { *result = MatrixCompose(*p0, *p1, *p2); }

EMSCRIPTEN_KEEPALIVE
void dr_MatrixDecompose(const Matrix *p0, Vector3 * p1, Quaternion * p2, Vector3 * p3) { MatrixDecompose(*p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraForward(Vector3 *result, Camera * p0) { *result = GetCameraForward(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraUp(Vector3 *result, Camera * p0) { *result = GetCameraUp(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraRight(Vector3 *result, Camera * p0) { *result = GetCameraRight(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraMoveForward(Camera * p0, float p1, bool p2) { CameraMoveForward(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraMoveUp(Camera * p0, float p1) { CameraMoveUp(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraMoveRight(Camera * p0, float p1, bool p2) { CameraMoveRight(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraMoveToTarget(Camera * p0, float p1) { CameraMoveToTarget(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraYaw(Camera * p0, float p1, bool p2) { CameraYaw(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraPitch(Camera * p0, float p1, bool p2, bool p3, bool p4) { CameraPitch(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
void dr_CameraRoll(Camera * p0, float p1) { CameraRoll(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraViewMatrix(Matrix *result, Camera * p0) { *result = GetCameraViewMatrix(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_GetCameraProjectionMatrix(Matrix *result, Camera * p0, float p1) { *result = GetCameraProjectionMatrix(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlMatrixMode(int p0) { rlMatrixMode(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlPushMatrix(void) { rlPushMatrix(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlPopMatrix(void) { rlPopMatrix(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlLoadIdentity(void) { rlLoadIdentity(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlTranslatef(float p0, float p1, float p2) { rlTranslatef(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlRotatef(float p0, float p1, float p2, float p3) { rlRotatef(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlScalef(float p0, float p1, float p2) { rlScalef(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlFrustum(double p0, double p1, double p2, double p3, double p4, double p5) { rlFrustum(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_rlOrtho(double p0, double p1, double p2, double p3, double p4, double p5) { rlOrtho(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_rlViewport(int p0, int p1, int p2, int p3) { rlViewport(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetClipPlanes(double p0, double p1) { rlSetClipPlanes(p0, p1); }

EMSCRIPTEN_KEEPALIVE
double dr_rlGetCullDistanceNear(void) { return rlGetCullDistanceNear(); }

EMSCRIPTEN_KEEPALIVE
double dr_rlGetCullDistanceFar(void) { return rlGetCullDistanceFar(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlBegin(int p0) { rlBegin(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnd(void) { rlEnd(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlVertex2i(int p0, int p1) { rlVertex2i(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlVertex2f(float p0, float p1) { rlVertex2f(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlVertex3f(float p0, float p1, float p2) { rlVertex3f(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlTexCoord2f(float p0, float p1) { rlTexCoord2f(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlNormal3f(float p0, float p1, float p2) { rlNormal3f(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlColor4ub(unsigned char p0, unsigned char p1, unsigned char p2, unsigned char p3) { rlColor4ub(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlColor3f(float p0, float p1, float p2) { rlColor3f(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlColor4f(float p0, float p1, float p2, float p3) { rlColor4f(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
bool dr_rlEnableVertexArray(unsigned int p0) { return rlEnableVertexArray(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableVertexArray(void) { rlDisableVertexArray(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableVertexBuffer(unsigned int p0) { rlEnableVertexBuffer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableVertexBuffer(void) { rlDisableVertexBuffer(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableVertexBufferElement(unsigned int p0) { rlEnableVertexBufferElement(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableVertexBufferElement(void) { rlDisableVertexBufferElement(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableVertexAttribute(unsigned int p0) { rlEnableVertexAttribute(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableVertexAttribute(unsigned int p0) { rlDisableVertexAttribute(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableStatePointer(int p0) { rlDisableStatePointer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlActiveTextureSlot(int p0) { rlActiveTextureSlot(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableTexture(unsigned int p0) { rlEnableTexture(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableTexture(void) { rlDisableTexture(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableTextureCubemap(unsigned int p0) { rlEnableTextureCubemap(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableTextureCubemap(void) { rlDisableTextureCubemap(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlTextureParameters(unsigned int p0, int p1, int p2) { rlTextureParameters(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlCubemapParameters(unsigned int p0, int p1, int p2) { rlCubemapParameters(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableShader(unsigned int p0) { rlEnableShader(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableShader(void) { rlDisableShader(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableFramebuffer(unsigned int p0) { rlEnableFramebuffer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableFramebuffer(void) { rlDisableFramebuffer(); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlGetActiveFramebuffer(void) { return rlGetActiveFramebuffer(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlActiveDrawBuffers(int p0) { rlActiveDrawBuffers(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlBlitFramebuffer(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) { rlBlitFramebuffer(p0, p1, p2, p3, p4, p5, p6, p7, p8); }

EMSCRIPTEN_KEEPALIVE
void dr_rlBindFramebuffer(unsigned int p0, unsigned int p1) { rlBindFramebuffer(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableColorBlend(void) { rlEnableColorBlend(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableColorBlend(void) { rlDisableColorBlend(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableDepthTest(void) { rlEnableDepthTest(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableDepthTest(void) { rlDisableDepthTest(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableDepthMask(void) { rlEnableDepthMask(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableDepthMask(void) { rlDisableDepthMask(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableBackfaceCulling(void) { rlEnableBackfaceCulling(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableBackfaceCulling(void) { rlDisableBackfaceCulling(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlColorMask(bool p0, bool p1, bool p2, bool p3) { rlColorMask(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetCullFace(int p0) { rlSetCullFace(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableScissorTest(void) { rlEnableScissorTest(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableScissorTest(void) { rlDisableScissorTest(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlScissor(int p0, int p1, int p2, int p3) { rlScissor(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnablePointMode(void) { rlEnablePointMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisablePointMode(void) { rlDisablePointMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetPointSize(float p0) { rlSetPointSize(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_rlGetPointSize(void) { return rlGetPointSize(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableWireMode(void) { rlEnableWireMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableWireMode(void) { rlDisableWireMode(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetLineWidth(float p0) { rlSetLineWidth(p0); }

EMSCRIPTEN_KEEPALIVE
float dr_rlGetLineWidth(void) { return rlGetLineWidth(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableSmoothLines(void) { rlEnableSmoothLines(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableSmoothLines(void) { rlDisableSmoothLines(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlEnableStereoRender(void) { rlEnableStereoRender(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDisableStereoRender(void) { rlDisableStereoRender(); }

EMSCRIPTEN_KEEPALIVE
bool dr_rlIsStereoRenderEnabled(void) { return rlIsStereoRenderEnabled(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlClearColor(unsigned char p0, unsigned char p1, unsigned char p2, unsigned char p3) { rlClearColor(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlClearScreenBuffers(void) { rlClearScreenBuffers(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlCheckErrors(void) { rlCheckErrors(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetBlendMode(int p0) { rlSetBlendMode(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetBlendFactors(int p0, int p1, int p2) { rlSetBlendFactors(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetBlendFactorsSeparate(int p0, int p1, int p2, int p3, int p4, int p5) { rlSetBlendFactorsSeparate(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_rlglInit(int p0, int p1) { rlglInit(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlglClose(void) { rlglClose(); }

EMSCRIPTEN_KEEPALIVE
int dr_rlGetVersion(void) { return rlGetVersion(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetFramebufferWidth(int p0) { rlSetFramebufferWidth(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_rlGetFramebufferWidth(void) { return rlGetFramebufferWidth(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetFramebufferHeight(int p0) { rlSetFramebufferHeight(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_rlGetFramebufferHeight(void) { return rlGetFramebufferHeight(); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlGetTextureIdDefault(void) { return rlGetTextureIdDefault(); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlGetShaderIdDefault(void) { return rlGetShaderIdDefault(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlLoadRenderBatch(rlRenderBatch *result, int p0, int p1) { *result = rlLoadRenderBatch(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadRenderBatch(const rlRenderBatch *p0) { rlUnloadRenderBatch(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDrawRenderBatch(rlRenderBatch * p0) { rlDrawRenderBatch(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetRenderBatchActive(rlRenderBatch * p0) { rlSetRenderBatchActive(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDrawRenderBatchActive(void) { rlDrawRenderBatchActive(); }

EMSCRIPTEN_KEEPALIVE
bool dr_rlCheckRenderBatchLimit(int p0) { return rlCheckRenderBatchLimit(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetTexture(unsigned int p0) { rlSetTexture(p0); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadVertexArray(void) { return rlLoadVertexArray(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadVertexArray(unsigned int p0) { rlUnloadVertexArray(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadVertexBuffer(unsigned int p0) { rlUnloadVertexBuffer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetVertexAttribute(unsigned int p0, int p1, int p2, bool p3, int p4, int p5) { rlSetVertexAttribute(p0, p1, p2, p3, p4, p5); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetVertexAttributeDivisor(unsigned int p0, int p1) { rlSetVertexAttributeDivisor(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDrawVertexArray(int p0, int p1) { rlDrawVertexArray(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlDrawVertexArrayInstanced(int p0, int p1, int p2) { rlDrawVertexArrayInstanced(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadTextureDepth(int p0, int p1, bool p2) { return rlLoadTextureDepth(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
const char * dr_rlGetPixelFormatName(unsigned int p0) { return rlGetPixelFormatName(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadTexture(unsigned int p0) { rlUnloadTexture(p0); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadFramebuffer(void) { return rlLoadFramebuffer(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlFramebufferAttach(unsigned int p0, unsigned int p1, int p2, int p3, int p4) { rlFramebufferAttach(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
bool dr_rlFramebufferComplete(unsigned int p0) { return rlFramebufferComplete(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadFramebuffer(unsigned int p0) { rlUnloadFramebuffer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlResizeFramebuffer(int p0, int p1) { rlResizeFramebuffer(p0, p1); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadShader(const char * p0, int p1) { return rlLoadShader(p0, p1); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadShaderProgram(const char * p0, const char * p1) { return rlLoadShaderProgram(p0, p1); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadShaderProgramEx(unsigned int p0, unsigned int p1) { return rlLoadShaderProgramEx(p0, p1); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlLoadShaderProgramCompute(unsigned int p0) { return rlLoadShaderProgramCompute(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadShader(unsigned int p0) { rlUnloadShader(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadShaderProgram(unsigned int p0) { rlUnloadShaderProgram(p0); }

EMSCRIPTEN_KEEPALIVE
int dr_rlGetLocationUniform(unsigned int p0, const char * p1) { return rlGetLocationUniform(p0, p1); }

EMSCRIPTEN_KEEPALIVE
int dr_rlGetLocationAttrib(unsigned int p0, const char * p1) { return rlGetLocationAttrib(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetUniformMatrix(int p0, const Matrix *p1) { rlSetUniformMatrix(p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetUniformSampler(int p0, unsigned int p1) { rlSetUniformSampler(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlComputeShaderDispatch(unsigned int p0, unsigned int p1, unsigned int p2) { rlComputeShaderDispatch(p0, p1, p2); }

EMSCRIPTEN_KEEPALIVE
void dr_rlUnloadShaderBuffer(unsigned int p0) { rlUnloadShaderBuffer(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlBindShaderBuffer(unsigned int p0, unsigned int p1) { rlBindShaderBuffer(p0, p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlCopyShaderBuffer(unsigned int p0, unsigned int p1, unsigned int p2, unsigned int p3, unsigned int p4) { rlCopyShaderBuffer(p0, p1, p2, p3, p4); }

EMSCRIPTEN_KEEPALIVE
unsigned int dr_rlGetShaderBufferSize(unsigned int p0) { return rlGetShaderBufferSize(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlBindImageTexture(unsigned int p0, unsigned int p1, int p2, bool p3) { rlBindImageTexture(p0, p1, p2, p3); }

EMSCRIPTEN_KEEPALIVE
void dr_rlGetMatrixModelview(Matrix *result) { *result = rlGetMatrixModelview(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlGetMatrixProjection(Matrix *result) { *result = rlGetMatrixProjection(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlGetMatrixTransform(Matrix *result) { *result = rlGetMatrixTransform(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlGetMatrixProjectionStereo(Matrix *result, int p0) { *result = rlGetMatrixProjectionStereo(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlGetMatrixViewOffsetStereo(Matrix *result, int p0) { *result = rlGetMatrixViewOffsetStereo(p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetMatrixProjection(const Matrix *p0) { rlSetMatrixProjection(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetMatrixModelview(const Matrix *p0) { rlSetMatrixModelview(*p0); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetMatrixProjectionStereo(const Matrix *p0, const Matrix *p1) { rlSetMatrixProjectionStereo(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlSetMatrixViewOffsetStereo(const Matrix *p0, const Matrix *p1) { rlSetMatrixViewOffsetStereo(*p0, *p1); }

EMSCRIPTEN_KEEPALIVE
void dr_rlLoadDrawCube(void) { rlLoadDrawCube(); }

EMSCRIPTEN_KEEPALIVE
void dr_rlLoadDrawQuad(void) { rlLoadDrawQuad(); }

