// This file is generated by generate_modules.ts
export const MODULE_NAMES = [
  "Animation",
  "Application",
  "Assets",
  "Audio",
  "AudioDevice",
  "AudioStream",
  "Automation",
  "Blend",
  "Camera",
  "Camera2D",
  "Camera3D",
  "CameraControls",
  "Clipboard",
  "Collision",
  "Collision2D",
  "Collision3D",
  "Colors",
  "Compression",
  "Coordinates",
  "Core",
  "Cubemap",
  "Cursor",
  "Directories",
  "Drawing",
  "DroppedFiles",
  "Events",
  "Files",
  "Font",
  "Framebuffer",
  "Gamepad",
  "Gestures",
  "Glyph",
  "Graphics",
  "Hashing",
  "Image",
  "ImmediateMode",
  "Input",
  "Keyboard",
  "Logging",
  "LowLevelShader",
  "LowLevelTexture",
  "Material",
  "Math",
  "Matrix",
  "Memory",
  "Mesh",
  "Model",
  "ModelCollision",
  "Monitor",
  "Mouse",
  "Music",
  "Paths",
  "Quaternion",
  "Random",
  "RenderBatch",
  "RenderState",
  "RenderTexture",
  "Rlgl",
  "ScalarMath",
  "Scissor",
  "Screen",
  "ShaderBuffer",
  "Shaders",
  "Shapes",
  "Shapes2D",
  "Shapes3D",
  "Skeleton",
  "Sound",
  "Splines",
  "Text",
  "Texture",
  "TextureDrawing",
  "Timing",
  "Touch",
  "VR",
  "Vector2",
  "Vector3",
  "Vector4",
  "VertexBuffer",
  "Wave",
  "Window",
] as const;
export const FUNCTION_MODULES = {
  "InitWindow": [
    "Core",
    "Window",
  ],
  "CloseWindow": [
    "Core",
    "Window",
  ],
  "WindowShouldClose": [
    "Core",
    "Window",
  ],
  "IsWindowReady": [
    "Core",
    "Window",
  ],
  "IsWindowFullscreen": [
    "Core",
    "Window",
  ],
  "IsWindowHidden": [
    "Core",
    "Window",
  ],
  "IsWindowMinimized": [
    "Core",
    "Window",
  ],
  "IsWindowMaximized": [
    "Core",
    "Window",
  ],
  "IsWindowFocused": [
    "Core",
    "Window",
  ],
  "IsWindowResized": [
    "Core",
    "Window",
  ],
  "IsWindowState": [
    "Core",
    "Window",
  ],
  "SetWindowState": [
    "Core",
    "Window",
  ],
  "ClearWindowState": [
    "Core",
    "Window",
  ],
  "ToggleFullscreen": [
    "Core",
    "Window",
  ],
  "ToggleBorderlessWindowed": [
    "Core",
    "Window",
  ],
  "MaximizeWindow": [
    "Core",
    "Window",
  ],
  "MinimizeWindow": [
    "Core",
    "Window",
  ],
  "RestoreWindow": [
    "Core",
    "Window",
  ],
  "SetWindowIcon": [
    "Core",
    "Window",
  ],
  "SetWindowIcons": [
    "Core",
    "Window",
  ],
  "SetWindowTitle": [
    "Core",
    "Window",
  ],
  "SetWindowPosition": [
    "Core",
    "Window",
  ],
  "SetWindowMonitor": [
    "Core",
    "Window",
    "Monitor",
  ],
  "SetWindowMinSize": [
    "Core",
    "Window",
  ],
  "SetWindowMaxSize": [
    "Core",
    "Window",
  ],
  "SetWindowSize": [
    "Core",
    "Window",
  ],
  "SetWindowOpacity": [
    "Core",
    "Window",
  ],
  "SetWindowFocused": [
    "Core",
    "Window",
  ],
  "GetWindowHandle": [
    "Core",
    "Window",
  ],
  "GetScreenWidth": [
    "Core",
    "Screen",
  ],
  "GetScreenHeight": [
    "Core",
    "Screen",
  ],
  "GetRenderWidth": [
    "Core",
    "Screen",
  ],
  "GetRenderHeight": [
    "Core",
    "Screen",
  ],
  "GetMonitorCount": [
    "Core",
    "Monitor",
  ],
  "GetCurrentMonitor": [
    "Core",
    "Monitor",
  ],
  "GetMonitorPosition": [
    "Core",
    "Monitor",
  ],
  "GetMonitorWidth": [
    "Core",
    "Monitor",
  ],
  "GetMonitorHeight": [
    "Core",
    "Monitor",
  ],
  "GetMonitorPhysicalWidth": [
    "Core",
    "Monitor",
  ],
  "GetMonitorPhysicalHeight": [
    "Core",
    "Monitor",
  ],
  "GetMonitorRefreshRate": [
    "Core",
    "Monitor",
  ],
  "GetWindowPosition": [
    "Core",
    "Window",
  ],
  "GetWindowScaleDPI": [
    "Core",
    "Window",
    "Monitor",
  ],
  "GetMonitorName": [
    "Core",
    "Monitor",
  ],
  "SetClipboardText": [
    "Core",
    "Clipboard",
  ],
  "GetClipboardText": [
    "Core",
    "Clipboard",
  ],
  "GetClipboardImage": [
    "Core",
    "Clipboard",
  ],
  "EnableEventWaiting": [
    "Core",
    "Events",
  ],
  "DisableEventWaiting": [
    "Core",
    "Events",
  ],
  "ShowCursor": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "HideCursor": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "IsCursorHidden": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "EnableCursor": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "DisableCursor": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "IsCursorOnScreen": [
    "Core",
    "Screen",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "ClearBackground": [
    "Core",
    "Drawing",
    "Graphics",
  ],
  "BeginDrawing": [
    "Core",
    "Drawing",
    "Graphics",
  ],
  "EndDrawing": [
    "Core",
    "Drawing",
    "Graphics",
  ],
  "BeginMode2D": [
    "Core",
    "Drawing",
    "Camera2D",
    "Camera",
    "Graphics",
  ],
  "EndMode2D": [
    "Core",
    "Drawing",
    "Camera2D",
    "Camera",
    "Graphics",
  ],
  "BeginMode3D": [
    "Core",
    "Drawing",
    "Camera3D",
    "Camera",
    "Graphics",
  ],
  "EndMode3D": [
    "Core",
    "Drawing",
    "Camera3D",
    "Camera",
    "Graphics",
  ],
  "BeginTextureMode": [
    "Core",
    "Drawing",
    "RenderTexture",
    "Graphics",
  ],
  "EndTextureMode": [
    "Core",
    "Drawing",
    "RenderTexture",
    "Graphics",
  ],
  "BeginShaderMode": [
    "Core",
    "Drawing",
    "Shaders",
    "Graphics",
  ],
  "EndShaderMode": [
    "Core",
    "Drawing",
    "Shaders",
    "Graphics",
  ],
  "BeginBlendMode": [
    "Core",
    "Drawing",
    "Blend",
    "Graphics",
  ],
  "EndBlendMode": [
    "Core",
    "Drawing",
    "Blend",
    "Graphics",
  ],
  "BeginScissorMode": [
    "Core",
    "Drawing",
    "Scissor",
    "Graphics",
  ],
  "EndScissorMode": [
    "Core",
    "Drawing",
    "Scissor",
    "Graphics",
  ],
  "BeginVrStereoMode": [
    "Core",
    "Drawing",
    "VR",
    "Graphics",
  ],
  "EndVrStereoMode": [
    "Core",
    "Drawing",
    "VR",
    "Graphics",
  ],
  "LoadVrStereoConfig": [
    "Core",
    "VR",
  ],
  "UnloadVrStereoConfig": [
    "Core",
    "VR",
  ],
  "LoadShader": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "LoadShaderFromMemory": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "IsShaderValid": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "GetShaderLocation": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "GetShaderLocationAttrib": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "SetShaderValue": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "SetShaderValueV": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "SetShaderValueMatrix": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "SetShaderValueTexture": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "UnloadShader": [
    "Core",
    "Shaders",
    "Graphics",
  ],
  "GetScreenToWorldRay": [
    "Core",
    "Screen",
    "Camera3D",
    "Coordinates",
    "Camera",
  ],
  "GetScreenToWorldRayEx": [
    "Core",
    "Screen",
    "Camera3D",
    "Coordinates",
    "Camera",
  ],
  "GetWorldToScreen": [
    "Core",
    "Screen",
    "Camera3D",
    "Coordinates",
    "Camera",
  ],
  "GetWorldToScreenEx": [
    "Core",
    "Screen",
    "Camera3D",
    "Coordinates",
    "Camera",
  ],
  "GetWorldToScreen2D": [
    "Core",
    "Screen",
    "Camera2D",
    "Camera3D",
    "Coordinates",
    "Camera",
  ],
  "GetScreenToWorld2D": [
    "Core",
    "Screen",
    "Camera2D",
    "Coordinates",
    "Camera",
  ],
  "GetCameraMatrix": [
    "Core",
    "Camera3D",
    "Camera",
  ],
  "GetCameraMatrix2D": [
    "Core",
    "Camera3D",
    "Camera",
  ],
  "SetTargetFPS": [
    "Core",
    "Timing",
  ],
  "GetFrameTime": [
    "Core",
    "Timing",
  ],
  "GetTime": [
    "Core",
    "Timing",
  ],
  "GetFPS": [
    "Core",
    "Timing",
  ],
  "SwapScreenBuffer": [
    "Core",
    "Screen",
    "Timing",
  ],
  "PollInputEvents": [
    "Core",
  ],
  "WaitTime": [
    "Core",
    "Timing",
  ],
  "SetRandomSeed": [
    "Core",
    "Random",
  ],
  "GetRandomValue": [
    "Core",
    "Random",
  ],
  "LoadRandomSequence": [
    "Core",
    "Random",
  ],
  "UnloadRandomSequence": [
    "Core",
    "Random",
  ],
  "TakeScreenshot": [
    "Core",
    "Screen",
  ],
  "SetConfigFlags": [
    "Core",
    "Application",
  ],
  "OpenURL": [
    "Core",
    "Application",
  ],
  "SetTraceLogLevel": [
    "Core",
    "Logging",
  ],
  "TraceLog": [
    "Core",
    "Logging",
  ],
  "SetTraceLogCallback": [
    "Core",
    "Logging",
  ],
  "MemAlloc": [
    "Core",
    "Memory",
  ],
  "MemRealloc": [
    "Core",
    "Memory",
  ],
  "MemFree": [
    "Core",
    "Memory",
  ],
  "LoadFileData": [
    "Core",
    "Files",
  ],
  "UnloadFileData": [
    "Core",
    "Files",
  ],
  "SaveFileData": [
    "Core",
    "Files",
  ],
  "ExportDataAsCode": [
    "Core",
  ],
  "LoadFileText": [
    "Core",
    "Files",
  ],
  "UnloadFileText": [
    "Core",
    "Files",
  ],
  "SaveFileText": [
    "Core",
    "Files",
  ],
  "SetLoadFileDataCallback": [
    "Core",
    "Files",
  ],
  "SetSaveFileDataCallback": [
    "Core",
    "Files",
  ],
  "SetLoadFileTextCallback": [
    "Core",
    "Files",
  ],
  "SetSaveFileTextCallback": [
    "Core",
    "Files",
  ],
  "FileRename": [
    "Core",
    "Files",
  ],
  "FileRemove": [
    "Core",
    "Files",
  ],
  "FileCopy": [
    "Core",
    "Files",
  ],
  "FileMove": [
    "Core",
    "Files",
  ],
  "FileTextReplace": [
    "Core",
    "Files",
  ],
  "FileTextFindIndex": [
    "Core",
    "Files",
  ],
  "FileExists": [
    "Core",
    "Files",
  ],
  "DirectoryExists": [
    "Core",
    "Directories",
  ],
  "IsFileExtension": [
    "Core",
    "Files",
    "Paths",
  ],
  "GetFileLength": [
    "Core",
    "Files",
  ],
  "GetFileModTime": [
    "Core",
    "Files",
  ],
  "GetFileExtension": [
    "Core",
    "Files",
    "Paths",
  ],
  "GetFileName": [
    "Core",
    "Files",
    "Paths",
  ],
  "GetFileNameWithoutExt": [
    "Core",
    "Files",
    "Paths",
  ],
  "GetDirectoryPath": [
    "Core",
    "Directories",
    "Paths",
  ],
  "GetPrevDirectoryPath": [
    "Core",
    "Directories",
    "Paths",
  ],
  "GetWorkingDirectory": [
    "Core",
    "Directories",
  ],
  "GetApplicationDirectory": [
    "Core",
    "Directories",
  ],
  "MakeDirectory": [
    "Core",
    "Directories",
  ],
  "ChangeDirectory": [
    "Core",
    "Directories",
  ],
  "IsPathFile": [
    "Core",
    "Files",
    "Paths",
  ],
  "IsFileNameValid": [
    "Core",
    "Files",
    "Paths",
  ],
  "LoadDirectoryFiles": [
    "Core",
    "Files",
    "Directories",
  ],
  "LoadDirectoryFilesEx": [
    "Core",
    "Files",
    "Directories",
  ],
  "UnloadDirectoryFiles": [
    "Core",
    "Files",
    "Directories",
  ],
  "IsFileDropped": [
    "Core",
    "Files",
    "DroppedFiles",
  ],
  "LoadDroppedFiles": [
    "Core",
    "Files",
    "DroppedFiles",
  ],
  "UnloadDroppedFiles": [
    "Core",
    "Files",
    "DroppedFiles",
  ],
  "GetDirectoryFileCount": [
    "Core",
    "Files",
    "Directories",
  ],
  "GetDirectoryFileCountEx": [
    "Core",
    "Files",
    "Directories",
  ],
  "CompressData": [
    "Core",
    "Compression",
  ],
  "DecompressData": [
    "Core",
    "Compression",
  ],
  "EncodeDataBase64": [
    "Core",
    "Compression",
  ],
  "DecodeDataBase64": [
    "Core",
    "Compression",
  ],
  "ComputeCRC32": [
    "Core",
    "Hashing",
  ],
  "ComputeMD5": [
    "Core",
    "Hashing",
  ],
  "ComputeSHA1": [
    "Core",
    "Hashing",
  ],
  "ComputeSHA256": [
    "Core",
    "Hashing",
  ],
  "LoadAutomationEventList": [
    "Core",
    "Automation",
  ],
  "UnloadAutomationEventList": [
    "Core",
    "Automation",
  ],
  "ExportAutomationEventList": [
    "Core",
    "Automation",
  ],
  "SetAutomationEventList": [
    "Core",
    "Automation",
  ],
  "SetAutomationEventBaseFrame": [
    "Core",
    "Automation",
  ],
  "StartAutomationEventRecording": [
    "Core",
    "Automation",
  ],
  "StopAutomationEventRecording": [
    "Core",
    "Automation",
  ],
  "PlayAutomationEvent": [
    "Core",
    "Automation",
  ],
  "IsKeyPressed": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "IsKeyPressedRepeat": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "IsKeyDown": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "IsKeyReleased": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "IsKeyUp": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "GetKeyPressed": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "GetCharPressed": [
    "Core",
  ],
  "GetKeyName": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "SetExitKey": [
    "Core",
    "Keyboard",
    "Input",
  ],
  "IsGamepadAvailable": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "GetGamepadName": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "IsGamepadButtonPressed": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "IsGamepadButtonDown": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "IsGamepadButtonReleased": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "IsGamepadButtonUp": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "GetGamepadButtonPressed": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "GetGamepadAxisCount": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "GetGamepadAxisMovement": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "SetGamepadMappings": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "SetGamepadVibration": [
    "Core",
    "Gamepad",
    "Input",
  ],
  "IsMouseButtonPressed": [
    "Core",
    "Mouse",
    "Input",
  ],
  "IsMouseButtonDown": [
    "Core",
    "Mouse",
    "Input",
  ],
  "IsMouseButtonReleased": [
    "Core",
    "Mouse",
    "Input",
  ],
  "IsMouseButtonUp": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMouseX": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMouseY": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMousePosition": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMouseDelta": [
    "Core",
    "Mouse",
    "Input",
  ],
  "SetMousePosition": [
    "Core",
    "Mouse",
    "Input",
  ],
  "SetMouseOffset": [
    "Core",
    "Mouse",
    "Input",
  ],
  "SetMouseScale": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMouseWheelMove": [
    "Core",
    "Mouse",
    "Input",
  ],
  "GetMouseWheelMoveV": [
    "Core",
    "Mouse",
    "Input",
  ],
  "SetMouseCursor": [
    "Core",
    "Mouse",
    "Cursor",
    "Input",
  ],
  "GetTouchX": [
    "Core",
    "Touch",
    "Input",
  ],
  "GetTouchY": [
    "Core",
    "Touch",
    "Input",
  ],
  "GetTouchPosition": [
    "Core",
    "Touch",
    "Input",
  ],
  "GetTouchPointId": [
    "Core",
    "Touch",
    "Input",
  ],
  "GetTouchPointCount": [
    "Core",
    "Touch",
    "Input",
  ],
  "SetGesturesEnabled": [
    "Core",
    "Gestures",
    "Input",
  ],
  "IsGestureDetected": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGestureDetected": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGestureHoldDuration": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGestureDragVector": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGestureDragAngle": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGesturePinchVector": [
    "Core",
    "Gestures",
    "Input",
  ],
  "GetGesturePinchAngle": [
    "Core",
    "Gestures",
    "Input",
  ],
  "UpdateCamera": [
    "Core",
    "Camera",
  ],
  "UpdateCameraPro": [
    "Core",
    "Camera",
  ],
  "SetShapesTexture": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "GetShapesTexture": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "GetShapesTextureRectangle": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawPixel": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawPixelV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLine": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLineV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLineEx": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLineStrip": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLineBezier": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawLineDashed": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircle": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleGradient": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleSector": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleSectorLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawCircleLinesV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawEllipse": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawEllipseV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawEllipseLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawEllipseLinesV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRing": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRingLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangle": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleRec": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectanglePro": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleGradientV": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleGradientH": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleGradientEx": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleLinesEx": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleRounded": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleRoundedLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawRectangleRoundedLinesEx": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawTriangle": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawTriangleLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawTriangleFan": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawTriangleStrip": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawPoly": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawPolyLines": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawPolyLinesEx": [
    "Shapes2D",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineLinear": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineBasis": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineCatmullRom": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineBezierQuadratic": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineBezierCubic": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineSegmentLinear": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineSegmentBasis": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineSegmentCatmullRom": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineSegmentBezierQuadratic": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "DrawSplineSegmentBezierCubic": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "GetSplinePointLinear": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "GetSplinePointBasis": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "GetSplinePointCatmullRom": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "GetSplinePointBezierQuad": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "GetSplinePointBezierCubic": [
    "Shapes2D",
    "Splines",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionRecs": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionCircles": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionCircleRec": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionCircleLine": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionPointRec": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionPointCircle": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionPointTriangle": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionPointLine": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionPointPoly": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "CheckCollisionLines": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "GetCollisionRec": [
    "Shapes2D",
    "Collision2D",
    "Collision",
    "Shapes",
    "Graphics",
  ],
  "LoadImage": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageRaw": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageAnim": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageAnimFromMemory": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageFromMemory": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageFromTexture": [
    "Image",
    "Texture",
    "Graphics",
    "Assets",
  ],
  "LoadImageFromScreen": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "IsImageValid": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "UnloadImage": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ExportImage": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ExportImageToMemory": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ExportImageAsCode": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageColor": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageGradientLinear": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageGradientRadial": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageGradientSquare": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageChecked": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageWhiteNoise": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImagePerlinNoise": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageCellular": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GenImageText": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageCopy": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageFromImage": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageFromChannel": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageText": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageTextEx": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageFormat": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageToPOT": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageCrop": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageAlphaCrop": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageAlphaClear": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageAlphaMask": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageAlphaPremultiply": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageBlurGaussian": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageKernelConvolution": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageResize": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageResizeNN": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageResizeCanvas": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageMipmaps": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDither": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageFlipVertical": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageFlipHorizontal": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageRotate": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageRotateCW": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageRotateCCW": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorTint": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorInvert": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorGrayscale": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorContrast": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorBrightness": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageColorReplace": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImageColors": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadImagePalette": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "UnloadImageColors": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "UnloadImagePalette": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GetImageAlphaBorder": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "GetImageColor": [
    "Colors",
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageClearBackground": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawPixel": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawPixelV": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawLine": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawLineV": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawLineEx": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawCircle": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawCircleV": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawCircleLines": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawCircleLinesV": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawRectangle": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawRectangleV": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawRectangleRec": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawRectangleLines": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTriangle": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTriangleEx": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTriangleLines": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTriangleFan": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTriangleStrip": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDraw": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawText": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "ImageDrawTextEx": [
    "Image",
    "Graphics",
    "Assets",
  ],
  "LoadTexture": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "LoadTextureFromImage": [
    "Image",
    "Texture",
    "Graphics",
    "Assets",
  ],
  "LoadTextureCubemap": [
    "Texture",
    "Cubemap",
    "Graphics",
    "Assets",
  ],
  "LoadRenderTexture": [
    "RenderTexture",
    "Texture",
    "Graphics",
    "Assets",
  ],
  "IsTextureValid": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "UnloadTexture": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "IsRenderTextureValid": [
    "RenderTexture",
    "Texture",
    "Graphics",
    "Assets",
  ],
  "UnloadRenderTexture": [
    "RenderTexture",
    "Texture",
    "Graphics",
    "Assets",
  ],
  "UpdateTexture": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "UpdateTextureRec": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "GenTextureMipmaps": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "SetTextureFilter": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "SetTextureWrap": [
    "Texture",
    "Graphics",
    "Assets",
  ],
  "DrawTexture": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "DrawTextureV": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "DrawTextureEx": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "DrawTextureRec": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "DrawTexturePro": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "DrawTextureNPatch": [
    "Texture",
    "TextureDrawing",
    "Graphics",
    "Assets",
  ],
  "ColorIsEqual": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "Fade": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorToInt": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorNormalize": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorFromNormalized": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorToHSV": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorFromHSV": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorTint": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorBrightness": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorContrast": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorAlpha": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorAlphaBlend": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "ColorLerp": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "GetColor": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "GetPixelColor": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "SetPixelColor": [
    "Colors",
    "Graphics",
    "Assets",
  ],
  "GetPixelDataSize": [
    "Graphics",
    "Assets",
  ],
  "GetFontDefault": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "LoadFont": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "LoadFontEx": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "LoadFontFromImage": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "LoadFontFromMemory": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "IsFontValid": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "LoadFontData": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "GenImageFontAtlas": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "UnloadFontData": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "UnloadFont": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "ExportFontAsCode": [
    "Text",
    "Font",
    "Graphics",
    "Assets",
  ],
  "DrawFPS": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "DrawText": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "DrawTextEx": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "DrawTextPro": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "DrawTextCodepoint": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "DrawTextCodepoints": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "SetTextLineSpacing": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "MeasureText": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "MeasureTextEx": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "MeasureTextCodepoints": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetGlyphIndex": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetGlyphInfo": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetGlyphAtlasRec": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "LoadUTF8": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "UnloadUTF8": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "LoadCodepoints": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "UnloadCodepoints": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetCodepointCount": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetCodepoint": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetCodepointNext": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "GetCodepointPrevious": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "CodepointToUTF8": [
    "Text",
    "Glyph",
    "Graphics",
    "Assets",
  ],
  "LoadTextLines": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "UnloadTextLines": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextCopy": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextIsEqual": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextLength": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextFormat": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextSubtext": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextRemoveSpaces": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "GetTextBetween": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextReplace": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextReplaceAlloc": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextReplaceBetween": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextReplaceBetweenAlloc": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextInsert": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextInsertAlloc": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextJoin": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextSplit": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextAppend": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextFindIndex": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToUpper": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToLower": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToPascal": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToSnake": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToCamel": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToInteger": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "TextToFloat": [
    "Text",
    "Graphics",
    "Assets",
  ],
  "DrawLine3D": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawPoint3D": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCircle3D": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawTriangle3D": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawTriangleStrip3D": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCube": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCubeV": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCubeWires": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCubeWiresV": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawSphere": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawSphereEx": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawSphereWires": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCylinder": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCylinderEx": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCylinderWires": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCylinderWiresEx": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCapsule": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawCapsuleWires": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawPlane": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawRay": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "DrawGrid": [
    "Shapes3D",
    "Shapes",
    "Model",
    "Graphics",
  ],
  "LoadModel": [
    "Model",
    "Graphics",
    "Assets",
  ],
  "LoadModelFromMesh": [
    "Model",
    "Mesh",
    "Graphics",
    "Assets",
  ],
  "IsModelValid": [
    "Model",
    "Graphics",
    "Assets",
  ],
  "UnloadModel": [
    "Model",
    "Graphics",
    "Assets",
  ],
  "GetModelBoundingBox": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "DrawModel": [
    "Model",
    "Graphics",
  ],
  "DrawModelEx": [
    "Model",
    "Graphics",
  ],
  "DrawModelWires": [
    "Model",
    "Graphics",
  ],
  "DrawModelWiresEx": [
    "Model",
    "Graphics",
  ],
  "DrawBoundingBox": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "DrawBillboard": [
    "Model",
    "Graphics",
  ],
  "DrawBillboardRec": [
    "Model",
    "Graphics",
  ],
  "DrawBillboardPro": [
    "Model",
    "Graphics",
  ],
  "UploadMesh": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "UpdateMeshBuffer": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "UnloadMesh": [
    "Model",
    "Mesh",
    "Graphics",
    "Assets",
  ],
  "DrawMesh": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "DrawMeshInstanced": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GetMeshBoundingBox": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "Mesh",
    "ModelCollision",
    "Graphics",
  ],
  "GenMeshTangents": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "ExportMesh": [
    "Model",
    "Mesh",
    "Graphics",
    "Assets",
  ],
  "ExportMeshAsCode": [
    "Model",
    "Mesh",
    "Graphics",
    "Assets",
  ],
  "GenMeshPoly": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshPlane": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshCube": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshSphere": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshHemiSphere": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshCylinder": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshCone": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshTorus": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshKnot": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshHeightmap": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "GenMeshCubicmap": [
    "Model",
    "Mesh",
    "Graphics",
  ],
  "LoadMaterials": [
    "Model",
    "Material",
    "Graphics",
    "Assets",
  ],
  "LoadMaterialDefault": [
    "Model",
    "Material",
    "Graphics",
    "Assets",
  ],
  "IsMaterialValid": [
    "Model",
    "Material",
    "Graphics",
    "Assets",
  ],
  "UnloadMaterial": [
    "Model",
    "Material",
    "Graphics",
    "Assets",
  ],
  "SetMaterialTexture": [
    "Model",
    "Material",
    "Graphics",
  ],
  "SetModelMeshMaterial": [
    "Model",
    "Mesh",
    "Material",
    "Graphics",
  ],
  "LoadModelAnimations": [
    "Model",
    "Animation",
    "Graphics",
    "Assets",
  ],
  "UpdateModelAnimation": [
    "Model",
    "Animation",
    "Graphics",
  ],
  "UpdateModelAnimationEx": [
    "Model",
    "Animation",
    "Graphics",
  ],
  "UnloadModelAnimations": [
    "Model",
    "Animation",
    "Graphics",
    "Assets",
  ],
  "IsModelAnimationValid": [
    "Model",
    "Animation",
    "Graphics",
    "Assets",
  ],
  "CheckCollisionSpheres": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "CheckCollisionBoxes": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "CheckCollisionBoxSphere": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "GetRayCollisionSphere": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "GetRayCollisionBox": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "GetRayCollisionMesh": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "Mesh",
    "ModelCollision",
    "Graphics",
  ],
  "GetRayCollisionTriangle": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "GetRayCollisionQuad": [
    "Collision3D",
    "Collision",
    "Shapes",
    "Model",
    "ModelCollision",
    "Graphics",
  ],
  "InitAudioDevice": [
    "Audio",
    "AudioDevice",
  ],
  "CloseAudioDevice": [
    "Audio",
    "AudioDevice",
  ],
  "IsAudioDeviceReady": [
    "Audio",
    "AudioDevice",
    "Assets",
  ],
  "SetMasterVolume": [
    "Audio",
    "AudioDevice",
  ],
  "GetMasterVolume": [
    "Audio",
    "AudioDevice",
  ],
  "LoadWave": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "LoadWaveFromMemory": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "IsWaveValid": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "LoadSound": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "LoadSoundFromWave": [
    "Audio",
    "Wave",
    "Sound",
    "Assets",
  ],
  "LoadSoundAlias": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "IsSoundValid": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "UpdateSound": [
    "Audio",
    "Sound",
  ],
  "UnloadWave": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "UnloadSound": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "UnloadSoundAlias": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "ExportWave": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "ExportWaveAsCode": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "PlaySound": [
    "Audio",
    "Sound",
  ],
  "StopSound": [
    "Audio",
    "Sound",
  ],
  "PauseSound": [
    "Audio",
    "Sound",
  ],
  "ResumeSound": [
    "Audio",
    "Sound",
  ],
  "IsSoundPlaying": [
    "Audio",
    "Sound",
    "Assets",
  ],
  "SetSoundVolume": [
    "Audio",
    "Sound",
  ],
  "SetSoundPitch": [
    "Audio",
    "Sound",
  ],
  "SetSoundPan": [
    "Audio",
    "Sound",
  ],
  "WaveCopy": [
    "Audio",
    "Wave",
  ],
  "WaveCrop": [
    "Audio",
    "Wave",
  ],
  "WaveFormat": [
    "Audio",
    "Wave",
  ],
  "LoadWaveSamples": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "UnloadWaveSamples": [
    "Audio",
    "Wave",
    "Assets",
  ],
  "LoadMusicStream": [
    "Audio",
    "Music",
    "Assets",
  ],
  "LoadMusicStreamFromMemory": [
    "Audio",
    "Music",
    "Assets",
  ],
  "IsMusicValid": [
    "Audio",
    "Music",
    "Assets",
  ],
  "UnloadMusicStream": [
    "Audio",
    "Music",
    "Assets",
  ],
  "PlayMusicStream": [
    "Audio",
    "Music",
  ],
  "IsMusicStreamPlaying": [
    "Audio",
    "Music",
    "Assets",
  ],
  "UpdateMusicStream": [
    "Audio",
    "Music",
  ],
  "StopMusicStream": [
    "Audio",
    "Music",
  ],
  "PauseMusicStream": [
    "Audio",
    "Music",
  ],
  "ResumeMusicStream": [
    "Audio",
    "Music",
  ],
  "SeekMusicStream": [
    "Audio",
    "Music",
  ],
  "SetMusicVolume": [
    "Audio",
    "Music",
  ],
  "SetMusicPitch": [
    "Audio",
    "Music",
  ],
  "SetMusicPan": [
    "Audio",
    "Music",
  ],
  "GetMusicTimeLength": [
    "Audio",
    "Music",
  ],
  "GetMusicTimePlayed": [
    "Audio",
    "Music",
  ],
  "LoadAudioStream": [
    "Audio",
    "AudioStream",
    "Assets",
  ],
  "IsAudioStreamValid": [
    "Audio",
    "AudioStream",
    "Assets",
  ],
  "UnloadAudioStream": [
    "Audio",
    "AudioStream",
    "Assets",
  ],
  "UpdateAudioStream": [
    "Audio",
    "AudioStream",
  ],
  "IsAudioStreamProcessed": [
    "Audio",
    "AudioStream",
    "Assets",
  ],
  "PlayAudioStream": [
    "Audio",
    "AudioStream",
  ],
  "PauseAudioStream": [
    "Audio",
    "AudioStream",
  ],
  "ResumeAudioStream": [
    "Audio",
    "AudioStream",
  ],
  "IsAudioStreamPlaying": [
    "Audio",
    "AudioStream",
    "Assets",
  ],
  "StopAudioStream": [
    "Audio",
    "AudioStream",
  ],
  "SetAudioStreamVolume": [
    "Audio",
    "AudioStream",
  ],
  "SetAudioStreamPitch": [
    "Audio",
    "AudioStream",
  ],
  "SetAudioStreamPan": [
    "Audio",
    "AudioStream",
  ],
  "SetAudioStreamBufferSizeDefault": [
    "Audio",
    "AudioStream",
  ],
  "SetAudioStreamCallback": [
    "Audio",
    "AudioStream",
  ],
  "AttachAudioStreamProcessor": [
    "Audio",
    "AudioStream",
  ],
  "DetachAudioStreamProcessor": [
    "Audio",
    "AudioStream",
  ],
  "AttachAudioMixedProcessor": [
    "Audio",
    "AudioStream",
  ],
  "DetachAudioMixedProcessor": [
    "Audio",
    "AudioStream",
  ],
  "Clamp": [
    "Math",
    "ScalarMath",
  ],
  "Lerp": [
    "Math",
    "ScalarMath",
  ],
  "Normalize": [
    "Math",
    "ScalarMath",
  ],
  "Remap": [
    "Math",
    "ScalarMath",
  ],
  "Wrap": [
    "Math",
    "ScalarMath",
  ],
  "FloatEquals": [
    "Math",
    "ScalarMath",
  ],
  "Vector2Zero": [
    "Math",
    "Vector2",
  ],
  "Vector2One": [
    "Math",
    "Vector2",
  ],
  "Vector2Add": [
    "Math",
    "Vector2",
  ],
  "Vector2AddValue": [
    "Math",
    "Vector2",
  ],
  "Vector2Subtract": [
    "Math",
    "Vector2",
  ],
  "Vector2SubtractValue": [
    "Math",
    "Vector2",
  ],
  "Vector2Length": [
    "Math",
    "Vector2",
  ],
  "Vector2LengthSqr": [
    "Math",
    "Vector2",
  ],
  "Vector2DotProduct": [
    "Math",
    "Vector2",
  ],
  "Vector2CrossProduct": [
    "Math",
    "Vector2",
  ],
  "Vector2Distance": [
    "Math",
    "Vector2",
  ],
  "Vector2DistanceSqr": [
    "Math",
    "Vector2",
  ],
  "Vector2Angle": [
    "Math",
    "Vector2",
  ],
  "Vector2LineAngle": [
    "Math",
    "Vector2",
  ],
  "Vector2Scale": [
    "Math",
    "Vector2",
  ],
  "Vector2Multiply": [
    "Math",
    "Vector2",
  ],
  "Vector2Negate": [
    "Math",
    "Vector2",
  ],
  "Vector2Divide": [
    "Math",
    "Vector2",
  ],
  "Vector2Normalize": [
    "Math",
    "Vector2",
  ],
  "Vector2Transform": [
    "Math",
    "Vector2",
  ],
  "Vector2Lerp": [
    "Math",
    "Vector2",
  ],
  "Vector2Reflect": [
    "Math",
    "Vector2",
  ],
  "Vector2Min": [
    "Math",
    "Vector2",
  ],
  "Vector2Max": [
    "Math",
    "Vector2",
  ],
  "Vector2Rotate": [
    "Math",
    "Vector2",
  ],
  "Vector2MoveTowards": [
    "Math",
    "Vector2",
  ],
  "Vector2Invert": [
    "Math",
    "Vector2",
  ],
  "Vector2Clamp": [
    "Math",
    "Vector2",
  ],
  "Vector2ClampValue": [
    "Math",
    "Vector2",
  ],
  "Vector2Equals": [
    "Math",
    "Vector2",
  ],
  "Vector2Refract": [
    "Math",
    "Vector2",
  ],
  "Vector3Zero": [
    "Math",
    "Vector3",
  ],
  "Vector3One": [
    "Math",
    "Vector3",
  ],
  "Vector3Add": [
    "Math",
    "Vector3",
  ],
  "Vector3AddValue": [
    "Math",
    "Vector3",
  ],
  "Vector3Subtract": [
    "Math",
    "Vector3",
  ],
  "Vector3SubtractValue": [
    "Math",
    "Vector3",
  ],
  "Vector3Scale": [
    "Math",
    "Vector3",
  ],
  "Vector3Multiply": [
    "Math",
    "Vector3",
  ],
  "Vector3CrossProduct": [
    "Math",
    "Vector3",
  ],
  "Vector3Perpendicular": [
    "Math",
    "Vector3",
  ],
  "Vector3Length": [
    "Math",
    "Vector3",
  ],
  "Vector3LengthSqr": [
    "Math",
    "Vector3",
  ],
  "Vector3DotProduct": [
    "Math",
    "Vector3",
  ],
  "Vector3Distance": [
    "Math",
    "Vector3",
  ],
  "Vector3DistanceSqr": [
    "Math",
    "Vector3",
  ],
  "Vector3Angle": [
    "Math",
    "Vector3",
  ],
  "Vector3Negate": [
    "Math",
    "Vector3",
  ],
  "Vector3Divide": [
    "Math",
    "Vector3",
  ],
  "Vector3Normalize": [
    "Math",
    "Vector3",
  ],
  "Vector3Project": [
    "Math",
    "Vector3",
  ],
  "Vector3Reject": [
    "Math",
    "Vector3",
  ],
  "Vector3OrthoNormalize": [
    "Math",
    "Vector3",
  ],
  "Vector3Transform": [
    "Math",
    "Vector3",
  ],
  "Vector3RotateByQuaternion": [
    "Math",
    "Vector3",
  ],
  "Vector3RotateByAxisAngle": [
    "Math",
    "Vector3",
  ],
  "Vector3MoveTowards": [
    "Math",
    "Vector3",
  ],
  "Vector3Lerp": [
    "Math",
    "Vector3",
  ],
  "Vector3CubicHermite": [
    "Math",
    "Vector3",
  ],
  "Vector3Reflect": [
    "Math",
    "Vector3",
  ],
  "Vector3Min": [
    "Math",
    "Vector3",
  ],
  "Vector3Max": [
    "Math",
    "Vector3",
  ],
  "Vector3Barycenter": [
    "Math",
    "Vector3",
  ],
  "Vector3Unproject": [
    "Math",
    "Vector3",
  ],
  "Vector3ToFloatV": [
    "Math",
    "Vector3",
  ],
  "Vector3Invert": [
    "Math",
    "Vector3",
  ],
  "Vector3Clamp": [
    "Math",
    "Vector3",
  ],
  "Vector3ClampValue": [
    "Math",
    "Vector3",
  ],
  "Vector3Equals": [
    "Math",
    "Vector3",
  ],
  "Vector3Refract": [
    "Math",
    "Vector3",
  ],
  "Vector4Zero": [
    "Math",
    "Vector4",
  ],
  "Vector4One": [
    "Math",
    "Vector4",
  ],
  "Vector4Add": [
    "Math",
    "Vector4",
  ],
  "Vector4AddValue": [
    "Math",
    "Vector4",
  ],
  "Vector4Subtract": [
    "Math",
    "Vector4",
  ],
  "Vector4SubtractValue": [
    "Math",
    "Vector4",
  ],
  "Vector4Length": [
    "Math",
    "Vector4",
  ],
  "Vector4LengthSqr": [
    "Math",
    "Vector4",
  ],
  "Vector4DotProduct": [
    "Math",
    "Vector4",
  ],
  "Vector4Distance": [
    "Math",
    "Vector4",
  ],
  "Vector4DistanceSqr": [
    "Math",
    "Vector4",
  ],
  "Vector4Scale": [
    "Math",
    "Vector4",
  ],
  "Vector4Multiply": [
    "Math",
    "Vector4",
  ],
  "Vector4Negate": [
    "Math",
    "Vector4",
  ],
  "Vector4Divide": [
    "Math",
    "Vector4",
  ],
  "Vector4Normalize": [
    "Math",
    "Vector4",
  ],
  "Vector4Min": [
    "Math",
    "Vector4",
  ],
  "Vector4Max": [
    "Math",
    "Vector4",
  ],
  "Vector4Lerp": [
    "Math",
    "Vector4",
  ],
  "Vector4MoveTowards": [
    "Math",
    "Vector4",
  ],
  "Vector4Invert": [
    "Math",
    "Vector4",
  ],
  "Vector4Equals": [
    "Math",
    "Vector4",
  ],
  "MatrixDeterminant": [
    "Math",
    "Matrix",
  ],
  "MatrixTrace": [
    "Math",
    "Matrix",
  ],
  "MatrixTranspose": [
    "Math",
    "Matrix",
  ],
  "MatrixInvert": [
    "Math",
    "Matrix",
  ],
  "MatrixIdentity": [
    "Math",
    "Matrix",
  ],
  "MatrixAdd": [
    "Math",
    "Matrix",
  ],
  "MatrixSubtract": [
    "Math",
    "Matrix",
  ],
  "MatrixMultiply": [
    "Math",
    "Matrix",
  ],
  "MatrixMultiplyValue": [
    "Math",
    "Matrix",
  ],
  "MatrixTranslate": [
    "Math",
    "Matrix",
  ],
  "MatrixRotate": [
    "Math",
    "Matrix",
  ],
  "MatrixRotateX": [
    "Math",
    "Matrix",
  ],
  "MatrixRotateY": [
    "Math",
    "Matrix",
  ],
  "MatrixRotateZ": [
    "Math",
    "Matrix",
  ],
  "MatrixRotateXYZ": [
    "Math",
    "Matrix",
  ],
  "MatrixRotateZYX": [
    "Math",
    "Matrix",
  ],
  "MatrixScale": [
    "Math",
    "Matrix",
  ],
  "MatrixFrustum": [
    "Math",
    "Matrix",
  ],
  "MatrixPerspective": [
    "Math",
    "Matrix",
  ],
  "MatrixOrtho": [
    "Math",
    "Matrix",
  ],
  "MatrixLookAt": [
    "Math",
    "Matrix",
  ],
  "MatrixToFloatV": [
    "Math",
    "Matrix",
  ],
  "QuaternionAdd": [
    "Math",
    "Quaternion",
  ],
  "QuaternionAddValue": [
    "Math",
    "Quaternion",
  ],
  "QuaternionSubtract": [
    "Math",
    "Quaternion",
  ],
  "QuaternionSubtractValue": [
    "Math",
    "Quaternion",
  ],
  "QuaternionIdentity": [
    "Math",
    "Quaternion",
  ],
  "QuaternionLength": [
    "Math",
    "Quaternion",
  ],
  "QuaternionNormalize": [
    "Math",
    "Quaternion",
  ],
  "QuaternionInvert": [
    "Math",
    "Quaternion",
  ],
  "QuaternionMultiply": [
    "Math",
    "Quaternion",
  ],
  "QuaternionScale": [
    "Math",
    "Quaternion",
  ],
  "QuaternionDivide": [
    "Math",
    "Quaternion",
  ],
  "QuaternionLerp": [
    "Math",
    "Quaternion",
  ],
  "QuaternionNlerp": [
    "Math",
    "Quaternion",
  ],
  "QuaternionSlerp": [
    "Math",
    "Quaternion",
  ],
  "QuaternionCubicHermiteSpline": [
    "Math",
    "Quaternion",
  ],
  "QuaternionFromVector3ToVector3": [
    "Math",
    "Quaternion",
  ],
  "QuaternionFromMatrix": [
    "Math",
    "Quaternion",
  ],
  "QuaternionToMatrix": [
    "Math",
    "Quaternion",
  ],
  "QuaternionFromAxisAngle": [
    "Math",
    "Quaternion",
  ],
  "QuaternionToAxisAngle": [
    "Math",
    "Quaternion",
  ],
  "QuaternionFromEuler": [
    "Math",
    "Quaternion",
  ],
  "QuaternionToEuler": [
    "Math",
    "Quaternion",
  ],
  "QuaternionTransform": [
    "Math",
    "Quaternion",
  ],
  "QuaternionEquals": [
    "Math",
    "Quaternion",
  ],
  "MatrixCompose": [
    "Math",
    "Matrix",
  ],
  "MatrixDecompose": [
    "Math",
    "Matrix",
  ],
  "GetCameraForward": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "GetCameraUp": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "GetCameraRight": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraMoveForward": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraMoveUp": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraMoveRight": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraMoveToTarget": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraYaw": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraPitch": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "CameraRoll": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "GetCameraViewMatrix": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "GetCameraProjectionMatrix": [
    "Camera3D",
    "CameraControls",
    "Camera",
    "Graphics",
  ],
  "rlMatrixMode": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlPushMatrix": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlPopMatrix": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlLoadIdentity": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlTranslatef": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlRotatef": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlScalef": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlMultMatrixf": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlFrustum": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlOrtho": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlViewport": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlSetClipPlanes": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlGetCullDistanceNear": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlGetCullDistanceFar": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlBegin": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlEnd": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlVertex2i": [
    "Rlgl",
    "ImmediateMode",
    "VertexBuffer",
    "Graphics",
  ],
  "rlVertex2f": [
    "Rlgl",
    "ImmediateMode",
    "VertexBuffer",
    "Graphics",
  ],
  "rlVertex3f": [
    "Rlgl",
    "ImmediateMode",
    "VertexBuffer",
    "Graphics",
  ],
  "rlTexCoord2f": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlNormal3f": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlColor4ub": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlColor3f": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlColor4f": [
    "Rlgl",
    "ImmediateMode",
    "Graphics",
  ],
  "rlEnableVertexArray": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDisableVertexArray": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlEnableVertexBuffer": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDisableVertexBuffer": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlEnableVertexBufferElement": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDisableVertexBufferElement": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlEnableVertexAttribute": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDisableVertexAttribute": [
    "Rlgl",
    "RenderState",
    "VertexBuffer",
    "Graphics",
  ],
  "rlEnableStatePointer": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableStatePointer": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlActiveTextureSlot": [
    "Rlgl",
    "RenderState",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlEnableTexture": [
    "Rlgl",
    "RenderState",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlDisableTexture": [
    "Rlgl",
    "RenderState",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlEnableTextureCubemap": [
    "Rlgl",
    "RenderState",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlDisableTextureCubemap": [
    "Rlgl",
    "RenderState",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlTextureParameters": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlCubemapParameters": [
    "Rlgl",
    "Graphics",
  ],
  "rlEnableShader": [
    "Rlgl",
    "RenderState",
    "LowLevelShader",
    "Graphics",
  ],
  "rlDisableShader": [
    "Rlgl",
    "RenderState",
    "LowLevelShader",
    "Graphics",
  ],
  "rlEnableFramebuffer": [
    "Rlgl",
    "RenderState",
    "Framebuffer",
    "Graphics",
  ],
  "rlDisableFramebuffer": [
    "Rlgl",
    "RenderState",
    "Framebuffer",
    "Graphics",
  ],
  "rlGetActiveFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlActiveDrawBuffers": [
    "Rlgl",
    "RenderState",
    "Framebuffer",
    "Graphics",
  ],
  "rlBlitFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlBindFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlEnableColorBlend": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableColorBlend": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableDepthTest": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableDepthTest": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableDepthMask": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableDepthMask": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableBackfaceCulling": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableBackfaceCulling": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlColorMask": [
    "Rlgl",
    "ImmediateMode",
    "RenderState",
    "Graphics",
  ],
  "rlSetCullFace": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableScissorTest": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableScissorTest": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlScissor": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnablePointMode": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisablePointMode": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlSetPointSize": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlGetPointSize": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableWireMode": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableWireMode": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlSetLineWidth": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlGetLineWidth": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableSmoothLines": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableSmoothLines": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlEnableStereoRender": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlDisableStereoRender": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlIsStereoRenderEnabled": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlClearColor": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlClearScreenBuffers": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlCheckErrors": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlSetBlendMode": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlSetBlendFactors": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlSetBlendFactorsSeparate": [
    "Rlgl",
    "RenderState",
    "Graphics",
  ],
  "rlglInit": [
    "Rlgl",
    "Graphics",
  ],
  "rlglClose": [
    "Rlgl",
    "Graphics",
  ],
  "rlLoadExtensions": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetProcAddress": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetVersion": [
    "Rlgl",
    "Graphics",
  ],
  "rlSetFramebufferWidth": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlGetFramebufferWidth": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlSetFramebufferHeight": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlGetFramebufferHeight": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlGetTextureIdDefault": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlGetShaderIdDefault": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlGetShaderLocsDefault": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlLoadRenderBatch": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlUnloadRenderBatch": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlDrawRenderBatch": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlSetRenderBatchActive": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlDrawRenderBatchActive": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlCheckRenderBatchLimit": [
    "Rlgl",
    "RenderBatch",
    "Graphics",
  ],
  "rlSetTexture": [
    "Rlgl",
    "RenderBatch",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlLoadVertexArray": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlLoadVertexBuffer": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlLoadVertexBufferElement": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlUpdateVertexBuffer": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlUpdateVertexBufferElements": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlUnloadVertexArray": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlUnloadVertexBuffer": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlSetVertexAttribute": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlSetVertexAttributeDivisor": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlSetVertexAttributeDefault": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDrawVertexArray": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDrawVertexArrayElements": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDrawVertexArrayInstanced": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlDrawVertexArrayElementsInstanced": [
    "Rlgl",
    "VertexBuffer",
    "Graphics",
  ],
  "rlLoadTexture": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlLoadTextureDepth": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlLoadTextureCubemap": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlUpdateTexture": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlGetGlTextureFormats": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlGetPixelFormatName": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlUnloadTexture": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlGenTextureMipmaps": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlReadTexturePixels": [
    "Rlgl",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlReadScreenPixels": [
    "Rlgl",
    "Graphics",
  ],
  "rlLoadFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlFramebufferAttach": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlFramebufferComplete": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlUnloadFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlCopyFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlResizeFramebuffer": [
    "Rlgl",
    "Framebuffer",
    "Graphics",
  ],
  "rlLoadShader": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlLoadShaderProgram": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlLoadShaderProgramEx": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlLoadShaderProgramCompute": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlUnloadShader": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlUnloadShaderProgram": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlGetLocationUniform": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlGetLocationAttrib": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlSetUniform": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlSetUniformMatrix": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlSetUniformMatrices": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlSetUniformSampler": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlSetShader": [
    "Rlgl",
    "LowLevelShader",
    "Graphics",
  ],
  "rlComputeShaderDispatch": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlLoadShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlUnloadShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlUpdateShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlBindShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlReadShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlCopyShaderBuffer": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlGetShaderBufferSize": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelShader",
    "Graphics",
  ],
  "rlBindImageTexture": [
    "Rlgl",
    "ShaderBuffer",
    "LowLevelTexture",
    "Graphics",
  ],
  "rlGetMatrixModelview": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetMatrixProjection": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetMatrixTransform": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetMatrixProjectionStereo": [
    "Rlgl",
    "Graphics",
  ],
  "rlGetMatrixViewOffsetStereo": [
    "Rlgl",
    "Graphics",
  ],
  "rlSetMatrixProjection": [
    "Rlgl",
    "Graphics",
  ],
  "rlSetMatrixModelview": [
    "Rlgl",
    "Graphics",
  ],
  "rlSetMatrixProjectionStereo": [
    "Rlgl",
    "Graphics",
  ],
  "rlSetMatrixViewOffsetStereo": [
    "Rlgl",
    "Graphics",
  ],
  "rlLoadDrawCube": [
    "Rlgl",
    "Graphics",
  ],
  "rlLoadDrawQuad": [
    "Rlgl",
    "Graphics",
  ],
} as const;
