/** Streamed music loading, playback, seeking, state, and timing. */
export {
  GetMusicTimeLength,
  GetMusicTimePlayed,
  IsMusicStreamPlaying,
  IsMusicValid,
  LoadMusicStream,
  LoadMusicStreamFromMemory,
  Music,
  PauseMusicStream,
  PlayMusicStream,
  ResumeMusicStream,
  SeekMusicStream,
  SetMusicPan,
  SetMusicPitch,
  SetMusicVolume,
  StopMusicStream,
  UnloadMusicStream,
  UpdateMusicStream,
} from "../Raylib/raylib.ts";
