/**
 * Direct rcamera movement, rotation, and projection APIs.
 *
 * @module
 */
// This file is generated by generate_rlgl.ts
// deno-lint-ignore-file verbatim-module-syntax no-unused-vars

import { lib as DLL } from "../Bindings/bindings.ts";
import { Camera3D, Matrix, Vector3 } from "../Bindings/Structs/structs.ts";
export { Camera3D, Matrix, Vector3 } from "../Bindings/Structs/structs.ts";

const encoder = new TextEncoder();
const lib = DLL.symbols;
const cstr = (text: string) => encoder.encode(text + "\0");
const readCString = (ptr: Deno.PointerValue) =>
  ptr === null ? "" : Deno.UnsafePointerView.getCString(ptr);

/** Update camera position for selected mode */
export function UpdateCamera(camera: Camera3D | null, mode: number): void {
  lib.UpdateCamera(camera?.buffer ?? null, mode);
}

/** Update camera movement/rotation */
export function UpdateCameraPro(
  camera: Camera3D | null,
  movement: Vector3,
  rotation: Vector3,
  zoom: number,
): void {
  lib.UpdateCameraPro(
    camera?.buffer ?? null,
    movement.buffer,
    rotation.buffer,
    zoom,
  );
}

/** GetCameraForward from the raylib 6.0 API. */
export function GetCameraForward(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraForward(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraUp from the raylib 6.0 API. */
export function GetCameraUp(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraUp(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraRight from the raylib 6.0 API. */
export function GetCameraRight(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraRight(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** CameraMoveForward from the raylib 6.0 API. */
export function CameraMoveForward(
  camera: Camera3D | null,
  distance: number,
  moveInWorldPlane: boolean,
): void {
  lib.CameraMoveForward(
    camera?.buffer ?? null,
    distance,
    moveInWorldPlane ? 1 : 0,
  );
}

/** CameraMoveUp from the raylib 6.0 API. */
export function CameraMoveUp(camera: Camera3D | null, distance: number): void {
  lib.CameraMoveUp(camera?.buffer ?? null, distance);
}

/** CameraMoveRight from the raylib 6.0 API. */
export function CameraMoveRight(
  camera: Camera3D | null,
  distance: number,
  moveInWorldPlane: boolean,
): void {
  lib.CameraMoveRight(
    camera?.buffer ?? null,
    distance,
    moveInWorldPlane ? 1 : 0,
  );
}

/** CameraMoveToTarget from the raylib 6.0 API. */
export function CameraMoveToTarget(
  camera: Camera3D | null,
  delta: number,
): void {
  lib.CameraMoveToTarget(camera?.buffer ?? null, delta);
}

/** CameraYaw from the raylib 6.0 API. */
export function CameraYaw(
  camera: Camera3D | null,
  angle: number,
  rotateAroundTarget: boolean,
): void {
  lib.CameraYaw(camera?.buffer ?? null, angle, rotateAroundTarget ? 1 : 0);
}

/** CameraPitch from the raylib 6.0 API. */
export function CameraPitch(
  camera: Camera3D | null,
  angle: number,
  lockView: boolean,
  rotateAroundTarget: boolean,
  rotateUp: boolean,
): void {
  lib.CameraPitch(
    camera?.buffer ?? null,
    angle,
    lockView ? 1 : 0,
    rotateAroundTarget ? 1 : 0,
    rotateUp ? 1 : 0,
  );
}

/** CameraRoll from the raylib 6.0 API. */
export function CameraRoll(camera: Camera3D | null, angle: number): void {
  lib.CameraRoll(camera?.buffer ?? null, angle);
}

/** GetCameraViewMatrix from the raylib 6.0 API. */
export function GetCameraViewMatrix(camera: Camera3D | null): Matrix {
  return new Matrix(
    lib.GetCameraViewMatrix(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraProjectionMatrix from the raylib 6.0 API. */
export function GetCameraProjectionMatrix(
  camera: Camera3D | null,
  aspect: number,
): Matrix {
  return new Matrix(
    lib.GetCameraProjectionMatrix(camera?.buffer ?? null, aspect) as Uint8Array<
      ArrayBuffer
    >,
  );
}

export { CameraMode, CameraProjection } from "./raylib.ts";
export type { Camera } from "./raylib.ts";
