// This file is generated by generate_rlgl.ts
// deno-lint-ignore-file verbatim-module-syntax no-unused-vars

import { lib as DLL } from "./bindings.ts";
import {
  Camera3D,
  Matrix,
  rlDrawCall,
  rlRenderBatch,
  rlVertexBuffer,
  Vector3,
} from "./Structs/structs.ts";
export {
  Camera3D,
  Matrix,
  rlDrawCall,
  rlRenderBatch,
  rlVertexBuffer,
  Vector3,
} from "./Structs/structs.ts";

const encoder = new TextEncoder();
const lib = DLL.symbols;
const cstr = (text: string) => encoder.encode(text + "\0");
const readCString = (ptr: Deno.PointerValue) =>
  ptr === null ? "" : Deno.UnsafePointerView.getCString(ptr);

/** OpenGL version */
export enum rlGlVersion {
  /** RL_OPENGL_SOFTWARE member. */
  RL_OPENGL_SOFTWARE = 0,
  /** RL_OPENGL_11 member. */
  RL_OPENGL_11 = 1,
  /** RL_OPENGL_21 member. */
  RL_OPENGL_21 = 2,
  /** RL_OPENGL_33 member. */
  RL_OPENGL_33 = 3,
  /** RL_OPENGL_43 member. */
  RL_OPENGL_43 = 4,
  /** RL_OPENGL_ES_20 member. */
  RL_OPENGL_ES_20 = 5,
  /** RL_OPENGL_ES_30 member. */
  RL_OPENGL_ES_30 = 6,
}
/** RL_OPENGL_SOFTWARE exported by Deno Raylib. */
export const RL_OPENGL_SOFTWARE = rlGlVersion.RL_OPENGL_SOFTWARE;
/** RL_OPENGL_11 exported by Deno Raylib. */
export const RL_OPENGL_11 = rlGlVersion.RL_OPENGL_11;
/** RL_OPENGL_21 exported by Deno Raylib. */
export const RL_OPENGL_21 = rlGlVersion.RL_OPENGL_21;
/** RL_OPENGL_33 exported by Deno Raylib. */
export const RL_OPENGL_33 = rlGlVersion.RL_OPENGL_33;
/** RL_OPENGL_43 exported by Deno Raylib. */
export const RL_OPENGL_43 = rlGlVersion.RL_OPENGL_43;
/** RL_OPENGL_ES_20 exported by Deno Raylib. */
export const RL_OPENGL_ES_20 = rlGlVersion.RL_OPENGL_ES_20;
/** RL_OPENGL_ES_30 exported by Deno Raylib. */
export const RL_OPENGL_ES_30 = rlGlVersion.RL_OPENGL_ES_30;

/** Trace log level */
export enum rlTraceLogLevel {
  /** RL_LOG_ALL member. */
  RL_LOG_ALL = 0,
  /** RL_LOG_TRACE member. */
  RL_LOG_TRACE = 1,
  /** RL_LOG_DEBUG member. */
  RL_LOG_DEBUG = 2,
  /** RL_LOG_INFO member. */
  RL_LOG_INFO = 3,
  /** RL_LOG_WARNING member. */
  RL_LOG_WARNING = 4,
  /** RL_LOG_ERROR member. */
  RL_LOG_ERROR = 5,
  /** RL_LOG_FATAL member. */
  RL_LOG_FATAL = 6,
  /** RL_LOG_NONE member. */
  RL_LOG_NONE = 7,
}
/** RL_LOG_ALL exported by Deno Raylib. */
export const RL_LOG_ALL = rlTraceLogLevel.RL_LOG_ALL;
/** RL_LOG_TRACE exported by Deno Raylib. */
export const RL_LOG_TRACE = rlTraceLogLevel.RL_LOG_TRACE;
/** RL_LOG_DEBUG exported by Deno Raylib. */
export const RL_LOG_DEBUG = rlTraceLogLevel.RL_LOG_DEBUG;
/** RL_LOG_INFO exported by Deno Raylib. */
export const RL_LOG_INFO = rlTraceLogLevel.RL_LOG_INFO;
/** RL_LOG_WARNING exported by Deno Raylib. */
export const RL_LOG_WARNING = rlTraceLogLevel.RL_LOG_WARNING;
/** RL_LOG_ERROR exported by Deno Raylib. */
export const RL_LOG_ERROR = rlTraceLogLevel.RL_LOG_ERROR;
/** RL_LOG_FATAL exported by Deno Raylib. */
export const RL_LOG_FATAL = rlTraceLogLevel.RL_LOG_FATAL;
/** RL_LOG_NONE exported by Deno Raylib. */
export const RL_LOG_NONE = rlTraceLogLevel.RL_LOG_NONE;

/** Texture pixel formats */
export enum rlPixelFormat {
  /** RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE member. */
  RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1,
  /** RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA member. */
  RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA = 2,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5 = 3,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8 = 4,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 = 5,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 = 6,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = 7,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R32 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R32 = 8,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32 = 9,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 = 10,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R16 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R16 = 11,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16 = 12,
  /** RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 member. */
  RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 = 13,
  /** RL_PIXELFORMAT_COMPRESSED_DXT1_RGB member. */
  RL_PIXELFORMAT_COMPRESSED_DXT1_RGB = 14,
  /** RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA = 15,
  /** RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA = 16,
  /** RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA = 17,
  /** RL_PIXELFORMAT_COMPRESSED_ETC1_RGB member. */
  RL_PIXELFORMAT_COMPRESSED_ETC1_RGB = 18,
  /** RL_PIXELFORMAT_COMPRESSED_ETC2_RGB member. */
  RL_PIXELFORMAT_COMPRESSED_ETC2_RGB = 19,
  /** RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA = 20,
  /** RL_PIXELFORMAT_COMPRESSED_PVRT_RGB member. */
  RL_PIXELFORMAT_COMPRESSED_PVRT_RGB = 21,
  /** RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA = 22,
  /** RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA = 23,
  /** RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA member. */
  RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA = 24,
}
/** RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE;
/** RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA;
/** RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5;
/** RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8;
/** RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1;
/** RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4;
/** RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8;
/** RL_PIXELFORMAT_UNCOMPRESSED_R32 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R32 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R32;
/** RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32;
/** RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32;
/** RL_PIXELFORMAT_UNCOMPRESSED_R16 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R16 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R16;
/** RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16;
/** RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 exported by Deno Raylib. */
export const RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 =
  rlPixelFormat.RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16;
/** RL_PIXELFORMAT_COMPRESSED_DXT1_RGB exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_DXT1_RGB =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_DXT1_RGB;
/** RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_ETC1_RGB exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_ETC1_RGB =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_ETC1_RGB;
/** RL_PIXELFORMAT_COMPRESSED_ETC2_RGB exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_ETC2_RGB =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_ETC2_RGB;
/** RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_PVRT_RGB exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_PVRT_RGB =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_PVRT_RGB;
/** RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA;
/** RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA exported by Deno Raylib. */
export const RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA =
  rlPixelFormat.RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA;

/** Texture parameters: filter mode */
export enum rlTextureFilter {
  /** RL_TEXTURE_FILTER_POINT member. */
  RL_TEXTURE_FILTER_POINT = 0,
  /** RL_TEXTURE_FILTER_BILINEAR member. */
  RL_TEXTURE_FILTER_BILINEAR = 1,
  /** RL_TEXTURE_FILTER_TRILINEAR member. */
  RL_TEXTURE_FILTER_TRILINEAR = 2,
  /** RL_TEXTURE_FILTER_ANISOTROPIC_4X member. */
  RL_TEXTURE_FILTER_ANISOTROPIC_4X = 3,
  /** RL_TEXTURE_FILTER_ANISOTROPIC_8X member. */
  RL_TEXTURE_FILTER_ANISOTROPIC_8X = 4,
  /** RL_TEXTURE_FILTER_ANISOTROPIC_16X member. */
  RL_TEXTURE_FILTER_ANISOTROPIC_16X = 5,
}
/** RL_TEXTURE_FILTER_POINT exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_POINT = rlTextureFilter.RL_TEXTURE_FILTER_POINT;
/** RL_TEXTURE_FILTER_BILINEAR exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_BILINEAR =
  rlTextureFilter.RL_TEXTURE_FILTER_BILINEAR;
/** RL_TEXTURE_FILTER_TRILINEAR exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_TRILINEAR =
  rlTextureFilter.RL_TEXTURE_FILTER_TRILINEAR;
/** RL_TEXTURE_FILTER_ANISOTROPIC_4X exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_ANISOTROPIC_4X =
  rlTextureFilter.RL_TEXTURE_FILTER_ANISOTROPIC_4X;
/** RL_TEXTURE_FILTER_ANISOTROPIC_8X exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_ANISOTROPIC_8X =
  rlTextureFilter.RL_TEXTURE_FILTER_ANISOTROPIC_8X;
/** RL_TEXTURE_FILTER_ANISOTROPIC_16X exported by Deno Raylib. */
export const RL_TEXTURE_FILTER_ANISOTROPIC_16X =
  rlTextureFilter.RL_TEXTURE_FILTER_ANISOTROPIC_16X;

/** Color blending modes (pre-defined) */
export enum rlBlendMode {
  /** RL_BLEND_ALPHA member. */
  RL_BLEND_ALPHA = 0,
  /** RL_BLEND_ADDITIVE member. */
  RL_BLEND_ADDITIVE = 1,
  /** RL_BLEND_MULTIPLIED member. */
  RL_BLEND_MULTIPLIED = 2,
  /** RL_BLEND_ADD_COLORS member. */
  RL_BLEND_ADD_COLORS = 3,
  /** RL_BLEND_SUBTRACT_COLORS member. */
  RL_BLEND_SUBTRACT_COLORS = 4,
  /** RL_BLEND_ALPHA_PREMULTIPLY member. */
  RL_BLEND_ALPHA_PREMULTIPLY = 5,
  /** RL_BLEND_CUSTOM member. */
  RL_BLEND_CUSTOM = 6,
  /** RL_BLEND_CUSTOM_SEPARATE member. */
  RL_BLEND_CUSTOM_SEPARATE = 7,
}
/** RL_BLEND_ALPHA exported by Deno Raylib. */
export const RL_BLEND_ALPHA = rlBlendMode.RL_BLEND_ALPHA;
/** RL_BLEND_ADDITIVE exported by Deno Raylib. */
export const RL_BLEND_ADDITIVE = rlBlendMode.RL_BLEND_ADDITIVE;
/** RL_BLEND_MULTIPLIED exported by Deno Raylib. */
export const RL_BLEND_MULTIPLIED = rlBlendMode.RL_BLEND_MULTIPLIED;
/** RL_BLEND_ADD_COLORS exported by Deno Raylib. */
export const RL_BLEND_ADD_COLORS = rlBlendMode.RL_BLEND_ADD_COLORS;
/** RL_BLEND_SUBTRACT_COLORS exported by Deno Raylib. */
export const RL_BLEND_SUBTRACT_COLORS = rlBlendMode.RL_BLEND_SUBTRACT_COLORS;
/** RL_BLEND_ALPHA_PREMULTIPLY exported by Deno Raylib. */
export const RL_BLEND_ALPHA_PREMULTIPLY =
  rlBlendMode.RL_BLEND_ALPHA_PREMULTIPLY;
/** RL_BLEND_CUSTOM exported by Deno Raylib. */
export const RL_BLEND_CUSTOM = rlBlendMode.RL_BLEND_CUSTOM;
/** RL_BLEND_CUSTOM_SEPARATE exported by Deno Raylib. */
export const RL_BLEND_CUSTOM_SEPARATE = rlBlendMode.RL_BLEND_CUSTOM_SEPARATE;

/** Shader location point type */
export enum rlShaderLocationIndex {
  /** RL_SHADER_LOC_VERTEX_POSITION member. */
  RL_SHADER_LOC_VERTEX_POSITION = 0,
  /** RL_SHADER_LOC_VERTEX_TEXCOORD01 member. */
  RL_SHADER_LOC_VERTEX_TEXCOORD01 = 1,
  /** RL_SHADER_LOC_VERTEX_TEXCOORD02 member. */
  RL_SHADER_LOC_VERTEX_TEXCOORD02 = 2,
  /** RL_SHADER_LOC_VERTEX_NORMAL member. */
  RL_SHADER_LOC_VERTEX_NORMAL = 3,
  /** RL_SHADER_LOC_VERTEX_TANGENT member. */
  RL_SHADER_LOC_VERTEX_TANGENT = 4,
  /** RL_SHADER_LOC_VERTEX_COLOR member. */
  RL_SHADER_LOC_VERTEX_COLOR = 5,
  /** RL_SHADER_LOC_MATRIX_MVP member. */
  RL_SHADER_LOC_MATRIX_MVP = 6,
  /** RL_SHADER_LOC_MATRIX_VIEW member. */
  RL_SHADER_LOC_MATRIX_VIEW = 7,
  /** RL_SHADER_LOC_MATRIX_PROJECTION member. */
  RL_SHADER_LOC_MATRIX_PROJECTION = 8,
  /** RL_SHADER_LOC_MATRIX_MODEL member. */
  RL_SHADER_LOC_MATRIX_MODEL = 9,
  /** RL_SHADER_LOC_MATRIX_NORMAL member. */
  RL_SHADER_LOC_MATRIX_NORMAL = 10,
  /** RL_SHADER_LOC_VECTOR_VIEW member. */
  RL_SHADER_LOC_VECTOR_VIEW = 11,
  /** RL_SHADER_LOC_COLOR_DIFFUSE member. */
  RL_SHADER_LOC_COLOR_DIFFUSE = 12,
  /** RL_SHADER_LOC_COLOR_SPECULAR member. */
  RL_SHADER_LOC_COLOR_SPECULAR = 13,
  /** RL_SHADER_LOC_COLOR_AMBIENT member. */
  RL_SHADER_LOC_COLOR_AMBIENT = 14,
  /** RL_SHADER_LOC_MAP_ALBEDO member. */
  RL_SHADER_LOC_MAP_ALBEDO = 15,
  /** RL_SHADER_LOC_MAP_METALNESS member. */
  RL_SHADER_LOC_MAP_METALNESS = 16,
  /** RL_SHADER_LOC_MAP_NORMAL member. */
  RL_SHADER_LOC_MAP_NORMAL = 17,
  /** RL_SHADER_LOC_MAP_ROUGHNESS member. */
  RL_SHADER_LOC_MAP_ROUGHNESS = 18,
  /** RL_SHADER_LOC_MAP_OCCLUSION member. */
  RL_SHADER_LOC_MAP_OCCLUSION = 19,
  /** RL_SHADER_LOC_MAP_EMISSION member. */
  RL_SHADER_LOC_MAP_EMISSION = 20,
  /** RL_SHADER_LOC_MAP_HEIGHT member. */
  RL_SHADER_LOC_MAP_HEIGHT = 21,
  /** RL_SHADER_LOC_MAP_CUBEMAP member. */
  RL_SHADER_LOC_MAP_CUBEMAP = 22,
  /** RL_SHADER_LOC_MAP_IRRADIANCE member. */
  RL_SHADER_LOC_MAP_IRRADIANCE = 23,
  /** RL_SHADER_LOC_MAP_PREFILTER member. */
  RL_SHADER_LOC_MAP_PREFILTER = 24,
  /** RL_SHADER_LOC_MAP_BRDF member. */
  RL_SHADER_LOC_MAP_BRDF = 25,
}
/** RL_SHADER_LOC_VERTEX_POSITION exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_POSITION =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_POSITION;
/** RL_SHADER_LOC_VERTEX_TEXCOORD01 exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_TEXCOORD01 =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_TEXCOORD01;
/** RL_SHADER_LOC_VERTEX_TEXCOORD02 exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_TEXCOORD02 =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_TEXCOORD02;
/** RL_SHADER_LOC_VERTEX_NORMAL exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_NORMAL =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_NORMAL;
/** RL_SHADER_LOC_VERTEX_TANGENT exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_TANGENT =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_TANGENT;
/** RL_SHADER_LOC_VERTEX_COLOR exported by Deno Raylib. */
export const RL_SHADER_LOC_VERTEX_COLOR =
  rlShaderLocationIndex.RL_SHADER_LOC_VERTEX_COLOR;
/** RL_SHADER_LOC_MATRIX_MVP exported by Deno Raylib. */
export const RL_SHADER_LOC_MATRIX_MVP =
  rlShaderLocationIndex.RL_SHADER_LOC_MATRIX_MVP;
/** RL_SHADER_LOC_MATRIX_VIEW exported by Deno Raylib. */
export const RL_SHADER_LOC_MATRIX_VIEW =
  rlShaderLocationIndex.RL_SHADER_LOC_MATRIX_VIEW;
/** RL_SHADER_LOC_MATRIX_PROJECTION exported by Deno Raylib. */
export const RL_SHADER_LOC_MATRIX_PROJECTION =
  rlShaderLocationIndex.RL_SHADER_LOC_MATRIX_PROJECTION;
/** RL_SHADER_LOC_MATRIX_MODEL exported by Deno Raylib. */
export const RL_SHADER_LOC_MATRIX_MODEL =
  rlShaderLocationIndex.RL_SHADER_LOC_MATRIX_MODEL;
/** RL_SHADER_LOC_MATRIX_NORMAL exported by Deno Raylib. */
export const RL_SHADER_LOC_MATRIX_NORMAL =
  rlShaderLocationIndex.RL_SHADER_LOC_MATRIX_NORMAL;
/** RL_SHADER_LOC_VECTOR_VIEW exported by Deno Raylib. */
export const RL_SHADER_LOC_VECTOR_VIEW =
  rlShaderLocationIndex.RL_SHADER_LOC_VECTOR_VIEW;
/** RL_SHADER_LOC_COLOR_DIFFUSE exported by Deno Raylib. */
export const RL_SHADER_LOC_COLOR_DIFFUSE =
  rlShaderLocationIndex.RL_SHADER_LOC_COLOR_DIFFUSE;
/** RL_SHADER_LOC_COLOR_SPECULAR exported by Deno Raylib. */
export const RL_SHADER_LOC_COLOR_SPECULAR =
  rlShaderLocationIndex.RL_SHADER_LOC_COLOR_SPECULAR;
/** RL_SHADER_LOC_COLOR_AMBIENT exported by Deno Raylib. */
export const RL_SHADER_LOC_COLOR_AMBIENT =
  rlShaderLocationIndex.RL_SHADER_LOC_COLOR_AMBIENT;
/** RL_SHADER_LOC_MAP_ALBEDO exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_ALBEDO =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_ALBEDO;
/** RL_SHADER_LOC_MAP_METALNESS exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_METALNESS =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_METALNESS;
/** RL_SHADER_LOC_MAP_NORMAL exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_NORMAL =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_NORMAL;
/** RL_SHADER_LOC_MAP_ROUGHNESS exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_ROUGHNESS =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_ROUGHNESS;
/** RL_SHADER_LOC_MAP_OCCLUSION exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_OCCLUSION =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_OCCLUSION;
/** RL_SHADER_LOC_MAP_EMISSION exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_EMISSION =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_EMISSION;
/** RL_SHADER_LOC_MAP_HEIGHT exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_HEIGHT =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_HEIGHT;
/** RL_SHADER_LOC_MAP_CUBEMAP exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_CUBEMAP =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_CUBEMAP;
/** RL_SHADER_LOC_MAP_IRRADIANCE exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_IRRADIANCE =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_IRRADIANCE;
/** RL_SHADER_LOC_MAP_PREFILTER exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_PREFILTER =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_PREFILTER;
/** RL_SHADER_LOC_MAP_BRDF exported by Deno Raylib. */
export const RL_SHADER_LOC_MAP_BRDF =
  rlShaderLocationIndex.RL_SHADER_LOC_MAP_BRDF;

/** Shader uniform data type */
export enum rlShaderUniformDataType {
  /** RL_SHADER_UNIFORM_FLOAT member. */
  RL_SHADER_UNIFORM_FLOAT = 0,
  /** RL_SHADER_UNIFORM_VEC2 member. */
  RL_SHADER_UNIFORM_VEC2 = 1,
  /** RL_SHADER_UNIFORM_VEC3 member. */
  RL_SHADER_UNIFORM_VEC3 = 2,
  /** RL_SHADER_UNIFORM_VEC4 member. */
  RL_SHADER_UNIFORM_VEC4 = 3,
  /** RL_SHADER_UNIFORM_INT member. */
  RL_SHADER_UNIFORM_INT = 4,
  /** RL_SHADER_UNIFORM_IVEC2 member. */
  RL_SHADER_UNIFORM_IVEC2 = 5,
  /** RL_SHADER_UNIFORM_IVEC3 member. */
  RL_SHADER_UNIFORM_IVEC3 = 6,
  /** RL_SHADER_UNIFORM_IVEC4 member. */
  RL_SHADER_UNIFORM_IVEC4 = 7,
  /** RL_SHADER_UNIFORM_UINT member. */
  RL_SHADER_UNIFORM_UINT = 8,
  /** RL_SHADER_UNIFORM_UIVEC2 member. */
  RL_SHADER_UNIFORM_UIVEC2 = 9,
  /** RL_SHADER_UNIFORM_UIVEC3 member. */
  RL_SHADER_UNIFORM_UIVEC3 = 10,
  /** RL_SHADER_UNIFORM_UIVEC4 member. */
  RL_SHADER_UNIFORM_UIVEC4 = 11,
  /** RL_SHADER_UNIFORM_SAMPLER2D member. */
  RL_SHADER_UNIFORM_SAMPLER2D = 12,
}
/** RL_SHADER_UNIFORM_FLOAT exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_FLOAT =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_FLOAT;
/** RL_SHADER_UNIFORM_VEC2 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_VEC2 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_VEC2;
/** RL_SHADER_UNIFORM_VEC3 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_VEC3 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_VEC3;
/** RL_SHADER_UNIFORM_VEC4 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_VEC4 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_VEC4;
/** RL_SHADER_UNIFORM_INT exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_INT =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_INT;
/** RL_SHADER_UNIFORM_IVEC2 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_IVEC2 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_IVEC2;
/** RL_SHADER_UNIFORM_IVEC3 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_IVEC3 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_IVEC3;
/** RL_SHADER_UNIFORM_IVEC4 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_IVEC4 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_IVEC4;
/** RL_SHADER_UNIFORM_UINT exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_UINT =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_UINT;
/** RL_SHADER_UNIFORM_UIVEC2 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_UIVEC2 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_UIVEC2;
/** RL_SHADER_UNIFORM_UIVEC3 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_UIVEC3 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_UIVEC3;
/** RL_SHADER_UNIFORM_UIVEC4 exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_UIVEC4 =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_UIVEC4;
/** RL_SHADER_UNIFORM_SAMPLER2D exported by Deno Raylib. */
export const RL_SHADER_UNIFORM_SAMPLER2D =
  rlShaderUniformDataType.RL_SHADER_UNIFORM_SAMPLER2D;

/** Shader attribute data types */
export enum rlShaderAttributeDataType {
  /** RL_SHADER_ATTRIB_FLOAT member. */
  RL_SHADER_ATTRIB_FLOAT = 0,
  /** RL_SHADER_ATTRIB_VEC2 member. */
  RL_SHADER_ATTRIB_VEC2 = 1,
  /** RL_SHADER_ATTRIB_VEC3 member. */
  RL_SHADER_ATTRIB_VEC3 = 2,
  /** RL_SHADER_ATTRIB_VEC4 member. */
  RL_SHADER_ATTRIB_VEC4 = 3,
}
/** RL_SHADER_ATTRIB_FLOAT exported by Deno Raylib. */
export const RL_SHADER_ATTRIB_FLOAT =
  rlShaderAttributeDataType.RL_SHADER_ATTRIB_FLOAT;
/** RL_SHADER_ATTRIB_VEC2 exported by Deno Raylib. */
export const RL_SHADER_ATTRIB_VEC2 =
  rlShaderAttributeDataType.RL_SHADER_ATTRIB_VEC2;
/** RL_SHADER_ATTRIB_VEC3 exported by Deno Raylib. */
export const RL_SHADER_ATTRIB_VEC3 =
  rlShaderAttributeDataType.RL_SHADER_ATTRIB_VEC3;
/** RL_SHADER_ATTRIB_VEC4 exported by Deno Raylib. */
export const RL_SHADER_ATTRIB_VEC4 =
  rlShaderAttributeDataType.RL_SHADER_ATTRIB_VEC4;

/** Framebuffer attachment type */
export enum rlFramebufferAttachType {
  /** RL_ATTACHMENT_COLOR_CHANNEL0 member. */
  RL_ATTACHMENT_COLOR_CHANNEL0 = 0,
  /** RL_ATTACHMENT_COLOR_CHANNEL1 member. */
  RL_ATTACHMENT_COLOR_CHANNEL1 = 1,
  /** RL_ATTACHMENT_COLOR_CHANNEL2 member. */
  RL_ATTACHMENT_COLOR_CHANNEL2 = 2,
  /** RL_ATTACHMENT_COLOR_CHANNEL3 member. */
  RL_ATTACHMENT_COLOR_CHANNEL3 = 3,
  /** RL_ATTACHMENT_COLOR_CHANNEL4 member. */
  RL_ATTACHMENT_COLOR_CHANNEL4 = 4,
  /** RL_ATTACHMENT_COLOR_CHANNEL5 member. */
  RL_ATTACHMENT_COLOR_CHANNEL5 = 5,
  /** RL_ATTACHMENT_COLOR_CHANNEL6 member. */
  RL_ATTACHMENT_COLOR_CHANNEL6 = 6,
  /** RL_ATTACHMENT_COLOR_CHANNEL7 member. */
  RL_ATTACHMENT_COLOR_CHANNEL7 = 7,
  /** RL_ATTACHMENT_DEPTH member. */
  RL_ATTACHMENT_DEPTH = 100,
  /** RL_ATTACHMENT_STENCIL member. */
  RL_ATTACHMENT_STENCIL = 200,
}
/** RL_ATTACHMENT_COLOR_CHANNEL0 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL0 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL0;
/** RL_ATTACHMENT_COLOR_CHANNEL1 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL1 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL1;
/** RL_ATTACHMENT_COLOR_CHANNEL2 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL2 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL2;
/** RL_ATTACHMENT_COLOR_CHANNEL3 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL3 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL3;
/** RL_ATTACHMENT_COLOR_CHANNEL4 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL4 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL4;
/** RL_ATTACHMENT_COLOR_CHANNEL5 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL5 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL5;
/** RL_ATTACHMENT_COLOR_CHANNEL6 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL6 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL6;
/** RL_ATTACHMENT_COLOR_CHANNEL7 exported by Deno Raylib. */
export const RL_ATTACHMENT_COLOR_CHANNEL7 =
  rlFramebufferAttachType.RL_ATTACHMENT_COLOR_CHANNEL7;
/** RL_ATTACHMENT_DEPTH exported by Deno Raylib. */
export const RL_ATTACHMENT_DEPTH = rlFramebufferAttachType.RL_ATTACHMENT_DEPTH;
/** RL_ATTACHMENT_STENCIL exported by Deno Raylib. */
export const RL_ATTACHMENT_STENCIL =
  rlFramebufferAttachType.RL_ATTACHMENT_STENCIL;

/** Framebuffer texture attachment type */
export enum rlFramebufferAttachTextureType {
  /** RL_ATTACHMENT_CUBEMAP_POSITIVE_X member. */
  RL_ATTACHMENT_CUBEMAP_POSITIVE_X = 0,
  /** RL_ATTACHMENT_CUBEMAP_NEGATIVE_X member. */
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_X = 1,
  /** RL_ATTACHMENT_CUBEMAP_POSITIVE_Y member. */
  RL_ATTACHMENT_CUBEMAP_POSITIVE_Y = 2,
  /** RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y member. */
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y = 3,
  /** RL_ATTACHMENT_CUBEMAP_POSITIVE_Z member. */
  RL_ATTACHMENT_CUBEMAP_POSITIVE_Z = 4,
  /** RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z member. */
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z = 5,
  /** RL_ATTACHMENT_TEXTURE2D member. */
  RL_ATTACHMENT_TEXTURE2D = 100,
  /** RL_ATTACHMENT_RENDERBUFFER member. */
  RL_ATTACHMENT_RENDERBUFFER = 200,
}
/** RL_ATTACHMENT_CUBEMAP_POSITIVE_X exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_POSITIVE_X =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_POSITIVE_X;
/** RL_ATTACHMENT_CUBEMAP_NEGATIVE_X exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_NEGATIVE_X =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_NEGATIVE_X;
/** RL_ATTACHMENT_CUBEMAP_POSITIVE_Y exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_POSITIVE_Y =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_POSITIVE_Y;
/** RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y;
/** RL_ATTACHMENT_CUBEMAP_POSITIVE_Z exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_POSITIVE_Z =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_POSITIVE_Z;
/** RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z exported by Deno Raylib. */
export const RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z;
/** RL_ATTACHMENT_TEXTURE2D exported by Deno Raylib. */
export const RL_ATTACHMENT_TEXTURE2D =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_TEXTURE2D;
/** RL_ATTACHMENT_RENDERBUFFER exported by Deno Raylib. */
export const RL_ATTACHMENT_RENDERBUFFER =
  rlFramebufferAttachTextureType.RL_ATTACHMENT_RENDERBUFFER;

/** Face culling mode */
export enum rlCullMode {
  /** RL_CULL_FACE_FRONT member. */
  RL_CULL_FACE_FRONT = 0,
  /** RL_CULL_FACE_BACK member. */
  RL_CULL_FACE_BACK = 1,
}
/** RL_CULL_FACE_FRONT exported by Deno Raylib. */
export const RL_CULL_FACE_FRONT = rlCullMode.RL_CULL_FACE_FRONT;
/** RL_CULL_FACE_BACK exported by Deno Raylib. */
export const RL_CULL_FACE_BACK = rlCullMode.RL_CULL_FACE_BACK;

/** RL_DEFAULT_BATCH_BUFFER_ELEMENTS from the raylib 6.0 API. */
export const RL_DEFAULT_BATCH_BUFFER_ELEMENTS = 8192;
/** Default number of batch buffers (multi-buffering) */
export const RL_DEFAULT_BATCH_BUFFERS = 1;
/** Default number of batch draw calls (by state changes: mode, texture) */
export const RL_DEFAULT_BATCH_DRAWCALLS = 256;
/** Maximum number of textures units that can be activated on batch drawing (SetShaderValueTexture()) */
export const RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS = 4;
/** Maximum size of Matrix stack */
export const RL_MAX_MATRIX_STACK_SIZE = 32;
/** Maximum number of shader locations supported */
export const RL_MAX_SHADER_LOCATIONS = 32;
/** Default near cull distance */
export const RL_CULL_DISTANCE_NEAR = 0.05;
/** Default far cull distance */
export const RL_CULL_DISTANCE_FAR = 4000;
/** GL_TEXTURE_WRAP_S */
export const RL_TEXTURE_WRAP_S = 10242;
/** GL_TEXTURE_WRAP_T */
export const RL_TEXTURE_WRAP_T = 10243;
/** GL_TEXTURE_MAG_FILTER */
export const RL_TEXTURE_MAG_FILTER = 10240;
/** GL_TEXTURE_MIN_FILTER */
export const RL_TEXTURE_MIN_FILTER = 10241;
/** GL_NEAREST */
export const RL_TEXTURE_FILTER_NEAREST = 9728;
/** GL_LINEAR */
export const RL_TEXTURE_FILTER_LINEAR = 9729;
/** GL_NEAREST_MIPMAP_NEAREST */
export const RL_TEXTURE_FILTER_MIP_NEAREST = 9984;
/** GL_NEAREST_MIPMAP_LINEAR */
export const RL_TEXTURE_FILTER_NEAREST_MIP_LINEAR = 9986;
/** GL_LINEAR_MIPMAP_NEAREST */
export const RL_TEXTURE_FILTER_LINEAR_MIP_NEAREST = 9985;
/** GL_LINEAR_MIPMAP_LINEAR */
export const RL_TEXTURE_FILTER_MIP_LINEAR = 9987;
/** Anisotropic filter (custom identifier) */
export const RL_TEXTURE_FILTER_ANISOTROPIC = 12288;
/** Texture mipmap bias, percentage ratio (custom identifier) */
export const RL_TEXTURE_MIPMAP_BIAS_RATIO = 16384;
/** GL_REPEAT */
export const RL_TEXTURE_WRAP_REPEAT = 10497;
/** GL_CLAMP_TO_EDGE */
export const RL_TEXTURE_WRAP_CLAMP = 33071;
/** GL_MIRRORED_REPEAT */
export const RL_TEXTURE_WRAP_MIRROR_REPEAT = 33648;
/** GL_MIRROR_CLAMP_EXT */
export const RL_TEXTURE_WRAP_MIRROR_CLAMP = 34626;
/** GL_MODELVIEW */
export const RL_MODELVIEW = 5888;
/** GL_PROJECTION */
export const RL_PROJECTION = 5889;
/** GL_TEXTURE */
export const RL_TEXTURE = 5890;
/** GL_LINES */
export const RL_LINES = 1;
/** GL_TRIANGLES */
export const RL_TRIANGLES = 4;
/** GL_QUADS */
export const RL_QUADS = 7;
/** GL_UNSIGNED_BYTE */
export const RL_UNSIGNED_BYTE = 5121;
/** GL_FLOAT */
export const RL_FLOAT = 5126;
/** GL_STREAM_DRAW */
export const RL_STREAM_DRAW = 35040;
/** GL_STREAM_READ */
export const RL_STREAM_READ = 35041;
/** GL_STREAM_COPY */
export const RL_STREAM_COPY = 35042;
/** GL_STATIC_DRAW */
export const RL_STATIC_DRAW = 35044;
/** GL_STATIC_READ */
export const RL_STATIC_READ = 35045;
/** GL_STATIC_COPY */
export const RL_STATIC_COPY = 35046;
/** GL_DYNAMIC_DRAW */
export const RL_DYNAMIC_DRAW = 35048;
/** GL_DYNAMIC_READ */
export const RL_DYNAMIC_READ = 35049;
/** GL_DYNAMIC_COPY */
export const RL_DYNAMIC_COPY = 35050;
/** GL_FRAGMENT_SHADER */
export const RL_FRAGMENT_SHADER = 35632;
/** GL_VERTEX_SHADER */
export const RL_VERTEX_SHADER = 35633;
/** GL_COMPUTE_SHADER */
export const RL_COMPUTE_SHADER = 37305;
/** GL_ZERO */
export const RL_ZERO = 0;
/** GL_ONE */
export const RL_ONE = 1;
/** GL_SRC_COLOR */
export const RL_SRC_COLOR = 768;
/** GL_ONE_MINUS_SRC_COLOR */
export const RL_ONE_MINUS_SRC_COLOR = 769;
/** GL_SRC_ALPHA */
export const RL_SRC_ALPHA = 770;
/** GL_ONE_MINUS_SRC_ALPHA */
export const RL_ONE_MINUS_SRC_ALPHA = 771;
/** GL_DST_ALPHA */
export const RL_DST_ALPHA = 772;
/** GL_ONE_MINUS_DST_ALPHA */
export const RL_ONE_MINUS_DST_ALPHA = 773;
/** GL_DST_COLOR */
export const RL_DST_COLOR = 774;
/** GL_ONE_MINUS_DST_COLOR */
export const RL_ONE_MINUS_DST_COLOR = 775;
/** GL_SRC_ALPHA_SATURATE */
export const RL_SRC_ALPHA_SATURATE = 776;
/** GL_CONSTANT_COLOR */
export const RL_CONSTANT_COLOR = 32769;
/** GL_ONE_MINUS_CONSTANT_COLOR */
export const RL_ONE_MINUS_CONSTANT_COLOR = 32770;
/** GL_CONSTANT_ALPHA */
export const RL_CONSTANT_ALPHA = 32771;
/** GL_ONE_MINUS_CONSTANT_ALPHA */
export const RL_ONE_MINUS_CONSTANT_ALPHA = 32772;
/** GL_FUNC_ADD */
export const RL_FUNC_ADD = 32774;
/** GL_MIN */
export const RL_MIN = 32775;
/** GL_MAX */
export const RL_MAX = 32776;
/** GL_FUNC_SUBTRACT */
export const RL_FUNC_SUBTRACT = 32778;
/** GL_FUNC_REVERSE_SUBTRACT */
export const RL_FUNC_REVERSE_SUBTRACT = 32779;
/** GL_BLEND_EQUATION */
export const RL_BLEND_EQUATION = 32777;
/** GL_BLEND_EQUATION_RGB   // (Same as BLEND_EQUATION) */
export const RL_BLEND_EQUATION_RGB = 32777;
/** GL_BLEND_EQUATION_ALPHA */
export const RL_BLEND_EQUATION_ALPHA = 34877;
/** GL_BLEND_DST_RGB */
export const RL_BLEND_DST_RGB = 32968;
/** GL_BLEND_SRC_RGB */
export const RL_BLEND_SRC_RGB = 32969;
/** GL_BLEND_DST_ALPHA */
export const RL_BLEND_DST_ALPHA = 32970;
/** GL_BLEND_SRC_ALPHA */
export const RL_BLEND_SRC_ALPHA = 32971;
/** GL_BLEND_COLOR */
export const RL_BLEND_COLOR = 32773;
/** GL_READ_FRAMEBUFFER */
export const RL_READ_FRAMEBUFFER = 36008;
/** GL_DRAW_FRAMEBUFFER */
export const RL_DRAW_FRAMEBUFFER = 36009;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION = 0;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD = 1;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL = 2;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR = 3;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT = 4;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2 from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2 = 5;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_INDICES from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_INDICES = 6;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEINDICES from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEINDICES = 7;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEWEIGHTS from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEWEIGHTS = 8;
/** RL_DEFAULT_SHADER_ATTRIB_LOCATION_INSTANCETRANSFORM from the raylib 6.0 API. */
export const RL_DEFAULT_SHADER_ATTRIB_LOCATION_INSTANCETRANSFORM = 9;

/** GetCameraForward from the raylib 6.0 API. */
export function GetCameraForward(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraForward(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraUp from the raylib 6.0 API. */
export function GetCameraUp(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraUp(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraRight from the raylib 6.0 API. */
export function GetCameraRight(camera: Camera3D | null): Vector3 {
  return new Vector3(
    lib.GetCameraRight(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** CameraMoveForward from the raylib 6.0 API. */
export function CameraMoveForward(
  camera: Camera3D | null,
  distance: number,
  moveInWorldPlane: boolean,
): void {
  lib.CameraMoveForward(
    camera?.buffer ?? null,
    distance,
    moveInWorldPlane ? 1 : 0,
  );
}

/** CameraMoveUp from the raylib 6.0 API. */
export function CameraMoveUp(camera: Camera3D | null, distance: number): void {
  lib.CameraMoveUp(camera?.buffer ?? null, distance);
}

/** CameraMoveRight from the raylib 6.0 API. */
export function CameraMoveRight(
  camera: Camera3D | null,
  distance: number,
  moveInWorldPlane: boolean,
): void {
  lib.CameraMoveRight(
    camera?.buffer ?? null,
    distance,
    moveInWorldPlane ? 1 : 0,
  );
}

/** CameraMoveToTarget from the raylib 6.0 API. */
export function CameraMoveToTarget(
  camera: Camera3D | null,
  delta: number,
): void {
  lib.CameraMoveToTarget(camera?.buffer ?? null, delta);
}

/** CameraYaw from the raylib 6.0 API. */
export function CameraYaw(
  camera: Camera3D | null,
  angle: number,
  rotateAroundTarget: boolean,
): void {
  lib.CameraYaw(camera?.buffer ?? null, angle, rotateAroundTarget ? 1 : 0);
}

/** CameraPitch from the raylib 6.0 API. */
export function CameraPitch(
  camera: Camera3D | null,
  angle: number,
  lockView: boolean,
  rotateAroundTarget: boolean,
  rotateUp: boolean,
): void {
  lib.CameraPitch(
    camera?.buffer ?? null,
    angle,
    lockView ? 1 : 0,
    rotateAroundTarget ? 1 : 0,
    rotateUp ? 1 : 0,
  );
}

/** CameraRoll from the raylib 6.0 API. */
export function CameraRoll(camera: Camera3D | null, angle: number): void {
  lib.CameraRoll(camera?.buffer ?? null, angle);
}

/** GetCameraViewMatrix from the raylib 6.0 API. */
export function GetCameraViewMatrix(camera: Camera3D | null): Matrix {
  return new Matrix(
    lib.GetCameraViewMatrix(camera?.buffer ?? null) as Uint8Array<ArrayBuffer>,
  );
}

/** GetCameraProjectionMatrix from the raylib 6.0 API. */
export function GetCameraProjectionMatrix(
  camera: Camera3D | null,
  aspect: number,
): Matrix {
  return new Matrix(
    lib.GetCameraProjectionMatrix(camera?.buffer ?? null, aspect) as Uint8Array<
      ArrayBuffer
    >,
  );
}

/** Choose the current matrix to be transformed */
export function rlMatrixMode(mode: number): void {
  lib.rlMatrixMode(mode);
}

/** Push the current matrix to stack */
export function rlPushMatrix(): void {
  lib.rlPushMatrix();
}

/** Pop latest inserted matrix from stack */
export function rlPopMatrix(): void {
  lib.rlPopMatrix();
}

/** Reset current matrix to identity matrix */
export function rlLoadIdentity(): void {
  lib.rlLoadIdentity();
}

/** Multiply the current matrix by a translation matrix */
export function rlTranslatef(x: number, y: number, z: number): void {
  lib.rlTranslatef(x, y, z);
}

/** Multiply the current matrix by a rotation matrix */
export function rlRotatef(
  angle: number,
  x: number,
  y: number,
  z: number,
): void {
  lib.rlRotatef(angle, x, y, z);
}

/** Multiply the current matrix by a scaling matrix */
export function rlScalef(x: number, y: number, z: number): void {
  lib.rlScalef(x, y, z);
}

/** Multiply the current matrix by another matrix */
export function rlMultMatrixf(matf: Deno.PointerValue): void {
  lib.rlMultMatrixf(matf);
}

/** rlFrustum from the raylib 6.0 API. */
export function rlFrustum(
  left: number,
  right: number,
  bottom: number,
  top: number,
  znear: number,
  zfar: number,
): void {
  lib.rlFrustum(left, right, bottom, top, znear, zfar);
}

/** rlOrtho from the raylib 6.0 API. */
export function rlOrtho(
  left: number,
  right: number,
  bottom: number,
  top: number,
  znear: number,
  zfar: number,
): void {
  lib.rlOrtho(left, right, bottom, top, znear, zfar);
}

/** Set the viewport area */
export function rlViewport(
  x: number,
  y: number,
  width: number,
  height: number,
): void {
  lib.rlViewport(x, y, width, height);
}

/** Set clip planes distances */
export function rlSetClipPlanes(nearPlane: number, farPlane: number): void {
  lib.rlSetClipPlanes(nearPlane, farPlane);
}

/** Get cull plane distance near */
export function rlGetCullDistanceNear(): number {
  return lib.rlGetCullDistanceNear();
}

/** Get cull plane distance far */
export function rlGetCullDistanceFar(): number {
  return lib.rlGetCullDistanceFar();
}

/** Initialize drawing mode (how to organize vertex) */
export function rlBegin(mode: number): void {
  lib.rlBegin(mode);
}

/** Finish vertex providing */
export function rlEnd(): void {
  lib.rlEnd();
}

/** Define one vertex (position) - 2 int */
export function rlVertex2i(x: number, y: number): void {
  lib.rlVertex2i(x, y);
}

/** Define one vertex (position) - 2 float */
export function rlVertex2f(x: number, y: number): void {
  lib.rlVertex2f(x, y);
}

/** Define one vertex (position) - 3 float */
export function rlVertex3f(x: number, y: number, z: number): void {
  lib.rlVertex3f(x, y, z);
}

/** Define one vertex (texture coordinate) - 2 float */
export function rlTexCoord2f(x: number, y: number): void {
  lib.rlTexCoord2f(x, y);
}

/** Define one vertex (normal) - 3 float */
export function rlNormal3f(x: number, y: number, z: number): void {
  lib.rlNormal3f(x, y, z);
}

/** Define one vertex (color) - 4 byte */
export function rlColor4ub(r: number, g: number, b: number, a: number): void {
  lib.rlColor4ub(r, g, b, a);
}

/** Define one vertex (color) - 3 float */
export function rlColor3f(x: number, y: number, z: number): void {
  lib.rlColor3f(x, y, z);
}

/** Define one vertex (color) - 4 float */
export function rlColor4f(x: number, y: number, z: number, w: number): void {
  lib.rlColor4f(x, y, z, w);
}

/** Enable vertex array (VAO, if supported) */
export function rlEnableVertexArray(vaoId: number): boolean {
  return !!lib.rlEnableVertexArray(vaoId);
}

/** Disable vertex array (VAO, if supported) */
export function rlDisableVertexArray(): void {
  lib.rlDisableVertexArray();
}

/** Enable vertex buffer (VBO) */
export function rlEnableVertexBuffer(id: number): void {
  lib.rlEnableVertexBuffer(id);
}

/** Disable vertex buffer (VBO) */
export function rlDisableVertexBuffer(): void {
  lib.rlDisableVertexBuffer();
}

/** Enable vertex buffer element (VBO element) */
export function rlEnableVertexBufferElement(id: number): void {
  lib.rlEnableVertexBufferElement(id);
}

/** Disable vertex buffer element (VBO element) */
export function rlDisableVertexBufferElement(): void {
  lib.rlDisableVertexBufferElement();
}

/** Enable vertex attribute index */
export function rlEnableVertexAttribute(index: number): void {
  lib.rlEnableVertexAttribute(index);
}

/** Disable vertex attribute index */
export function rlDisableVertexAttribute(index: number): void {
  lib.rlDisableVertexAttribute(index);
}

/** Enable attribute state pointer */
export function rlEnableStatePointer(
  vertexAttribType: number,
  buffer: Deno.PointerValue,
): void {
  lib.rlEnableStatePointer(vertexAttribType, buffer);
}

/** Disable attribute state pointer */
export function rlDisableStatePointer(vertexAttribType: number): void {
  lib.rlDisableStatePointer(vertexAttribType);
}

/** Select and active a texture slot */
export function rlActiveTextureSlot(slot: number): void {
  lib.rlActiveTextureSlot(slot);
}

/** Enable texture */
export function rlEnableTexture(id: number): void {
  lib.rlEnableTexture(id);
}

/** Disable texture */
export function rlDisableTexture(): void {
  lib.rlDisableTexture();
}

/** Enable texture cubemap */
export function rlEnableTextureCubemap(id: number): void {
  lib.rlEnableTextureCubemap(id);
}

/** Disable texture cubemap */
export function rlDisableTextureCubemap(): void {
  lib.rlDisableTextureCubemap();
}

/** Set texture parameters (filter, wrap) */
export function rlTextureParameters(
  id: number,
  param: number,
  value: number,
): void {
  lib.rlTextureParameters(id, param, value);
}

/** Set cubemap parameters (filter, wrap) */
export function rlCubemapParameters(
  id: number,
  param: number,
  value: number,
): void {
  lib.rlCubemapParameters(id, param, value);
}

/** Enable shader program */
export function rlEnableShader(id: number): void {
  lib.rlEnableShader(id);
}

/** Disable shader program */
export function rlDisableShader(): void {
  lib.rlDisableShader();
}

/** Enable render texture (fbo) */
export function rlEnableFramebuffer(id: number): void {
  lib.rlEnableFramebuffer(id);
}

/** Disable render texture (fbo), return to default framebuffer */
export function rlDisableFramebuffer(): void {
  lib.rlDisableFramebuffer();
}

/** Get the currently active render texture (fbo), 0 for default framebuffer */
export function rlGetActiveFramebuffer(): number {
  return lib.rlGetActiveFramebuffer();
}

/** Activate multiple draw color buffers */
export function rlActiveDrawBuffers(count: number): void {
  lib.rlActiveDrawBuffers(count);
}

/** Blit active framebuffer to main framebuffer */
export function rlBlitFramebuffer(
  srcX: number,
  srcY: number,
  srcWidth: number,
  srcHeight: number,
  dstX: number,
  dstY: number,
  dstWidth: number,
  dstHeight: number,
  bufferMask: number,
): void {
  lib.rlBlitFramebuffer(
    srcX,
    srcY,
    srcWidth,
    srcHeight,
    dstX,
    dstY,
    dstWidth,
    dstHeight,
    bufferMask,
  );
}

/** Bind framebuffer (FBO) */
export function rlBindFramebuffer(target: number, framebuffer: number): void {
  lib.rlBindFramebuffer(target, framebuffer);
}

/** Enable color blending */
export function rlEnableColorBlend(): void {
  lib.rlEnableColorBlend();
}

/** Disable color blending */
export function rlDisableColorBlend(): void {
  lib.rlDisableColorBlend();
}

/** Enable depth test */
export function rlEnableDepthTest(): void {
  lib.rlEnableDepthTest();
}

/** Disable depth test */
export function rlDisableDepthTest(): void {
  lib.rlDisableDepthTest();
}

/** Enable depth write */
export function rlEnableDepthMask(): void {
  lib.rlEnableDepthMask();
}

/** Disable depth write */
export function rlDisableDepthMask(): void {
  lib.rlDisableDepthMask();
}

/** Enable backface culling */
export function rlEnableBackfaceCulling(): void {
  lib.rlEnableBackfaceCulling();
}

/** Disable backface culling */
export function rlDisableBackfaceCulling(): void {
  lib.rlDisableBackfaceCulling();
}

/** Color mask control */
export function rlColorMask(
  r: boolean,
  g: boolean,
  b: boolean,
  a: boolean,
): void {
  lib.rlColorMask(r ? 1 : 0, g ? 1 : 0, b ? 1 : 0, a ? 1 : 0);
}

/** Set face culling mode */
export function rlSetCullFace(mode: number): void {
  lib.rlSetCullFace(mode);
}

/** Enable scissor test */
export function rlEnableScissorTest(): void {
  lib.rlEnableScissorTest();
}

/** Disable scissor test */
export function rlDisableScissorTest(): void {
  lib.rlDisableScissorTest();
}

/** Scissor test */
export function rlScissor(
  x: number,
  y: number,
  width: number,
  height: number,
): void {
  lib.rlScissor(x, y, width, height);
}

/** Enable point mode */
export function rlEnablePointMode(): void {
  lib.rlEnablePointMode();
}

/** Disable point mode */
export function rlDisablePointMode(): void {
  lib.rlDisablePointMode();
}

/** Set the point drawing size */
export function rlSetPointSize(size: number): void {
  lib.rlSetPointSize(size);
}

/** Get the point drawing size */
export function rlGetPointSize(): number {
  return lib.rlGetPointSize();
}

/** Enable wire mode */
export function rlEnableWireMode(): void {
  lib.rlEnableWireMode();
}

/** Disable wire mode */
export function rlDisableWireMode(): void {
  lib.rlDisableWireMode();
}

/** Set the line drawing width */
export function rlSetLineWidth(width: number): void {
  lib.rlSetLineWidth(width);
}

/** Get the line drawing width */
export function rlGetLineWidth(): number {
  return lib.rlGetLineWidth();
}

/** Enable line aliasing */
export function rlEnableSmoothLines(): void {
  lib.rlEnableSmoothLines();
}

/** Disable line aliasing */
export function rlDisableSmoothLines(): void {
  lib.rlDisableSmoothLines();
}

/** Enable stereo rendering */
export function rlEnableStereoRender(): void {
  lib.rlEnableStereoRender();
}

/** Disable stereo rendering */
export function rlDisableStereoRender(): void {
  lib.rlDisableStereoRender();
}

/** Check if stereo render is enabled */
export function rlIsStereoRenderEnabled(): boolean {
  return !!lib.rlIsStereoRenderEnabled();
}

/** Clear color buffer with color */
export function rlClearColor(r: number, g: number, b: number, a: number): void {
  lib.rlClearColor(r, g, b, a);
}

/** Clear used screen buffers (color and depth) */
export function rlClearScreenBuffers(): void {
  lib.rlClearScreenBuffers();
}

/** Check and log OpenGL error codes */
export function rlCheckErrors(): void {
  lib.rlCheckErrors();
}

/** Set blending mode */
export function rlSetBlendMode(mode: number): void {
  lib.rlSetBlendMode(mode);
}

/** Set blending mode factor and equation (using OpenGL factors) */
export function rlSetBlendFactors(
  glSrcFactor: number,
  glDstFactor: number,
  glEquation: number,
): void {
  lib.rlSetBlendFactors(glSrcFactor, glDstFactor, glEquation);
}

/** Set blending mode factors and equations separately (using OpenGL factors) */
export function rlSetBlendFactorsSeparate(
  glSrcRGB: number,
  glDstRGB: number,
  glSrcAlpha: number,
  glDstAlpha: number,
  glEqRGB: number,
  glEqAlpha: number,
): void {
  lib.rlSetBlendFactorsSeparate(
    glSrcRGB,
    glDstRGB,
    glSrcAlpha,
    glDstAlpha,
    glEqRGB,
    glEqAlpha,
  );
}

/** Initialize rlgl (buffers, shaders, textures, states) */
export function rlglInit(width: number, height: number): void {
  lib.rlglInit(width, height);
}

/** De-initialize rlgl (buffers, shaders, textures) */
export function rlglClose(): void {
  lib.rlglClose();
}

/** Load OpenGL extensions (loader function required) */
export function rlLoadExtensions(loader: Deno.PointerValue): void {
  lib.rlLoadExtensions(loader);
}

/** Get OpenGL procedure address */
export function rlGetProcAddress(procName: string): Deno.PointerValue {
  return lib.rlGetProcAddress(cstr(procName as string));
}

/** Get current OpenGL version */
export function rlGetVersion(): number {
  return lib.rlGetVersion();
}

/** Set current framebuffer width */
export function rlSetFramebufferWidth(width: number): void {
  lib.rlSetFramebufferWidth(width);
}

/** Get default framebuffer width */
export function rlGetFramebufferWidth(): number {
  return lib.rlGetFramebufferWidth();
}

/** Set current framebuffer height */
export function rlSetFramebufferHeight(height: number): void {
  lib.rlSetFramebufferHeight(height);
}

/** Get default framebuffer height */
export function rlGetFramebufferHeight(): number {
  return lib.rlGetFramebufferHeight();
}

/** Get default texture id */
export function rlGetTextureIdDefault(): number {
  return lib.rlGetTextureIdDefault();
}

/** Get default shader id */
export function rlGetShaderIdDefault(): number {
  return lib.rlGetShaderIdDefault();
}

/** Get default shader locations */
export function rlGetShaderLocsDefault(): Deno.PointerValue {
  return lib.rlGetShaderLocsDefault();
}

/** Load a render batch system */
export function rlLoadRenderBatch(
  numBuffers: number,
  bufferElements: number,
): rlRenderBatch {
  return new rlRenderBatch(
    lib.rlLoadRenderBatch(numBuffers, bufferElements) as Uint8Array<
      ArrayBuffer
    >,
  );
}

/** Unload render batch system */
export function rlUnloadRenderBatch(batch: rlRenderBatch): void {
  lib.rlUnloadRenderBatch(batch.buffer);
}

/** Draw render batch data (Update->Draw->Reset) */
export function rlDrawRenderBatch(batch: rlRenderBatch | null): void {
  lib.rlDrawRenderBatch(batch?.buffer ?? null);
}

/** Set the active render batch for rlgl (NULL for default internal) */
export function rlSetRenderBatchActive(batch: rlRenderBatch | null): void {
  lib.rlSetRenderBatchActive(batch?.buffer ?? null);
}

/** Update and draw internal render batch */
export function rlDrawRenderBatchActive(): void {
  lib.rlDrawRenderBatchActive();
}

/** Check internal buffer overflow for a given number of vertex */
export function rlCheckRenderBatchLimit(vCount: number): boolean {
  return !!lib.rlCheckRenderBatchLimit(vCount);
}

/** Set current texture for render batch and check buffers limits */
export function rlSetTexture(id: number): void {
  lib.rlSetTexture(id);
}

/** Load vertex array (vao) if supported */
export function rlLoadVertexArray(): number {
  return lib.rlLoadVertexArray();
}

/** Load a vertex buffer object */
export function rlLoadVertexBuffer(
  buffer: Deno.PointerValue,
  size: number,
  dynamic: boolean,
): number {
  return lib.rlLoadVertexBuffer(buffer, size, dynamic ? 1 : 0);
}

/** Load vertex buffer elements object */
export function rlLoadVertexBufferElement(
  buffer: Deno.PointerValue,
  size: number,
  dynamic: boolean,
): number {
  return lib.rlLoadVertexBufferElement(buffer, size, dynamic ? 1 : 0);
}

/** Update vertex buffer object data on GPU buffer */
export function rlUpdateVertexBuffer(
  bufferId: number,
  data: Deno.PointerValue,
  dataSize: number,
  offset: number,
): void {
  lib.rlUpdateVertexBuffer(bufferId, data, dataSize, offset);
}

/** Update vertex buffer elements data on GPU buffer */
export function rlUpdateVertexBufferElements(
  id: number,
  data: Deno.PointerValue,
  dataSize: number,
  offset: number,
): void {
  lib.rlUpdateVertexBufferElements(id, data, dataSize, offset);
}

/** Unload vertex array (vao) */
export function rlUnloadVertexArray(vaoId: number): void {
  lib.rlUnloadVertexArray(vaoId);
}

/** Unload vertex buffer object */
export function rlUnloadVertexBuffer(vboId: number): void {
  lib.rlUnloadVertexBuffer(vboId);
}

/** Set vertex attribute data configuration */
export function rlSetVertexAttribute(
  index: number,
  compSize: number,
  type: number,
  normalized: boolean,
  stride: number,
  offset: number,
): void {
  lib.rlSetVertexAttribute(
    index,
    compSize,
    type,
    normalized ? 1 : 0,
    stride,
    offset,
  );
}

/** Set vertex attribute data divisor */
export function rlSetVertexAttributeDivisor(
  index: number,
  divisor: number,
): void {
  lib.rlSetVertexAttributeDivisor(index, divisor);
}

/** Set vertex attribute default value, when attribute to provided */
export function rlSetVertexAttributeDefault(
  locIndex: number,
  value: Deno.PointerValue,
  attribType: number,
  count: number,
): void {
  lib.rlSetVertexAttributeDefault(locIndex, value, attribType, count);
}

/** Draw vertex array (currently active vao) */
export function rlDrawVertexArray(offset: number, count: number): void {
  lib.rlDrawVertexArray(offset, count);
}

/** Draw vertex array elements */
export function rlDrawVertexArrayElements(
  offset: number,
  count: number,
  buffer: Deno.PointerValue,
): void {
  lib.rlDrawVertexArrayElements(offset, count, buffer);
}

/** Draw vertex array (currently active vao) with instancing */
export function rlDrawVertexArrayInstanced(
  offset: number,
  count: number,
  instances: number,
): void {
  lib.rlDrawVertexArrayInstanced(offset, count, instances);
}

/** Draw vertex array elements with instancing */
export function rlDrawVertexArrayElementsInstanced(
  offset: number,
  count: number,
  buffer: Deno.PointerValue,
  instances: number,
): void {
  lib.rlDrawVertexArrayElementsInstanced(offset, count, buffer, instances);
}

/** Load texture data */
export function rlLoadTexture(
  data: Deno.PointerValue,
  width: number,
  height: number,
  format: number,
  mipmapCount: number,
): number {
  return lib.rlLoadTexture(data, width, height, format, mipmapCount);
}

/** Load depth texture/renderbuffer (to be attached to fbo) */
export function rlLoadTextureDepth(
  width: number,
  height: number,
  useRenderBuffer: boolean,
): number {
  return lib.rlLoadTextureDepth(width, height, useRenderBuffer ? 1 : 0);
}

/** Load texture cubemap data */
export function rlLoadTextureCubemap(
  data: Deno.PointerValue,
  size: number,
  format: number,
  mipmapCount: number,
): number {
  return lib.rlLoadTextureCubemap(data, size, format, mipmapCount);
}

/** Update texture with new data on GPU */
export function rlUpdateTexture(
  id: number,
  offsetX: number,
  offsetY: number,
  width: number,
  height: number,
  format: number,
  data: Deno.PointerValue,
): void {
  lib.rlUpdateTexture(id, offsetX, offsetY, width, height, format, data);
}

/** Get OpenGL internal formats */
export function rlGetGlTextureFormats(
  format: number,
  glInternalFormat: Deno.PointerValue,
  glFormat: Deno.PointerValue,
  glType: Deno.PointerValue,
): void {
  lib.rlGetGlTextureFormats(format, glInternalFormat, glFormat, glType);
}

/** Get name string for pixel format */
export function rlGetPixelFormatName(format: number): string {
  return readCString(lib.rlGetPixelFormatName(format));
}

/** Unload texture from GPU memory */
export function rlUnloadTexture(id: number): void {
  lib.rlUnloadTexture(id);
}

/** Generate mipmap data for selected texture */
export function rlGenTextureMipmaps(
  id: number,
  width: number,
  height: number,
  format: number,
  mipmaps: Deno.PointerValue,
): void {
  lib.rlGenTextureMipmaps(id, width, height, format, mipmaps);
}

/** Read texture pixel data */
export function rlReadTexturePixels(
  id: number,
  width: number,
  height: number,
  format: number,
): Deno.PointerValue {
  return lib.rlReadTexturePixels(id, width, height, format);
}

/** Read screen pixel data (color buffer) */
export function rlReadScreenPixels(
  width: number,
  height: number,
): Deno.PointerValue {
  return lib.rlReadScreenPixels(width, height);
}

/** Load an empty framebuffer */
export function rlLoadFramebuffer(): number {
  return lib.rlLoadFramebuffer();
}

/** Attach texture/renderbuffer to a framebuffer */
export function rlFramebufferAttach(
  id: number,
  texId: number,
  attachType: number,
  texType: number,
  mipLevel: number,
): void {
  lib.rlFramebufferAttach(id, texId, attachType, texType, mipLevel);
}

/** Verify framebuffer is complete */
export function rlFramebufferComplete(id: number): boolean {
  return !!lib.rlFramebufferComplete(id);
}

/** Delete framebuffer from GPU */
export function rlUnloadFramebuffer(id: number): void {
  lib.rlUnloadFramebuffer(id);
}

/** Copy framebuffer pixel data to internal buffer */
export function rlCopyFramebuffer(
  x: number,
  y: number,
  width: number,
  height: number,
  format: number,
  pixels: Deno.PointerValue,
): void {
  lib.rlCopyFramebuffer(x, y, width, height, format, pixels);
}

/** Resize internal framebuffer */
export function rlResizeFramebuffer(width: number, height: number): void {
  lib.rlResizeFramebuffer(width, height);
}

/** Load (compile) shader and return shader id (type: RL_VERTEX_SHADER, RL_FRAGMENT_SHADER, RL_COMPUTE_SHADER) */
export function rlLoadShader(code: string, type: number): number {
  return lib.rlLoadShader(cstr(code as string), type);
}

/** Load shader from code strings */
export function rlLoadShaderProgram(vsCode: string, fsCode: string): number {
  return lib.rlLoadShaderProgram(
    cstr(vsCode as string),
    cstr(fsCode as string),
  );
}

/** Load shader program, using already loaded shader ids */
export function rlLoadShaderProgramEx(vsId: number, fsId: number): number {
  return lib.rlLoadShaderProgramEx(vsId, fsId);
}

/** Load compute shader program */
export function rlLoadShaderProgramCompute(csId: number): number {
  return lib.rlLoadShaderProgramCompute(csId);
}

/** Unload shader, loaded with rlLoadShader() */
export function rlUnloadShader(id: number): void {
  lib.rlUnloadShader(id);
}

/** Unload shader program */
export function rlUnloadShaderProgram(id: number): void {
  lib.rlUnloadShaderProgram(id);
}

/** Get shader location uniform, requires shader program id */
export function rlGetLocationUniform(id: number, uniformName: string): number {
  return lib.rlGetLocationUniform(id, cstr(uniformName as string));
}

/** Get shader location attribute, requires shader program id */
export function rlGetLocationAttrib(id: number, attribName: string): number {
  return lib.rlGetLocationAttrib(id, cstr(attribName as string));
}

/** Set shader value uniform */
export function rlSetUniform(
  locIndex: number,
  value: Deno.PointerValue,
  uniformType: number,
  count: number,
): void {
  lib.rlSetUniform(locIndex, value, uniformType, count);
}

/** Set shader value matrix */
export function rlSetUniformMatrix(locIndex: number, mat: Matrix): void {
  lib.rlSetUniformMatrix(locIndex, mat.buffer);
}

/** Set shader value matrices */
export function rlSetUniformMatrices(
  locIndex: number,
  mat: Matrix | null,
  count: number,
): void {
  lib.rlSetUniformMatrices(locIndex, mat?.buffer ?? null, count);
}

/** Set shader value sampler */
export function rlSetUniformSampler(locIndex: number, textureId: number): void {
  lib.rlSetUniformSampler(locIndex, textureId);
}

/** Set shader currently active (id and locations) */
export function rlSetShader(id: number, locs: Deno.PointerValue): void {
  lib.rlSetShader(id, locs);
}

/** Dispatch compute shader (equivalent to *draw* for graphics pipeline) */
export function rlComputeShaderDispatch(
  groupX: number,
  groupY: number,
  groupZ: number,
): void {
  lib.rlComputeShaderDispatch(groupX, groupY, groupZ);
}

/** Load shader storage buffer object (SSBO) */
export function rlLoadShaderBuffer(
  size: number,
  data: Deno.PointerValue,
  usageHint: number,
): number {
  return lib.rlLoadShaderBuffer(size, data, usageHint);
}

/** Unload shader storage buffer object (SSBO) */
export function rlUnloadShaderBuffer(ssboId: number): void {
  lib.rlUnloadShaderBuffer(ssboId);
}

/** Update SSBO buffer data */
export function rlUpdateShaderBuffer(
  id: number,
  data: Deno.PointerValue,
  dataSize: number,
  offset: number,
): void {
  lib.rlUpdateShaderBuffer(id, data, dataSize, offset);
}

/** Bind SSBO buffer */
export function rlBindShaderBuffer(id: number, index: number): void {
  lib.rlBindShaderBuffer(id, index);
}

/** Read SSBO buffer data (GPU->CPU) */
export function rlReadShaderBuffer(
  id: number,
  dest: Deno.PointerValue,
  count: number,
  offset: number,
): void {
  lib.rlReadShaderBuffer(id, dest, count, offset);
}

/** Copy SSBO data between buffers */
export function rlCopyShaderBuffer(
  destId: number,
  srcId: number,
  destOffset: number,
  srcOffset: number,
  count: number,
): void {
  lib.rlCopyShaderBuffer(destId, srcId, destOffset, srcOffset, count);
}

/** Get SSBO buffer size */
export function rlGetShaderBufferSize(id: number): number {
  return lib.rlGetShaderBufferSize(id);
}

/** Bind image texture */
export function rlBindImageTexture(
  id: number,
  index: number,
  format: number,
  readonly: boolean,
): void {
  lib.rlBindImageTexture(id, index, format, readonly ? 1 : 0);
}

/** Get internal modelview matrix */
export function rlGetMatrixModelview(): Matrix {
  return new Matrix(lib.rlGetMatrixModelview() as Uint8Array<ArrayBuffer>);
}

/** Get internal projection matrix */
export function rlGetMatrixProjection(): Matrix {
  return new Matrix(lib.rlGetMatrixProjection() as Uint8Array<ArrayBuffer>);
}

/** Get internal accumulated transform matrix */
export function rlGetMatrixTransform(): Matrix {
  return new Matrix(lib.rlGetMatrixTransform() as Uint8Array<ArrayBuffer>);
}

/** Get internal projection matrix for stereo render (selected eye) */
export function rlGetMatrixProjectionStereo(eye: number): Matrix {
  return new Matrix(
    lib.rlGetMatrixProjectionStereo(eye) as Uint8Array<ArrayBuffer>,
  );
}

/** Get internal view offset matrix for stereo render (selected eye) */
export function rlGetMatrixViewOffsetStereo(eye: number): Matrix {
  return new Matrix(
    lib.rlGetMatrixViewOffsetStereo(eye) as Uint8Array<ArrayBuffer>,
  );
}

/** Set a custom projection matrix (replaces internal projection matrix) */
export function rlSetMatrixProjection(proj: Matrix): void {
  lib.rlSetMatrixProjection(proj.buffer);
}

/** Set a custom modelview matrix (replaces internal modelview matrix) */
export function rlSetMatrixModelview(view: Matrix): void {
  lib.rlSetMatrixModelview(view.buffer);
}

/** Set eyes projection matrices for stereo rendering */
export function rlSetMatrixProjectionStereo(right: Matrix, left: Matrix): void {
  lib.rlSetMatrixProjectionStereo(right.buffer, left.buffer);
}

/** Set eyes view offsets matrices for stereo rendering */
export function rlSetMatrixViewOffsetStereo(right: Matrix, left: Matrix): void {
  lib.rlSetMatrixViewOffsetStereo(right.buffer, left.buffer);
}

/** Load and draw a cube */
export function rlLoadDrawCube(): void {
  lib.rlLoadDrawCube();
}

/** Load and draw a quad */
export function rlLoadDrawQuad(): void {
  lib.rlLoadDrawQuad();
}
