// Generate the Web facade with names matching the native Modules surface.

import { MODULE_NAMES } from "../../Modules/manifest.ts";
const root = new URL("../../", import.meta.url);
const api = JSON.parse(
  await Deno.readTextFile(new URL("./raylib_api.json", import.meta.url)),
);
const functions = api.functions as Array<{ name: string }>;
const enums = api.enums as Array<{
  name: string;
  description?: string;
  values: Array<{ name: string; value: number; description?: string }>;
}>;
const defines = api.defines as Array<{
  name: string;
  type: string;
  value: unknown;
}>;

const moduleNames = MODULE_NAMES as readonly string[];

await Deno.mkdir(new URL("../../Web/", import.meta.url), {
  recursive: true,
});

const functionNames = functions.map(({ name }) => name);
await Deno.writeTextFile(
  new URL("../../Web/function_names.ts", import.meta.url),
  [
    "// This file is generated by generate_webapp.ts",
    `export const FUNCTION_NAMES = ${
      JSON.stringify(functionNames, null, 2)
    } as const;`,
    "export type FunctionName = (typeof FUNCTION_NAMES)[number];",
    "",
  ].join("\n"),
);

const webValueMappings = (api.structs as Array<{ name: string }>).map(
  ({ name }) =>
    `  T extends import("../Raylib/raylib.ts").${name} ? WebStructs.${name} :`,
);
await Deno.writeTextFile(
  new URL("../../Web/api_types.ts", import.meta.url),
  [
    "// This file is generated by generate_webapp.ts",
    "// deno-lint-ignore-file no-explicit-any",
    'import type * as WebStructs from "./structs.ts";',
    'import type { FunctionName } from "./function_names.ts";',
    'type NativeAPI = typeof import("../Raylib/raylib.ts");',
    "type AnyFunction = (...args: any[]) => any;",
    "export type WebValue<T> =",
    // Native and Web enums share values but have distinct TypeScript
    // identities. Normalize numeric values so Web's own enums are valid.
    "  T extends number ? number :",
    ...webValueMappings,
    "  T extends Promise<infer Value> ? Promise<WebValue<Value>> :",
    "  T extends readonly (infer Value)[] ? WebValue<Value>[] : T;",
    "export type WebFunction<Name extends FunctionName> =",
    "  Extract<NativeAPI[Name], AnyFunction> extends (...args: infer Args) => infer Result",
    "    ? (...args: { [Index in keyof Args]: WebValue<Args[Index]> }) => WebValue<Result>",
    "    : never;",
    "",
  ].join("\n"),
);

const delegates = [
  "// This file is generated by generate_webapp.ts",
  "// deno-lint-ignore-file no-slow-types",
  'import { invoke } from "./Runtime/context.ts";',
  'import type { WebFunction } from "./api_types.ts";',
  'import type { FunctionName } from "./function_names.ts";',
  "const delegate = <Name extends FunctionName>(name: Name): WebFunction<Name> =>",
  "  ((...args: Parameters<WebFunction<Name>>) => invoke(name, args)) as WebFunction<Name>;",
  "",
  ...functionNames.map(
    (name) =>
      `export const ${name}: WebFunction<"${name}"> = delegate("${name}");`,
  ),
  "",
];
await Deno.writeTextFile(
  new URL("../../Web/functions.ts", import.meta.url),
  delegates.join("\n"),
);

const enumOutput: string[] = [
  "// This file is generated by generate_webapp.ts",
];
for (const definition of enums) {
  enumOutput.push(`export enum ${definition.name} {`);
  for (const value of definition.values) {
    enumOutput.push(`  ${value.name} = ${JSON.stringify(value.value)},`);
  }
  enumOutput.push("}");
  if (definition.name.startsWith("rl")) {
    for (const value of definition.values) {
      enumOutput.push(
        `export const ${value.name} = ${definition.name}.${value.name};`,
      );
    }
  }
}

for (const definition of defines) {
  if (
    definition.name.startsWith("RL_") && typeof definition.value === "number"
  ) {
    enumOutput.push(
      `export const ${definition.name} = ${JSON.stringify(definition.value)};`,
    );
  }
}

const colorNames: Record<string, string> = {
  LIGHTGRAY: "LightGray",
  GRAY: "Gray",
  DARKGRAY: "DarkGray",
  YELLOW: "Yellow",
  GOLD: "Gold",
  ORANGE: "Orange",
  PINK: "Pink",
  RED: "Red",
  MAROON: "Maroon",
  GREEN: "Green",
  LIME: "Lime",
  DARKGREEN: "DarkGreen",
  SKYBLUE: "SkyBlue",
  BLUE: "Blue",
  DARKBLUE: "DarkBlue",
  PURPLE: "Purple",
  VIOLET: "Violet",
  DARKPURPLE: "DarkPurple",
  BEIGE: "Beige",
  BROWN: "Brown",
  DARKBROWN: "DarkBrown",
  WHITE: "White",
  BLACK: "Black",
  BLANK: "Blank",
  MAGENTA: "Magenta",
  RAYWHITE: "RayWhite",
};
enumOutput.push('import { Color } from "./structs.ts";');
for (const definition of defines) {
  const exportName = colorNames[definition.name];
  if (!exportName || typeof definition.value !== "string") continue;
  const values = definition.value.match(/\d+/g)?.slice(-4);
  if (!values || values.length !== 4) continue;
  enumOutput.push(
    `export const ${exportName}: Color = new Color(${values.join(", ")});`,
  );
}
enumOutput.push("");
await Deno.writeTextFile(
  new URL("../../Web/constants.ts", import.meta.url),
  enumOutput.join("\n"),
);

await Deno.writeTextFile(
  new URL("../../Web/raylib.ts", import.meta.url),
  [
    "// This file is generated by generate_webapp.ts",
    'export * from "./constants.ts";',
    'export * from "./functions.ts";',
    'export * from "./structs.ts";',
    'export { Vector4 as Quaternion, Texture as Texture2D, Texture as TextureCubemap, RenderTexture as RenderTexture2D } from "./structs.ts";',
    "export type float = number;",
    "export type int = number;",
    "export type bool = boolean;",
    "export type char = string;",
    "export const RAYLIB_VERSION_MAJOR = 6;",
    "export const RAYLIB_VERSION_MINOR = 0;",
    "export const RAYLIB_VERSION_PATCH = 0;",
    'export const RAYLIB_VERSION = "6.0";',
    "",
  ].join("\n"),
);

for (const name of moduleNames) {
  const nativeSource = await Deno.readTextFile(
    new URL(`Modules/${name}.ts`, root),
  );
  let webSource = nativeSource.replaceAll(
    'from "../Raylib/raylib.ts";',
    'from "./raylib.ts";',
  );
  if (name === "Application") {
    webSource +=
      '\nexport { Close, Init, IsInitialized, Run, Stop } from "./Runtime/Application.ts";\n';
    webSource +=
      'export type { InitOptions, RaylibWebBackend, RunOptions, WebBackendFactory, WebBackendFactoryOptions } from "./Runtime/Application.ts";\n';
    webSource +=
      'export { UnsupportedPlatformError, WebNotInitializedError } from "./Runtime/Application.ts";\n';
  }
  await Deno.writeTextFile(new URL(`Web/${name}.ts`, root), webSource);
}

await Deno.writeTextFile(
  new URL("../../Web/Models.ts", import.meta.url),
  '/** @deprecated Prefer `Web/Model`. */\nexport * from "./Model.ts";\n',
);
await Deno.writeTextFile(
  new URL("../../Web/Windows.ts", import.meta.url),
  '/** @deprecated Prefer `Web/Window`. */\nexport * from "./Window.ts";\n',
);

await Deno.writeTextFile(
  new URL("../../Web/mod.ts", import.meta.url),
  [
    ...moduleNames.map((name) => `export * as ${name} from "./${name}.ts";`),
    'export * as Models from "./Models.ts";',
    'export * as Windows from "./Windows.ts";',
    "",
  ].join("\n"),
);

const denoJsonUrl = new URL("../../deno.json", import.meta.url);
const denoJson = JSON.parse(await Deno.readTextFile(denoJsonUrl));
for (const key of Object.keys(denoJson.exports)) {
  if (key.startsWith("./Web")) delete denoJson.exports[key];
}
denoJson.exports["./Web"] = "./Web/mod.ts";
for (const name of moduleNames) {
  denoJson.exports[`./Web/${name}`] = `./Web/${name}.ts`;
}
denoJson.exports["./Web/Models"] = "./Web/Models.ts";
denoJson.exports["./Web/Windows"] = "./Web/Windows.ts";
await Deno.writeTextFile(denoJsonUrl, `${JSON.stringify(denoJson, null, 2)}\n`);
