// Generate the Emscripten C ABI and JavaScript backend for signatures that can
// be marshalled safely as primitives, strings, enums, and by-value structures.
// deno-lint-ignore-file no-explicit-any

const api = JSON.parse(
  await Deno.readTextFile(new URL("./raylib_api.json", import.meta.url)),
);

const structures = new Set<string>(api.structs.map((item: any) => item.name));
const enums = new Set<string>(api.enums.map((item: any) => item.name));
const callbacks = new Set<string>(
  api.callbacks.map((item: any) => item.name),
);
const aliases = new Map<string, string>(
  api.aliases.map((item: any) => [item.name, item.type]),
);
const primitives = new Set([
  "void",
  "bool",
  "char",
  "signed char",
  "unsigned char",
  "short",
  "unsigned short",
  "int",
  "unsigned int",
  "long",
  "unsigned long",
  "long long",
  "unsigned long long",
  "float",
  "double",
]);

function stripConst(type: string): string {
  return type.trim().replace(/^const\s+/, "").trim();
}

function resolveAlias(type: string): string {
  let current = stripConst(type);
  const seen = new Set<string>();
  while (aliases.has(current) && !seen.has(current)) {
    seen.add(current);
    current = aliases.get(current)!;
  }
  return current;
}

function isString(type: string): boolean {
  return type.trim() === "const char *" || type.trim() === "char *";
}

function isStruct(type: string): boolean {
  return structures.has(resolveAlias(type));
}

function mutableStructPointer(type: string): string | undefined {
  const value = type.trim();
  if (value.startsWith("const ") || !value.endsWith("*")) return undefined;
  const base = value.slice(0, -1).trim();
  const resolved = resolveAlias(base);
  return structures.has(resolved) ? resolved : undefined;
}

function isBool(type: string): boolean {
  return resolveAlias(type) === "bool";
}

function isSupported(type: string): boolean {
  const value = type.trim();
  if (isString(value)) return true;
  if (mutableStructPointer(value)) return true;
  if (
    value.includes("*") || value.includes("[") || value.includes("...") ||
    callbacks.has(value)
  ) return false;
  const resolved = resolveAlias(value);
  return primitives.has(resolved) || structures.has(resolved) ||
    enums.has(resolved);
}

const functions = api.functions.filter((fn: any) =>
  isSupported(fn.returnType) &&
  (fn.params ?? []).every((param: any) => isSupported(param.type))
);

let c = `// Generated by generate_wasm_bridge.ts. Do not edit.\n
#include "raylib.h"
#include "raymath.h"
#include "rlgl.h"
#include "rcamera.h"
#include <emscripten/emscripten.h>

`;

const exported: string[] = [];
for (const fn of functions) {
  const wrapper = `dr_${fn.name}`;
  exported.push(`_${wrapper}`);
  const resultStruct = isStruct(fn.returnType);
  const returnType = resultStruct ? "void" : fn.returnType;
  const declarations: string[] = [];
  const callArguments: string[] = [];
  if (resultStruct) declarations.push(`${fn.returnType} *result`);
  for (const [index, param] of (fn.params ?? []).entries()) {
    const name = `p${index}`;
    if (isStruct(param.type)) {
      declarations.push(`const ${stripConst(param.type)} *${name}`);
      callArguments.push(`*${name}`);
    } else {
      declarations.push(`${param.type} ${name}`);
      callArguments.push(name);
    }
  }
  const invocation = `${fn.name}(${callArguments.join(", ")})`;
  const body = resultStruct
    ? `*result = ${invocation};`
    : resolveAlias(fn.returnType) === "void"
    ? `${invocation};`
    : `return ${invocation};`;
  c += `EMSCRIPTEN_KEEPALIVE\n${returnType} ${wrapper}(${
    declarations.join(
      ", ",
    ) || "void"
  }) { ${body} }\n\n`;
}

let js = `// Generated by generate_wasm_bridge.ts. Do not edit.\n`;
js += `// deno-lint-ignore-file no-unused-vars\n`;
js += `import createRaylibModule from "./raylib_web.mjs";\n`;
js += `import * as Structs from "./web_structs.js";\n\n`;
js += `function resolveCanvas(canvas) {\n`;
js += `  if (typeof canvas === "string") {\n`;
js += `    const element = document.querySelector(canvas);\n`;
js += `    if (!element) throw new Error(\`Canvas not found: \${canvas}\`);\n`;
js += `    return element;\n  }\n`;
js += `  if (canvas) return canvas;\n`;
js += `  const element = document.querySelector("canvas");\n`;
js +=
  `  if (!element) throw new Error("A canvas is required for the raylib web backend.");\n`;
js += `  return element;\n}\n\n`;
js += `export default async function createBackend(options = {}) {\n`;
js += `  const module = await createRaylibModule({\n`;
js += `    canvas: resolveCanvas(options.canvas),\n`;
js += `    locateFile: (path) => new URL(path, import.meta.url).href,\n`;
js += `  });\n`;
js += `  const allocate = (value) => {\n`;
js += `    const pointer = module._malloc(value.buffer.byteLength);\n`;
js += `    module.HEAPU8.set(value.buffer, pointer);\n`;
js += `    return pointer;\n  };\n`;
js += `  const copyStruct = (name, pointer) => {\n`;
js += `    const Type = Structs[name];\n`;
js +=
  `    return new Type(module.HEAPU8.slice(pointer, pointer + Type.SIZE));\n`;
js += `  };\n`;
js += `  const backend = {};\n`;

for (const fn of functions) {
  const resultStruct = isStruct(fn.returnType);
  const resultString = isString(fn.returnType);
  const cwrapResult = resultStruct
    ? "null"
    : resultString
    ? JSON.stringify(fn.returnType.trim() === "char *" ? "number" : "string")
    : resolveAlias(fn.returnType) === "void"
    ? "null"
    : '"number"';
  const cwrapParams = [
    ...(resultStruct ? ["number"] : []),
    ...(fn.params ?? []).map((param: any) =>
      isString(param.type) ? "string" : "number"
    ),
  ];
  js += `  {\n`;
  js += `    const call = module.cwrap("dr_${fn.name}", ${cwrapResult}, ${
    JSON.stringify(cwrapParams)
  });\n`;
  js += `    backend.${fn.name} = (...args) => {\n`;
  js += `      const allocations = [];\n`;
  if (resultStruct) {
    js += `      const result = module._malloc(Structs.${
      resolveAlias(fn.returnType)
    }.SIZE);\n`;
    js += `      allocations.push(result);\n`;
  }
  for (const [index, param] of (fn.params ?? []).entries()) {
    if (mutableStructPointer(param.type)) js += `      let p${index};\n`;
  }
  js += `      try {\n`;
  const callArgs: string[] = resultStruct ? ["result"] : [];
  for (const [index, param] of (fn.params ?? []).entries()) {
    if (isStruct(param.type) || mutableStructPointer(param.type)) {
      const declaration = mutableStructPointer(param.type) ? "" : "const ";
      js += `        ${declaration}p${index} = allocate(args[${index}]);\n`;
      js += `        allocations.push(p${index});\n`;
      callArgs.push(`p${index}`);
    } else {
      callArgs.push(`args[${index}]`);
    }
  }
  if (resultStruct) {
    js += `        call(${callArgs.join(", ")});\n`;
    js += `        return copyStruct("${
      resolveAlias(fn.returnType)
    }", result);\n`;
  } else if (fn.returnType.trim() === "char *") {
    js += `        const pointer = call(${callArgs.join(", ")});\n`;
    js += `        if (!pointer) return "";\n`;
    js += `        const value = module.UTF8ToString(pointer);\n`;
    js += `        module._free(pointer);\n`;
    js += `        return value;\n`;
  } else if (resolveAlias(fn.returnType) === "void") {
    js += `        call(${callArgs.join(", ")});\n`;
  } else if (isBool(fn.returnType)) {
    js += `        return Boolean(call(${callArgs.join(", ")}));\n`;
  } else {
    js += `        return call(${callArgs.join(", ")});\n`;
  }
  js += `      } finally {\n`;
  for (const [index, param] of (fn.params ?? []).entries()) {
    if (mutableStructPointer(param.type)) {
      js +=
        `        args[${index}].buffer.set(module.HEAPU8.subarray(p${index}, p${index} + args[${index}].buffer.byteLength));\n`;
    }
  }
  js += `        for (const pointer of allocations) module._free(pointer);\n`;
  js += `      }\n`;
  js += `    };\n  }\n`;
}
js += `  return backend;\n}\n`;

const bridgeRoot = new URL("../../Web/Bridge/", import.meta.url);
await Deno.writeTextFile(new URL("generated.c", bridgeRoot), c);
await Deno.writeTextFile(new URL("backend.mjs", bridgeRoot), js);
await Deno.writeTextFile(
  new URL("exports.json", bridgeRoot),
  JSON.stringify(
    {
      functions: functions.map((fn: any) => fn.name),
      unsupported: api.functions
        .filter((fn: any) => !functions.includes(fn))
        .map((fn: any) => fn.name),
      exported,
    },
    null,
    2,
  ) +
    "\n",
);
console.log(`Generated ${functions.length} WebAssembly function bridges.`);
