// Generate C-style rcamera.h and rlgl.h wrappers.
// deno-lint-ignore-file no-explicit-any

const apiPath = new URL("./raylib_api.json", import.meta.url);
const api = JSON.parse(Deno.readTextFileSync(apiPath));

const aliases = new Map<string, string>(
  api.aliases.map((value: any) => [value.name, value.type]),
);
const structs = new Set<string>(api.structs.map((value: any) => value.name));
const cameraFunctions = new Set([
  "GetCameraForward",
  "GetCameraUp",
  "GetCameraRight",
  "CameraMoveForward",
  "CameraMoveUp",
  "CameraMoveRight",
  "CameraMoveToTarget",
  "CameraYaw",
  "CameraPitch",
  "CameraRoll",
  "GetCameraViewMatrix",
  "GetCameraProjectionMatrix",
]);

function strip(type: string): string {
  return type.replace(/^const\s+/, "").trim();
}

function resolve(type: string): string {
  let current = type;
  const seen = new Set<string>();
  while (aliases.has(current) && !seen.has(current)) {
    seen.add(current);
    current = aliases.get(current)!;
  }
  return current;
}

function pointerBase(type: string): string {
  return resolve(strip(type).replace(/\*/g, "").trim());
}

function tsType(type: string, isReturn = false): string {
  const value = strip(type);
  if (value.includes("*")) {
    const base = pointerBase(value);
    if (isReturn && base === "char") return "string";
    if (structs.has(base)) return `${base} | null`;
    return "Deno.PointerValue";
  }
  const resolved = resolve(value);
  if (structs.has(resolved)) return resolved;
  if (resolved === "void") return "void";
  if (resolved === "bool") return "boolean";
  return "number";
}

function argument(param: any): string {
  const value = strip(param.type);
  if (value.includes("*")) {
    const base = pointerBase(value);
    if (base === "char") return `cstr(${param.name} as string)`;
    if (structs.has(base)) return `${param.name}?.buffer ?? null`;
    return param.name;
  }
  const resolved = resolve(value);
  if (structs.has(resolved)) return `${param.name}.buffer`;
  if (resolved === "bool") return `${param.name} ? 1 : 0`;
  return param.name;
}

function returnExpression(fn: any, call: string): string {
  const value = strip(fn.returnType);
  if (value.includes("*")) {
    const base = pointerBase(value);
    if (base === "char") return `return readCString(${call});`;
    return `return ${call};`;
  }
  const resolved = resolve(value);
  if (structs.has(resolved)) {
    return `return new ${resolved}(${call} as Uint8Array<ArrayBuffer>);`;
  }
  if (resolved === "void") return `${call};`;
  if (resolved === "bool") return `return !!${call};`;
  return `return ${call};`;
}

const functions = api.functions.filter((fn: any) =>
  fn.name.startsWith("rl") || cameraFunctions.has(fn.name)
);
const usedStructs = new Set<string>();
for (const struct of api.structs) {
  if (struct.name.startsWith("rl")) usedStructs.add(struct.name);
}
for (const fn of functions) {
  for (
    const type of [
      fn.returnType,
      ...(fn.params ?? []).map((p: any) => p.type),
    ]
  ) {
    const base = type.includes("*") ? pointerBase(type) : resolve(strip(type));
    if (structs.has(base)) usedStructs.add(base);
  }
}

let output = "// This file is generated by generate_rlgl.ts\n";
output += "// deno-lint-ignore-file verbatim-module-syntax no-unused-vars\n\n";
output += 'import { lib as DLL } from "./bindings.ts";\n';
output += `import { ${
  [...usedStructs].sort().join(", ")
} } from "./Structs/structs.ts";\n`;
output += `export { ${
  [...usedStructs].sort().join(", ")
} } from "./Structs/structs.ts";\n\n`;
output += "const encoder = new TextEncoder();\n";
output += "const lib = DLL.symbols;\n";
output += 'const cstr = (text: string) => encoder.encode(text + "\\0");\n';
output +=
  'const readCString = (ptr: Deno.PointerValue) => ptr === null ? "" : Deno.UnsafePointerView.getCString(ptr);\n\n';

for (
  const enumDef of api.enums.filter((value: any) => value.name.startsWith("rl"))
) {
  output += `/** ${enumDef.description ?? ""} */\n`;
  output += `export enum ${enumDef.name} {\n`;
  for (const value of enumDef.values) {
    output += `  ${value.name} = ${value.value},\n`;
  }
  output += "}\n";
  for (const value of enumDef.values) {
    output += `export const ${value.name} = ${enumDef.name}.${value.name};\n`;
  }
  output += "\n";
}

for (
  const define of api.defines.filter((value: any) =>
    value.name.startsWith("RL_") && typeof value.value === "number"
  )
) {
  output += `export const ${define.name} = ${define.value};\n`;
}
output += "\n";

for (const fn of functions) {
  const params = (fn.params ?? []).map((param: any) =>
    `${param.name}: ${
      pointerBase(param.type) === "char" ? "string" : tsType(param.type)
    }`
  );
  const args = (fn.params ?? []).map(argument);
  const call = `lib.${fn.name}(${args.join(", ")})`;
  output += `/** ${fn.description ?? ""} */\n`;
  output += `export function ${fn.name}(${params.join(", ")}): ${
    tsType(fn.returnType, true)
  } {\n`;
  output += `  ${returnExpression(fn, call)}\n`;
  output += "}\n\n";
}

await Deno.writeTextFile(new URL("../rlgl.ts", import.meta.url), output);
