// This file is generated by generate_webapp.ts
// deno-lint-ignore-file no-explicit-any
import type * as WebStructs from "./structs.ts";
import type { FunctionName } from "./function_names.ts";
type NativeAPI = typeof import("../Raylib/raylib.ts");
type AnyFunction = (...args: any[]) => any;
export type WebValue<T> = T extends number ? number
  : T extends import("../Raylib/raylib.ts").Vector2 ? WebStructs.Vector2
  : T extends import("../Raylib/raylib.ts").Vector3 ? WebStructs.Vector3
  : T extends import("../Raylib/raylib.ts").Vector4 ? WebStructs.Vector4
  : T extends import("../Raylib/raylib.ts").Matrix ? WebStructs.Matrix
  : T extends import("../Raylib/raylib.ts").Color ? WebStructs.Color
  : T extends import("../Raylib/raylib.ts").Rectangle ? WebStructs.Rectangle
  : T extends import("../Raylib/raylib.ts").Image ? WebStructs.Image
  : T extends import("../Raylib/raylib.ts").Texture ? WebStructs.Texture
  : T extends import("../Raylib/raylib.ts").RenderTexture
    ? WebStructs.RenderTexture
  : T extends import("../Raylib/raylib.ts").NPatchInfo ? WebStructs.NPatchInfo
  : T extends import("../Raylib/raylib.ts").GlyphInfo ? WebStructs.GlyphInfo
  : T extends import("../Raylib/raylib.ts").Font ? WebStructs.Font
  : T extends import("../Raylib/raylib.ts").Camera3D ? WebStructs.Camera3D
  : T extends import("../Raylib/raylib.ts").Camera2D ? WebStructs.Camera2D
  : T extends import("../Raylib/raylib.ts").Mesh ? WebStructs.Mesh
  : T extends import("../Raylib/raylib.ts").Shader ? WebStructs.Shader
  : T extends import("../Raylib/raylib.ts").MaterialMap ? WebStructs.MaterialMap
  : T extends import("../Raylib/raylib.ts").Material ? WebStructs.Material
  : T extends import("../Raylib/raylib.ts").Transform ? WebStructs.Transform
  : T extends import("../Raylib/raylib.ts").BoneInfo ? WebStructs.BoneInfo
  : T extends import("../Raylib/raylib.ts").ModelSkeleton
    ? WebStructs.ModelSkeleton
  : T extends import("../Raylib/raylib.ts").Model ? WebStructs.Model
  : T extends import("../Raylib/raylib.ts").ModelAnimation
    ? WebStructs.ModelAnimation
  : T extends import("../Raylib/raylib.ts").Ray ? WebStructs.Ray
  : T extends import("../Raylib/raylib.ts").RayCollision
    ? WebStructs.RayCollision
  : T extends import("../Raylib/raylib.ts").BoundingBox ? WebStructs.BoundingBox
  : T extends import("../Raylib/raylib.ts").Wave ? WebStructs.Wave
  : T extends import("../Raylib/raylib.ts").AudioStream ? WebStructs.AudioStream
  : T extends import("../Raylib/raylib.ts").Sound ? WebStructs.Sound
  : T extends import("../Raylib/raylib.ts").Music ? WebStructs.Music
  : T extends import("../Raylib/raylib.ts").VrDeviceInfo
    ? WebStructs.VrDeviceInfo
  : T extends import("../Raylib/raylib.ts").VrStereoConfig
    ? WebStructs.VrStereoConfig
  : T extends import("../Raylib/raylib.ts").FilePathList
    ? WebStructs.FilePathList
  : T extends import("../Raylib/raylib.ts").AutomationEvent
    ? WebStructs.AutomationEvent
  : T extends import("../Raylib/raylib.ts").AutomationEventList
    ? WebStructs.AutomationEventList
  : T extends import("../Raylib/raylib.ts").float3 ? WebStructs.float3
  : T extends import("../Raylib/raylib.ts").float16 ? WebStructs.float16
  : T extends import("../Raylib/raylib.ts").rlVertexBuffer
    ? WebStructs.rlVertexBuffer
  : T extends import("../Raylib/raylib.ts").rlDrawCall ? WebStructs.rlDrawCall
  : T extends import("../Raylib/raylib.ts").rlRenderBatch
    ? WebStructs.rlRenderBatch
  : T extends Promise<infer Value> ? Promise<WebValue<Value>>
  : T extends readonly (infer Value)[] ? WebValue<Value>[]
  : T;
export type WebFunction<Name extends FunctionName> =
  Extract<NativeAPI[Name], AnyFunction> extends
    (...args: infer Args) => infer Result ? (
      ...args: { [Index in keyof Args]: WebValue<Args[Index]> }
    ) => WebValue<Result>
    : never;
