// This file is generated by generate_webapp.ts
// deno-lint-ignore-file no-slow-types
import { invoke } from "./Runtime/context.ts";
import type { WebFunction } from "./api_types.ts";
import type { FunctionName } from "./function_names.ts";
const delegate = <Name extends FunctionName>(name: Name): WebFunction<Name> =>
  ((...args: Parameters<WebFunction<Name>>) =>
    invoke(name, args)) as WebFunction<Name>;

export const InitWindow: WebFunction<"InitWindow"> = delegate("InitWindow");
export const CloseWindow: WebFunction<"CloseWindow"> = delegate("CloseWindow");
export const WindowShouldClose: WebFunction<"WindowShouldClose"> = delegate(
  "WindowShouldClose",
);
export const IsWindowReady: WebFunction<"IsWindowReady"> = delegate(
  "IsWindowReady",
);
export const IsWindowFullscreen: WebFunction<"IsWindowFullscreen"> = delegate(
  "IsWindowFullscreen",
);
export const IsWindowHidden: WebFunction<"IsWindowHidden"> = delegate(
  "IsWindowHidden",
);
export const IsWindowMinimized: WebFunction<"IsWindowMinimized"> = delegate(
  "IsWindowMinimized",
);
export const IsWindowMaximized: WebFunction<"IsWindowMaximized"> = delegate(
  "IsWindowMaximized",
);
export const IsWindowFocused: WebFunction<"IsWindowFocused"> = delegate(
  "IsWindowFocused",
);
export const IsWindowResized: WebFunction<"IsWindowResized"> = delegate(
  "IsWindowResized",
);
export const IsWindowState: WebFunction<"IsWindowState"> = delegate(
  "IsWindowState",
);
export const SetWindowState: WebFunction<"SetWindowState"> = delegate(
  "SetWindowState",
);
export const ClearWindowState: WebFunction<"ClearWindowState"> = delegate(
  "ClearWindowState",
);
export const ToggleFullscreen: WebFunction<"ToggleFullscreen"> = delegate(
  "ToggleFullscreen",
);
export const ToggleBorderlessWindowed: WebFunction<"ToggleBorderlessWindowed"> =
  delegate("ToggleBorderlessWindowed");
export const MaximizeWindow: WebFunction<"MaximizeWindow"> = delegate(
  "MaximizeWindow",
);
export const MinimizeWindow: WebFunction<"MinimizeWindow"> = delegate(
  "MinimizeWindow",
);
export const RestoreWindow: WebFunction<"RestoreWindow"> = delegate(
  "RestoreWindow",
);
export const SetWindowIcon: WebFunction<"SetWindowIcon"> = delegate(
  "SetWindowIcon",
);
export const SetWindowIcons: WebFunction<"SetWindowIcons"> = delegate(
  "SetWindowIcons",
);
export const SetWindowTitle: WebFunction<"SetWindowTitle"> = delegate(
  "SetWindowTitle",
);
export const SetWindowPosition: WebFunction<"SetWindowPosition"> = delegate(
  "SetWindowPosition",
);
export const SetWindowMonitor: WebFunction<"SetWindowMonitor"> = delegate(
  "SetWindowMonitor",
);
export const SetWindowMinSize: WebFunction<"SetWindowMinSize"> = delegate(
  "SetWindowMinSize",
);
export const SetWindowMaxSize: WebFunction<"SetWindowMaxSize"> = delegate(
  "SetWindowMaxSize",
);
export const SetWindowSize: WebFunction<"SetWindowSize"> = delegate(
  "SetWindowSize",
);
export const SetWindowOpacity: WebFunction<"SetWindowOpacity"> = delegate(
  "SetWindowOpacity",
);
export const SetWindowFocused: WebFunction<"SetWindowFocused"> = delegate(
  "SetWindowFocused",
);
export const GetWindowHandle: WebFunction<"GetWindowHandle"> = delegate(
  "GetWindowHandle",
);
export const GetScreenWidth: WebFunction<"GetScreenWidth"> = delegate(
  "GetScreenWidth",
);
export const GetScreenHeight: WebFunction<"GetScreenHeight"> = delegate(
  "GetScreenHeight",
);
export const GetRenderWidth: WebFunction<"GetRenderWidth"> = delegate(
  "GetRenderWidth",
);
export const GetRenderHeight: WebFunction<"GetRenderHeight"> = delegate(
  "GetRenderHeight",
);
export const GetMonitorCount: WebFunction<"GetMonitorCount"> = delegate(
  "GetMonitorCount",
);
export const GetCurrentMonitor: WebFunction<"GetCurrentMonitor"> = delegate(
  "GetCurrentMonitor",
);
export const GetMonitorPosition: WebFunction<"GetMonitorPosition"> = delegate(
  "GetMonitorPosition",
);
export const GetMonitorWidth: WebFunction<"GetMonitorWidth"> = delegate(
  "GetMonitorWidth",
);
export const GetMonitorHeight: WebFunction<"GetMonitorHeight"> = delegate(
  "GetMonitorHeight",
);
export const GetMonitorPhysicalWidth: WebFunction<"GetMonitorPhysicalWidth"> =
  delegate("GetMonitorPhysicalWidth");
export const GetMonitorPhysicalHeight: WebFunction<"GetMonitorPhysicalHeight"> =
  delegate("GetMonitorPhysicalHeight");
export const GetMonitorRefreshRate: WebFunction<"GetMonitorRefreshRate"> =
  delegate("GetMonitorRefreshRate");
export const GetWindowPosition: WebFunction<"GetWindowPosition"> = delegate(
  "GetWindowPosition",
);
export const GetWindowScaleDPI: WebFunction<"GetWindowScaleDPI"> = delegate(
  "GetWindowScaleDPI",
);
export const GetMonitorName: WebFunction<"GetMonitorName"> = delegate(
  "GetMonitorName",
);
export const SetClipboardText: WebFunction<"SetClipboardText"> = delegate(
  "SetClipboardText",
);
export const GetClipboardText: WebFunction<"GetClipboardText"> = delegate(
  "GetClipboardText",
);
export const GetClipboardImage: WebFunction<"GetClipboardImage"> = delegate(
  "GetClipboardImage",
);
export const EnableEventWaiting: WebFunction<"EnableEventWaiting"> = delegate(
  "EnableEventWaiting",
);
export const DisableEventWaiting: WebFunction<"DisableEventWaiting"> = delegate(
  "DisableEventWaiting",
);
export const ShowCursor: WebFunction<"ShowCursor"> = delegate("ShowCursor");
export const HideCursor: WebFunction<"HideCursor"> = delegate("HideCursor");
export const IsCursorHidden: WebFunction<"IsCursorHidden"> = delegate(
  "IsCursorHidden",
);
export const EnableCursor: WebFunction<"EnableCursor"> = delegate(
  "EnableCursor",
);
export const DisableCursor: WebFunction<"DisableCursor"> = delegate(
  "DisableCursor",
);
export const IsCursorOnScreen: WebFunction<"IsCursorOnScreen"> = delegate(
  "IsCursorOnScreen",
);
export const ClearBackground: WebFunction<"ClearBackground"> = delegate(
  "ClearBackground",
);
export const BeginDrawing: WebFunction<"BeginDrawing"> = delegate(
  "BeginDrawing",
);
export const EndDrawing: WebFunction<"EndDrawing"> = delegate("EndDrawing");
export const BeginMode2D: WebFunction<"BeginMode2D"> = delegate("BeginMode2D");
export const EndMode2D: WebFunction<"EndMode2D"> = delegate("EndMode2D");
export const BeginMode3D: WebFunction<"BeginMode3D"> = delegate("BeginMode3D");
export const EndMode3D: WebFunction<"EndMode3D"> = delegate("EndMode3D");
export const BeginTextureMode: WebFunction<"BeginTextureMode"> = delegate(
  "BeginTextureMode",
);
export const EndTextureMode: WebFunction<"EndTextureMode"> = delegate(
  "EndTextureMode",
);
export const BeginShaderMode: WebFunction<"BeginShaderMode"> = delegate(
  "BeginShaderMode",
);
export const EndShaderMode: WebFunction<"EndShaderMode"> = delegate(
  "EndShaderMode",
);
export const BeginBlendMode: WebFunction<"BeginBlendMode"> = delegate(
  "BeginBlendMode",
);
export const EndBlendMode: WebFunction<"EndBlendMode"> = delegate(
  "EndBlendMode",
);
export const BeginScissorMode: WebFunction<"BeginScissorMode"> = delegate(
  "BeginScissorMode",
);
export const EndScissorMode: WebFunction<"EndScissorMode"> = delegate(
  "EndScissorMode",
);
export const BeginVrStereoMode: WebFunction<"BeginVrStereoMode"> = delegate(
  "BeginVrStereoMode",
);
export const EndVrStereoMode: WebFunction<"EndVrStereoMode"> = delegate(
  "EndVrStereoMode",
);
export const LoadVrStereoConfig: WebFunction<"LoadVrStereoConfig"> = delegate(
  "LoadVrStereoConfig",
);
export const UnloadVrStereoConfig: WebFunction<"UnloadVrStereoConfig"> =
  delegate("UnloadVrStereoConfig");
export const LoadShader: WebFunction<"LoadShader"> = delegate("LoadShader");
export const LoadShaderFromMemory: WebFunction<"LoadShaderFromMemory"> =
  delegate("LoadShaderFromMemory");
export const IsShaderValid: WebFunction<"IsShaderValid"> = delegate(
  "IsShaderValid",
);
export const GetShaderLocation: WebFunction<"GetShaderLocation"> = delegate(
  "GetShaderLocation",
);
export const GetShaderLocationAttrib: WebFunction<"GetShaderLocationAttrib"> =
  delegate("GetShaderLocationAttrib");
export const SetShaderValue: WebFunction<"SetShaderValue"> = delegate(
  "SetShaderValue",
);
export const SetShaderValueV: WebFunction<"SetShaderValueV"> = delegate(
  "SetShaderValueV",
);
export const SetShaderValueMatrix: WebFunction<"SetShaderValueMatrix"> =
  delegate("SetShaderValueMatrix");
export const SetShaderValueTexture: WebFunction<"SetShaderValueTexture"> =
  delegate("SetShaderValueTexture");
export const UnloadShader: WebFunction<"UnloadShader"> = delegate(
  "UnloadShader",
);
export const GetScreenToWorldRay: WebFunction<"GetScreenToWorldRay"> = delegate(
  "GetScreenToWorldRay",
);
export const GetScreenToWorldRayEx: WebFunction<"GetScreenToWorldRayEx"> =
  delegate("GetScreenToWorldRayEx");
export const GetWorldToScreen: WebFunction<"GetWorldToScreen"> = delegate(
  "GetWorldToScreen",
);
export const GetWorldToScreenEx: WebFunction<"GetWorldToScreenEx"> = delegate(
  "GetWorldToScreenEx",
);
export const GetWorldToScreen2D: WebFunction<"GetWorldToScreen2D"> = delegate(
  "GetWorldToScreen2D",
);
export const GetScreenToWorld2D: WebFunction<"GetScreenToWorld2D"> = delegate(
  "GetScreenToWorld2D",
);
export const GetCameraMatrix: WebFunction<"GetCameraMatrix"> = delegate(
  "GetCameraMatrix",
);
export const GetCameraMatrix2D: WebFunction<"GetCameraMatrix2D"> = delegate(
  "GetCameraMatrix2D",
);
export const SetTargetFPS: WebFunction<"SetTargetFPS"> = delegate(
  "SetTargetFPS",
);
export const GetFrameTime: WebFunction<"GetFrameTime"> = delegate(
  "GetFrameTime",
);
export const GetTime: WebFunction<"GetTime"> = delegate("GetTime");
export const GetFPS: WebFunction<"GetFPS"> = delegate("GetFPS");
export const SwapScreenBuffer: WebFunction<"SwapScreenBuffer"> = delegate(
  "SwapScreenBuffer",
);
export const PollInputEvents: WebFunction<"PollInputEvents"> = delegate(
  "PollInputEvents",
);
export const WaitTime: WebFunction<"WaitTime"> = delegate("WaitTime");
export const SetRandomSeed: WebFunction<"SetRandomSeed"> = delegate(
  "SetRandomSeed",
);
export const GetRandomValue: WebFunction<"GetRandomValue"> = delegate(
  "GetRandomValue",
);
export const LoadRandomSequence: WebFunction<"LoadRandomSequence"> = delegate(
  "LoadRandomSequence",
);
export const UnloadRandomSequence: WebFunction<"UnloadRandomSequence"> =
  delegate("UnloadRandomSequence");
export const TakeScreenshot: WebFunction<"TakeScreenshot"> = delegate(
  "TakeScreenshot",
);
export const SetConfigFlags: WebFunction<"SetConfigFlags"> = delegate(
  "SetConfigFlags",
);
export const OpenURL: WebFunction<"OpenURL"> = delegate("OpenURL");
export const SetTraceLogLevel: WebFunction<"SetTraceLogLevel"> = delegate(
  "SetTraceLogLevel",
);
export const TraceLog: WebFunction<"TraceLog"> = delegate("TraceLog");
export const SetTraceLogCallback: WebFunction<"SetTraceLogCallback"> = delegate(
  "SetTraceLogCallback",
);
export const MemAlloc: WebFunction<"MemAlloc"> = delegate("MemAlloc");
export const MemRealloc: WebFunction<"MemRealloc"> = delegate("MemRealloc");
export const MemFree: WebFunction<"MemFree"> = delegate("MemFree");
export const LoadFileData: WebFunction<"LoadFileData"> = delegate(
  "LoadFileData",
);
export const UnloadFileData: WebFunction<"UnloadFileData"> = delegate(
  "UnloadFileData",
);
export const SaveFileData: WebFunction<"SaveFileData"> = delegate(
  "SaveFileData",
);
export const ExportDataAsCode: WebFunction<"ExportDataAsCode"> = delegate(
  "ExportDataAsCode",
);
export const LoadFileText: WebFunction<"LoadFileText"> = delegate(
  "LoadFileText",
);
export const UnloadFileText: WebFunction<"UnloadFileText"> = delegate(
  "UnloadFileText",
);
export const SaveFileText: WebFunction<"SaveFileText"> = delegate(
  "SaveFileText",
);
export const SetLoadFileDataCallback: WebFunction<"SetLoadFileDataCallback"> =
  delegate("SetLoadFileDataCallback");
export const SetSaveFileDataCallback: WebFunction<"SetSaveFileDataCallback"> =
  delegate("SetSaveFileDataCallback");
export const SetLoadFileTextCallback: WebFunction<"SetLoadFileTextCallback"> =
  delegate("SetLoadFileTextCallback");
export const SetSaveFileTextCallback: WebFunction<"SetSaveFileTextCallback"> =
  delegate("SetSaveFileTextCallback");
export const FileRename: WebFunction<"FileRename"> = delegate("FileRename");
export const FileRemove: WebFunction<"FileRemove"> = delegate("FileRemove");
export const FileCopy: WebFunction<"FileCopy"> = delegate("FileCopy");
export const FileMove: WebFunction<"FileMove"> = delegate("FileMove");
export const FileTextReplace: WebFunction<"FileTextReplace"> = delegate(
  "FileTextReplace",
);
export const FileTextFindIndex: WebFunction<"FileTextFindIndex"> = delegate(
  "FileTextFindIndex",
);
export const FileExists: WebFunction<"FileExists"> = delegate("FileExists");
export const DirectoryExists: WebFunction<"DirectoryExists"> = delegate(
  "DirectoryExists",
);
export const IsFileExtension: WebFunction<"IsFileExtension"> = delegate(
  "IsFileExtension",
);
export const GetFileLength: WebFunction<"GetFileLength"> = delegate(
  "GetFileLength",
);
export const GetFileModTime: WebFunction<"GetFileModTime"> = delegate(
  "GetFileModTime",
);
export const GetFileExtension: WebFunction<"GetFileExtension"> = delegate(
  "GetFileExtension",
);
export const GetFileName: WebFunction<"GetFileName"> = delegate("GetFileName");
export const GetFileNameWithoutExt: WebFunction<"GetFileNameWithoutExt"> =
  delegate("GetFileNameWithoutExt");
export const GetDirectoryPath: WebFunction<"GetDirectoryPath"> = delegate(
  "GetDirectoryPath",
);
export const GetPrevDirectoryPath: WebFunction<"GetPrevDirectoryPath"> =
  delegate("GetPrevDirectoryPath");
export const GetWorkingDirectory: WebFunction<"GetWorkingDirectory"> = delegate(
  "GetWorkingDirectory",
);
export const GetApplicationDirectory: WebFunction<"GetApplicationDirectory"> =
  delegate("GetApplicationDirectory");
export const MakeDirectory: WebFunction<"MakeDirectory"> = delegate(
  "MakeDirectory",
);
export const ChangeDirectory: WebFunction<"ChangeDirectory"> = delegate(
  "ChangeDirectory",
);
export const IsPathFile: WebFunction<"IsPathFile"> = delegate("IsPathFile");
export const IsFileNameValid: WebFunction<"IsFileNameValid"> = delegate(
  "IsFileNameValid",
);
export const LoadDirectoryFiles: WebFunction<"LoadDirectoryFiles"> = delegate(
  "LoadDirectoryFiles",
);
export const LoadDirectoryFilesEx: WebFunction<"LoadDirectoryFilesEx"> =
  delegate("LoadDirectoryFilesEx");
export const UnloadDirectoryFiles: WebFunction<"UnloadDirectoryFiles"> =
  delegate("UnloadDirectoryFiles");
export const IsFileDropped: WebFunction<"IsFileDropped"> = delegate(
  "IsFileDropped",
);
export const LoadDroppedFiles: WebFunction<"LoadDroppedFiles"> = delegate(
  "LoadDroppedFiles",
);
export const UnloadDroppedFiles: WebFunction<"UnloadDroppedFiles"> = delegate(
  "UnloadDroppedFiles",
);
export const GetDirectoryFileCount: WebFunction<"GetDirectoryFileCount"> =
  delegate("GetDirectoryFileCount");
export const GetDirectoryFileCountEx: WebFunction<"GetDirectoryFileCountEx"> =
  delegate("GetDirectoryFileCountEx");
export const CompressData: WebFunction<"CompressData"> = delegate(
  "CompressData",
);
export const DecompressData: WebFunction<"DecompressData"> = delegate(
  "DecompressData",
);
export const EncodeDataBase64: WebFunction<"EncodeDataBase64"> = delegate(
  "EncodeDataBase64",
);
export const DecodeDataBase64: WebFunction<"DecodeDataBase64"> = delegate(
  "DecodeDataBase64",
);
export const ComputeCRC32: WebFunction<"ComputeCRC32"> = delegate(
  "ComputeCRC32",
);
export const ComputeMD5: WebFunction<"ComputeMD5"> = delegate("ComputeMD5");
export const ComputeSHA1: WebFunction<"ComputeSHA1"> = delegate("ComputeSHA1");
export const ComputeSHA256: WebFunction<"ComputeSHA256"> = delegate(
  "ComputeSHA256",
);
export const LoadAutomationEventList: WebFunction<"LoadAutomationEventList"> =
  delegate("LoadAutomationEventList");
export const UnloadAutomationEventList: WebFunction<
  "UnloadAutomationEventList"
> = delegate("UnloadAutomationEventList");
export const ExportAutomationEventList: WebFunction<
  "ExportAutomationEventList"
> = delegate("ExportAutomationEventList");
export const SetAutomationEventList: WebFunction<"SetAutomationEventList"> =
  delegate("SetAutomationEventList");
export const SetAutomationEventBaseFrame: WebFunction<
  "SetAutomationEventBaseFrame"
> = delegate("SetAutomationEventBaseFrame");
export const StartAutomationEventRecording: WebFunction<
  "StartAutomationEventRecording"
> = delegate("StartAutomationEventRecording");
export const StopAutomationEventRecording: WebFunction<
  "StopAutomationEventRecording"
> = delegate("StopAutomationEventRecording");
export const PlayAutomationEvent: WebFunction<"PlayAutomationEvent"> = delegate(
  "PlayAutomationEvent",
);
export const IsKeyPressed: WebFunction<"IsKeyPressed"> = delegate(
  "IsKeyPressed",
);
export const IsKeyPressedRepeat: WebFunction<"IsKeyPressedRepeat"> = delegate(
  "IsKeyPressedRepeat",
);
export const IsKeyDown: WebFunction<"IsKeyDown"> = delegate("IsKeyDown");
export const IsKeyReleased: WebFunction<"IsKeyReleased"> = delegate(
  "IsKeyReleased",
);
export const IsKeyUp: WebFunction<"IsKeyUp"> = delegate("IsKeyUp");
export const GetKeyPressed: WebFunction<"GetKeyPressed"> = delegate(
  "GetKeyPressed",
);
export const GetCharPressed: WebFunction<"GetCharPressed"> = delegate(
  "GetCharPressed",
);
export const GetKeyName: WebFunction<"GetKeyName"> = delegate("GetKeyName");
export const SetExitKey: WebFunction<"SetExitKey"> = delegate("SetExitKey");
export const IsGamepadAvailable: WebFunction<"IsGamepadAvailable"> = delegate(
  "IsGamepadAvailable",
);
export const GetGamepadName: WebFunction<"GetGamepadName"> = delegate(
  "GetGamepadName",
);
export const IsGamepadButtonPressed: WebFunction<"IsGamepadButtonPressed"> =
  delegate("IsGamepadButtonPressed");
export const IsGamepadButtonDown: WebFunction<"IsGamepadButtonDown"> = delegate(
  "IsGamepadButtonDown",
);
export const IsGamepadButtonReleased: WebFunction<"IsGamepadButtonReleased"> =
  delegate("IsGamepadButtonReleased");
export const IsGamepadButtonUp: WebFunction<"IsGamepadButtonUp"> = delegate(
  "IsGamepadButtonUp",
);
export const GetGamepadButtonPressed: WebFunction<"GetGamepadButtonPressed"> =
  delegate("GetGamepadButtonPressed");
export const GetGamepadAxisCount: WebFunction<"GetGamepadAxisCount"> = delegate(
  "GetGamepadAxisCount",
);
export const GetGamepadAxisMovement: WebFunction<"GetGamepadAxisMovement"> =
  delegate("GetGamepadAxisMovement");
export const SetGamepadMappings: WebFunction<"SetGamepadMappings"> = delegate(
  "SetGamepadMappings",
);
export const SetGamepadVibration: WebFunction<"SetGamepadVibration"> = delegate(
  "SetGamepadVibration",
);
export const IsMouseButtonPressed: WebFunction<"IsMouseButtonPressed"> =
  delegate("IsMouseButtonPressed");
export const IsMouseButtonDown: WebFunction<"IsMouseButtonDown"> = delegate(
  "IsMouseButtonDown",
);
export const IsMouseButtonReleased: WebFunction<"IsMouseButtonReleased"> =
  delegate("IsMouseButtonReleased");
export const IsMouseButtonUp: WebFunction<"IsMouseButtonUp"> = delegate(
  "IsMouseButtonUp",
);
export const GetMouseX: WebFunction<"GetMouseX"> = delegate("GetMouseX");
export const GetMouseY: WebFunction<"GetMouseY"> = delegate("GetMouseY");
export const GetMousePosition: WebFunction<"GetMousePosition"> = delegate(
  "GetMousePosition",
);
export const GetMouseDelta: WebFunction<"GetMouseDelta"> = delegate(
  "GetMouseDelta",
);
export const SetMousePosition: WebFunction<"SetMousePosition"> = delegate(
  "SetMousePosition",
);
export const SetMouseOffset: WebFunction<"SetMouseOffset"> = delegate(
  "SetMouseOffset",
);
export const SetMouseScale: WebFunction<"SetMouseScale"> = delegate(
  "SetMouseScale",
);
export const GetMouseWheelMove: WebFunction<"GetMouseWheelMove"> = delegate(
  "GetMouseWheelMove",
);
export const GetMouseWheelMoveV: WebFunction<"GetMouseWheelMoveV"> = delegate(
  "GetMouseWheelMoveV",
);
export const SetMouseCursor: WebFunction<"SetMouseCursor"> = delegate(
  "SetMouseCursor",
);
export const GetTouchX: WebFunction<"GetTouchX"> = delegate("GetTouchX");
export const GetTouchY: WebFunction<"GetTouchY"> = delegate("GetTouchY");
export const GetTouchPosition: WebFunction<"GetTouchPosition"> = delegate(
  "GetTouchPosition",
);
export const GetTouchPointId: WebFunction<"GetTouchPointId"> = delegate(
  "GetTouchPointId",
);
export const GetTouchPointCount: WebFunction<"GetTouchPointCount"> = delegate(
  "GetTouchPointCount",
);
export const SetGesturesEnabled: WebFunction<"SetGesturesEnabled"> = delegate(
  "SetGesturesEnabled",
);
export const IsGestureDetected: WebFunction<"IsGestureDetected"> = delegate(
  "IsGestureDetected",
);
export const GetGestureDetected: WebFunction<"GetGestureDetected"> = delegate(
  "GetGestureDetected",
);
export const GetGestureHoldDuration: WebFunction<"GetGestureHoldDuration"> =
  delegate("GetGestureHoldDuration");
export const GetGestureDragVector: WebFunction<"GetGestureDragVector"> =
  delegate("GetGestureDragVector");
export const GetGestureDragAngle: WebFunction<"GetGestureDragAngle"> = delegate(
  "GetGestureDragAngle",
);
export const GetGesturePinchVector: WebFunction<"GetGesturePinchVector"> =
  delegate("GetGesturePinchVector");
export const GetGesturePinchAngle: WebFunction<"GetGesturePinchAngle"> =
  delegate("GetGesturePinchAngle");
export const UpdateCamera: WebFunction<"UpdateCamera"> = delegate(
  "UpdateCamera",
);
export const UpdateCameraPro: WebFunction<"UpdateCameraPro"> = delegate(
  "UpdateCameraPro",
);
export const SetShapesTexture: WebFunction<"SetShapesTexture"> = delegate(
  "SetShapesTexture",
);
export const GetShapesTexture: WebFunction<"GetShapesTexture"> = delegate(
  "GetShapesTexture",
);
export const GetShapesTextureRectangle: WebFunction<
  "GetShapesTextureRectangle"
> = delegate("GetShapesTextureRectangle");
export const DrawPixel: WebFunction<"DrawPixel"> = delegate("DrawPixel");
export const DrawPixelV: WebFunction<"DrawPixelV"> = delegate("DrawPixelV");
export const DrawLine: WebFunction<"DrawLine"> = delegate("DrawLine");
export const DrawLineV: WebFunction<"DrawLineV"> = delegate("DrawLineV");
export const DrawLineEx: WebFunction<"DrawLineEx"> = delegate("DrawLineEx");
export const DrawLineStrip: WebFunction<"DrawLineStrip"> = delegate(
  "DrawLineStrip",
);
export const DrawLineBezier: WebFunction<"DrawLineBezier"> = delegate(
  "DrawLineBezier",
);
export const DrawLineDashed: WebFunction<"DrawLineDashed"> = delegate(
  "DrawLineDashed",
);
export const DrawCircle: WebFunction<"DrawCircle"> = delegate("DrawCircle");
export const DrawCircleV: WebFunction<"DrawCircleV"> = delegate("DrawCircleV");
export const DrawCircleGradient: WebFunction<"DrawCircleGradient"> = delegate(
  "DrawCircleGradient",
);
export const DrawCircleSector: WebFunction<"DrawCircleSector"> = delegate(
  "DrawCircleSector",
);
export const DrawCircleSectorLines: WebFunction<"DrawCircleSectorLines"> =
  delegate("DrawCircleSectorLines");
export const DrawCircleLines: WebFunction<"DrawCircleLines"> = delegate(
  "DrawCircleLines",
);
export const DrawCircleLinesV: WebFunction<"DrawCircleLinesV"> = delegate(
  "DrawCircleLinesV",
);
export const DrawEllipse: WebFunction<"DrawEllipse"> = delegate("DrawEllipse");
export const DrawEllipseV: WebFunction<"DrawEllipseV"> = delegate(
  "DrawEllipseV",
);
export const DrawEllipseLines: WebFunction<"DrawEllipseLines"> = delegate(
  "DrawEllipseLines",
);
export const DrawEllipseLinesV: WebFunction<"DrawEllipseLinesV"> = delegate(
  "DrawEllipseLinesV",
);
export const DrawRing: WebFunction<"DrawRing"> = delegate("DrawRing");
export const DrawRingLines: WebFunction<"DrawRingLines"> = delegate(
  "DrawRingLines",
);
export const DrawRectangle: WebFunction<"DrawRectangle"> = delegate(
  "DrawRectangle",
);
export const DrawRectangleV: WebFunction<"DrawRectangleV"> = delegate(
  "DrawRectangleV",
);
export const DrawRectangleRec: WebFunction<"DrawRectangleRec"> = delegate(
  "DrawRectangleRec",
);
export const DrawRectanglePro: WebFunction<"DrawRectanglePro"> = delegate(
  "DrawRectanglePro",
);
export const DrawRectangleGradientV: WebFunction<"DrawRectangleGradientV"> =
  delegate("DrawRectangleGradientV");
export const DrawRectangleGradientH: WebFunction<"DrawRectangleGradientH"> =
  delegate("DrawRectangleGradientH");
export const DrawRectangleGradientEx: WebFunction<"DrawRectangleGradientEx"> =
  delegate("DrawRectangleGradientEx");
export const DrawRectangleLines: WebFunction<"DrawRectangleLines"> = delegate(
  "DrawRectangleLines",
);
export const DrawRectangleLinesEx: WebFunction<"DrawRectangleLinesEx"> =
  delegate("DrawRectangleLinesEx");
export const DrawRectangleRounded: WebFunction<"DrawRectangleRounded"> =
  delegate("DrawRectangleRounded");
export const DrawRectangleRoundedLines: WebFunction<
  "DrawRectangleRoundedLines"
> = delegate("DrawRectangleRoundedLines");
export const DrawRectangleRoundedLinesEx: WebFunction<
  "DrawRectangleRoundedLinesEx"
> = delegate("DrawRectangleRoundedLinesEx");
export const DrawTriangle: WebFunction<"DrawTriangle"> = delegate(
  "DrawTriangle",
);
export const DrawTriangleLines: WebFunction<"DrawTriangleLines"> = delegate(
  "DrawTriangleLines",
);
export const DrawTriangleFan: WebFunction<"DrawTriangleFan"> = delegate(
  "DrawTriangleFan",
);
export const DrawTriangleStrip: WebFunction<"DrawTriangleStrip"> = delegate(
  "DrawTriangleStrip",
);
export const DrawPoly: WebFunction<"DrawPoly"> = delegate("DrawPoly");
export const DrawPolyLines: WebFunction<"DrawPolyLines"> = delegate(
  "DrawPolyLines",
);
export const DrawPolyLinesEx: WebFunction<"DrawPolyLinesEx"> = delegate(
  "DrawPolyLinesEx",
);
export const DrawSplineLinear: WebFunction<"DrawSplineLinear"> = delegate(
  "DrawSplineLinear",
);
export const DrawSplineBasis: WebFunction<"DrawSplineBasis"> = delegate(
  "DrawSplineBasis",
);
export const DrawSplineCatmullRom: WebFunction<"DrawSplineCatmullRom"> =
  delegate("DrawSplineCatmullRom");
export const DrawSplineBezierQuadratic: WebFunction<
  "DrawSplineBezierQuadratic"
> = delegate("DrawSplineBezierQuadratic");
export const DrawSplineBezierCubic: WebFunction<"DrawSplineBezierCubic"> =
  delegate("DrawSplineBezierCubic");
export const DrawSplineSegmentLinear: WebFunction<"DrawSplineSegmentLinear"> =
  delegate("DrawSplineSegmentLinear");
export const DrawSplineSegmentBasis: WebFunction<"DrawSplineSegmentBasis"> =
  delegate("DrawSplineSegmentBasis");
export const DrawSplineSegmentCatmullRom: WebFunction<
  "DrawSplineSegmentCatmullRom"
> = delegate("DrawSplineSegmentCatmullRom");
export const DrawSplineSegmentBezierQuadratic: WebFunction<
  "DrawSplineSegmentBezierQuadratic"
> = delegate("DrawSplineSegmentBezierQuadratic");
export const DrawSplineSegmentBezierCubic: WebFunction<
  "DrawSplineSegmentBezierCubic"
> = delegate("DrawSplineSegmentBezierCubic");
export const GetSplinePointLinear: WebFunction<"GetSplinePointLinear"> =
  delegate("GetSplinePointLinear");
export const GetSplinePointBasis: WebFunction<"GetSplinePointBasis"> = delegate(
  "GetSplinePointBasis",
);
export const GetSplinePointCatmullRom: WebFunction<"GetSplinePointCatmullRom"> =
  delegate("GetSplinePointCatmullRom");
export const GetSplinePointBezierQuad: WebFunction<"GetSplinePointBezierQuad"> =
  delegate("GetSplinePointBezierQuad");
export const GetSplinePointBezierCubic: WebFunction<
  "GetSplinePointBezierCubic"
> = delegate("GetSplinePointBezierCubic");
export const CheckCollisionRecs: WebFunction<"CheckCollisionRecs"> = delegate(
  "CheckCollisionRecs",
);
export const CheckCollisionCircles: WebFunction<"CheckCollisionCircles"> =
  delegate("CheckCollisionCircles");
export const CheckCollisionCircleRec: WebFunction<"CheckCollisionCircleRec"> =
  delegate("CheckCollisionCircleRec");
export const CheckCollisionCircleLine: WebFunction<"CheckCollisionCircleLine"> =
  delegate("CheckCollisionCircleLine");
export const CheckCollisionPointRec: WebFunction<"CheckCollisionPointRec"> =
  delegate("CheckCollisionPointRec");
export const CheckCollisionPointCircle: WebFunction<
  "CheckCollisionPointCircle"
> = delegate("CheckCollisionPointCircle");
export const CheckCollisionPointTriangle: WebFunction<
  "CheckCollisionPointTriangle"
> = delegate("CheckCollisionPointTriangle");
export const CheckCollisionPointLine: WebFunction<"CheckCollisionPointLine"> =
  delegate("CheckCollisionPointLine");
export const CheckCollisionPointPoly: WebFunction<"CheckCollisionPointPoly"> =
  delegate("CheckCollisionPointPoly");
export const CheckCollisionLines: WebFunction<"CheckCollisionLines"> = delegate(
  "CheckCollisionLines",
);
export const GetCollisionRec: WebFunction<"GetCollisionRec"> = delegate(
  "GetCollisionRec",
);
export const LoadImage: WebFunction<"LoadImage"> = delegate("LoadImage");
export const LoadImageRaw: WebFunction<"LoadImageRaw"> = delegate(
  "LoadImageRaw",
);
export const LoadImageAnim: WebFunction<"LoadImageAnim"> = delegate(
  "LoadImageAnim",
);
export const LoadImageAnimFromMemory: WebFunction<"LoadImageAnimFromMemory"> =
  delegate("LoadImageAnimFromMemory");
export const LoadImageFromMemory: WebFunction<"LoadImageFromMemory"> = delegate(
  "LoadImageFromMemory",
);
export const LoadImageFromTexture: WebFunction<"LoadImageFromTexture"> =
  delegate("LoadImageFromTexture");
export const LoadImageFromScreen: WebFunction<"LoadImageFromScreen"> = delegate(
  "LoadImageFromScreen",
);
export const IsImageValid: WebFunction<"IsImageValid"> = delegate(
  "IsImageValid",
);
export const UnloadImage: WebFunction<"UnloadImage"> = delegate("UnloadImage");
export const ExportImage: WebFunction<"ExportImage"> = delegate("ExportImage");
export const ExportImageToMemory: WebFunction<"ExportImageToMemory"> = delegate(
  "ExportImageToMemory",
);
export const ExportImageAsCode: WebFunction<"ExportImageAsCode"> = delegate(
  "ExportImageAsCode",
);
export const GenImageColor: WebFunction<"GenImageColor"> = delegate(
  "GenImageColor",
);
export const GenImageGradientLinear: WebFunction<"GenImageGradientLinear"> =
  delegate("GenImageGradientLinear");
export const GenImageGradientRadial: WebFunction<"GenImageGradientRadial"> =
  delegate("GenImageGradientRadial");
export const GenImageGradientSquare: WebFunction<"GenImageGradientSquare"> =
  delegate("GenImageGradientSquare");
export const GenImageChecked: WebFunction<"GenImageChecked"> = delegate(
  "GenImageChecked",
);
export const GenImageWhiteNoise: WebFunction<"GenImageWhiteNoise"> = delegate(
  "GenImageWhiteNoise",
);
export const GenImagePerlinNoise: WebFunction<"GenImagePerlinNoise"> = delegate(
  "GenImagePerlinNoise",
);
export const GenImageCellular: WebFunction<"GenImageCellular"> = delegate(
  "GenImageCellular",
);
export const GenImageText: WebFunction<"GenImageText"> = delegate(
  "GenImageText",
);
export const ImageCopy: WebFunction<"ImageCopy"> = delegate("ImageCopy");
export const ImageFromImage: WebFunction<"ImageFromImage"> = delegate(
  "ImageFromImage",
);
export const ImageFromChannel: WebFunction<"ImageFromChannel"> = delegate(
  "ImageFromChannel",
);
export const ImageText: WebFunction<"ImageText"> = delegate("ImageText");
export const ImageTextEx: WebFunction<"ImageTextEx"> = delegate("ImageTextEx");
export const ImageFormat: WebFunction<"ImageFormat"> = delegate("ImageFormat");
export const ImageToPOT: WebFunction<"ImageToPOT"> = delegate("ImageToPOT");
export const ImageCrop: WebFunction<"ImageCrop"> = delegate("ImageCrop");
export const ImageAlphaCrop: WebFunction<"ImageAlphaCrop"> = delegate(
  "ImageAlphaCrop",
);
export const ImageAlphaClear: WebFunction<"ImageAlphaClear"> = delegate(
  "ImageAlphaClear",
);
export const ImageAlphaMask: WebFunction<"ImageAlphaMask"> = delegate(
  "ImageAlphaMask",
);
export const ImageAlphaPremultiply: WebFunction<"ImageAlphaPremultiply"> =
  delegate("ImageAlphaPremultiply");
export const ImageBlurGaussian: WebFunction<"ImageBlurGaussian"> = delegate(
  "ImageBlurGaussian",
);
export const ImageKernelConvolution: WebFunction<"ImageKernelConvolution"> =
  delegate("ImageKernelConvolution");
export const ImageResize: WebFunction<"ImageResize"> = delegate("ImageResize");
export const ImageResizeNN: WebFunction<"ImageResizeNN"> = delegate(
  "ImageResizeNN",
);
export const ImageResizeCanvas: WebFunction<"ImageResizeCanvas"> = delegate(
  "ImageResizeCanvas",
);
export const ImageMipmaps: WebFunction<"ImageMipmaps"> = delegate(
  "ImageMipmaps",
);
export const ImageDither: WebFunction<"ImageDither"> = delegate("ImageDither");
export const ImageFlipVertical: WebFunction<"ImageFlipVertical"> = delegate(
  "ImageFlipVertical",
);
export const ImageFlipHorizontal: WebFunction<"ImageFlipHorizontal"> = delegate(
  "ImageFlipHorizontal",
);
export const ImageRotate: WebFunction<"ImageRotate"> = delegate("ImageRotate");
export const ImageRotateCW: WebFunction<"ImageRotateCW"> = delegate(
  "ImageRotateCW",
);
export const ImageRotateCCW: WebFunction<"ImageRotateCCW"> = delegate(
  "ImageRotateCCW",
);
export const ImageColorTint: WebFunction<"ImageColorTint"> = delegate(
  "ImageColorTint",
);
export const ImageColorInvert: WebFunction<"ImageColorInvert"> = delegate(
  "ImageColorInvert",
);
export const ImageColorGrayscale: WebFunction<"ImageColorGrayscale"> = delegate(
  "ImageColorGrayscale",
);
export const ImageColorContrast: WebFunction<"ImageColorContrast"> = delegate(
  "ImageColorContrast",
);
export const ImageColorBrightness: WebFunction<"ImageColorBrightness"> =
  delegate("ImageColorBrightness");
export const ImageColorReplace: WebFunction<"ImageColorReplace"> = delegate(
  "ImageColorReplace",
);
export const LoadImageColors: WebFunction<"LoadImageColors"> = delegate(
  "LoadImageColors",
);
export const LoadImagePalette: WebFunction<"LoadImagePalette"> = delegate(
  "LoadImagePalette",
);
export const UnloadImageColors: WebFunction<"UnloadImageColors"> = delegate(
  "UnloadImageColors",
);
export const UnloadImagePalette: WebFunction<"UnloadImagePalette"> = delegate(
  "UnloadImagePalette",
);
export const GetImageAlphaBorder: WebFunction<"GetImageAlphaBorder"> = delegate(
  "GetImageAlphaBorder",
);
export const GetImageColor: WebFunction<"GetImageColor"> = delegate(
  "GetImageColor",
);
export const ImageClearBackground: WebFunction<"ImageClearBackground"> =
  delegate("ImageClearBackground");
export const ImageDrawPixel: WebFunction<"ImageDrawPixel"> = delegate(
  "ImageDrawPixel",
);
export const ImageDrawPixelV: WebFunction<"ImageDrawPixelV"> = delegate(
  "ImageDrawPixelV",
);
export const ImageDrawLine: WebFunction<"ImageDrawLine"> = delegate(
  "ImageDrawLine",
);
export const ImageDrawLineV: WebFunction<"ImageDrawLineV"> = delegate(
  "ImageDrawLineV",
);
export const ImageDrawLineEx: WebFunction<"ImageDrawLineEx"> = delegate(
  "ImageDrawLineEx",
);
export const ImageDrawCircle: WebFunction<"ImageDrawCircle"> = delegate(
  "ImageDrawCircle",
);
export const ImageDrawCircleV: WebFunction<"ImageDrawCircleV"> = delegate(
  "ImageDrawCircleV",
);
export const ImageDrawCircleLines: WebFunction<"ImageDrawCircleLines"> =
  delegate("ImageDrawCircleLines");
export const ImageDrawCircleLinesV: WebFunction<"ImageDrawCircleLinesV"> =
  delegate("ImageDrawCircleLinesV");
export const ImageDrawRectangle: WebFunction<"ImageDrawRectangle"> = delegate(
  "ImageDrawRectangle",
);
export const ImageDrawRectangleV: WebFunction<"ImageDrawRectangleV"> = delegate(
  "ImageDrawRectangleV",
);
export const ImageDrawRectangleRec: WebFunction<"ImageDrawRectangleRec"> =
  delegate("ImageDrawRectangleRec");
export const ImageDrawRectangleLines: WebFunction<"ImageDrawRectangleLines"> =
  delegate("ImageDrawRectangleLines");
export const ImageDrawTriangle: WebFunction<"ImageDrawTriangle"> = delegate(
  "ImageDrawTriangle",
);
export const ImageDrawTriangleEx: WebFunction<"ImageDrawTriangleEx"> = delegate(
  "ImageDrawTriangleEx",
);
export const ImageDrawTriangleLines: WebFunction<"ImageDrawTriangleLines"> =
  delegate("ImageDrawTriangleLines");
export const ImageDrawTriangleFan: WebFunction<"ImageDrawTriangleFan"> =
  delegate("ImageDrawTriangleFan");
export const ImageDrawTriangleStrip: WebFunction<"ImageDrawTriangleStrip"> =
  delegate("ImageDrawTriangleStrip");
export const ImageDraw: WebFunction<"ImageDraw"> = delegate("ImageDraw");
export const ImageDrawText: WebFunction<"ImageDrawText"> = delegate(
  "ImageDrawText",
);
export const ImageDrawTextEx: WebFunction<"ImageDrawTextEx"> = delegate(
  "ImageDrawTextEx",
);
export const LoadTexture: WebFunction<"LoadTexture"> = delegate("LoadTexture");
export const LoadTextureFromImage: WebFunction<"LoadTextureFromImage"> =
  delegate("LoadTextureFromImage");
export const LoadTextureCubemap: WebFunction<"LoadTextureCubemap"> = delegate(
  "LoadTextureCubemap",
);
export const LoadRenderTexture: WebFunction<"LoadRenderTexture"> = delegate(
  "LoadRenderTexture",
);
export const IsTextureValid: WebFunction<"IsTextureValid"> = delegate(
  "IsTextureValid",
);
export const UnloadTexture: WebFunction<"UnloadTexture"> = delegate(
  "UnloadTexture",
);
export const IsRenderTextureValid: WebFunction<"IsRenderTextureValid"> =
  delegate("IsRenderTextureValid");
export const UnloadRenderTexture: WebFunction<"UnloadRenderTexture"> = delegate(
  "UnloadRenderTexture",
);
export const UpdateTexture: WebFunction<"UpdateTexture"> = delegate(
  "UpdateTexture",
);
export const UpdateTextureRec: WebFunction<"UpdateTextureRec"> = delegate(
  "UpdateTextureRec",
);
export const GenTextureMipmaps: WebFunction<"GenTextureMipmaps"> = delegate(
  "GenTextureMipmaps",
);
export const SetTextureFilter: WebFunction<"SetTextureFilter"> = delegate(
  "SetTextureFilter",
);
export const SetTextureWrap: WebFunction<"SetTextureWrap"> = delegate(
  "SetTextureWrap",
);
export const DrawTexture: WebFunction<"DrawTexture"> = delegate("DrawTexture");
export const DrawTextureV: WebFunction<"DrawTextureV"> = delegate(
  "DrawTextureV",
);
export const DrawTextureEx: WebFunction<"DrawTextureEx"> = delegate(
  "DrawTextureEx",
);
export const DrawTextureRec: WebFunction<"DrawTextureRec"> = delegate(
  "DrawTextureRec",
);
export const DrawTexturePro: WebFunction<"DrawTexturePro"> = delegate(
  "DrawTexturePro",
);
export const DrawTextureNPatch: WebFunction<"DrawTextureNPatch"> = delegate(
  "DrawTextureNPatch",
);
export const ColorIsEqual: WebFunction<"ColorIsEqual"> = delegate(
  "ColorIsEqual",
);
export const Fade: WebFunction<"Fade"> = delegate("Fade");
export const ColorToInt: WebFunction<"ColorToInt"> = delegate("ColorToInt");
export const ColorNormalize: WebFunction<"ColorNormalize"> = delegate(
  "ColorNormalize",
);
export const ColorFromNormalized: WebFunction<"ColorFromNormalized"> = delegate(
  "ColorFromNormalized",
);
export const ColorToHSV: WebFunction<"ColorToHSV"> = delegate("ColorToHSV");
export const ColorFromHSV: WebFunction<"ColorFromHSV"> = delegate(
  "ColorFromHSV",
);
export const ColorTint: WebFunction<"ColorTint"> = delegate("ColorTint");
export const ColorBrightness: WebFunction<"ColorBrightness"> = delegate(
  "ColorBrightness",
);
export const ColorContrast: WebFunction<"ColorContrast"> = delegate(
  "ColorContrast",
);
export const ColorAlpha: WebFunction<"ColorAlpha"> = delegate("ColorAlpha");
export const ColorAlphaBlend: WebFunction<"ColorAlphaBlend"> = delegate(
  "ColorAlphaBlend",
);
export const ColorLerp: WebFunction<"ColorLerp"> = delegate("ColorLerp");
export const GetColor: WebFunction<"GetColor"> = delegate("GetColor");
export const GetPixelColor: WebFunction<"GetPixelColor"> = delegate(
  "GetPixelColor",
);
export const SetPixelColor: WebFunction<"SetPixelColor"> = delegate(
  "SetPixelColor",
);
export const GetPixelDataSize: WebFunction<"GetPixelDataSize"> = delegate(
  "GetPixelDataSize",
);
export const GetFontDefault: WebFunction<"GetFontDefault"> = delegate(
  "GetFontDefault",
);
export const LoadFont: WebFunction<"LoadFont"> = delegate("LoadFont");
export const LoadFontEx: WebFunction<"LoadFontEx"> = delegate("LoadFontEx");
export const LoadFontFromImage: WebFunction<"LoadFontFromImage"> = delegate(
  "LoadFontFromImage",
);
export const LoadFontFromMemory: WebFunction<"LoadFontFromMemory"> = delegate(
  "LoadFontFromMemory",
);
export const IsFontValid: WebFunction<"IsFontValid"> = delegate("IsFontValid");
export const LoadFontData: WebFunction<"LoadFontData"> = delegate(
  "LoadFontData",
);
export const GenImageFontAtlas: WebFunction<"GenImageFontAtlas"> = delegate(
  "GenImageFontAtlas",
);
export const UnloadFontData: WebFunction<"UnloadFontData"> = delegate(
  "UnloadFontData",
);
export const UnloadFont: WebFunction<"UnloadFont"> = delegate("UnloadFont");
export const ExportFontAsCode: WebFunction<"ExportFontAsCode"> = delegate(
  "ExportFontAsCode",
);
export const DrawFPS: WebFunction<"DrawFPS"> = delegate("DrawFPS");
export const DrawText: WebFunction<"DrawText"> = delegate("DrawText");
export const DrawTextEx: WebFunction<"DrawTextEx"> = delegate("DrawTextEx");
export const DrawTextPro: WebFunction<"DrawTextPro"> = delegate("DrawTextPro");
export const DrawTextCodepoint: WebFunction<"DrawTextCodepoint"> = delegate(
  "DrawTextCodepoint",
);
export const DrawTextCodepoints: WebFunction<"DrawTextCodepoints"> = delegate(
  "DrawTextCodepoints",
);
export const SetTextLineSpacing: WebFunction<"SetTextLineSpacing"> = delegate(
  "SetTextLineSpacing",
);
export const MeasureText: WebFunction<"MeasureText"> = delegate("MeasureText");
export const MeasureTextEx: WebFunction<"MeasureTextEx"> = delegate(
  "MeasureTextEx",
);
export const MeasureTextCodepoints: WebFunction<"MeasureTextCodepoints"> =
  delegate("MeasureTextCodepoints");
export const GetGlyphIndex: WebFunction<"GetGlyphIndex"> = delegate(
  "GetGlyphIndex",
);
export const GetGlyphInfo: WebFunction<"GetGlyphInfo"> = delegate(
  "GetGlyphInfo",
);
export const GetGlyphAtlasRec: WebFunction<"GetGlyphAtlasRec"> = delegate(
  "GetGlyphAtlasRec",
);
export const LoadUTF8: WebFunction<"LoadUTF8"> = delegate("LoadUTF8");
export const UnloadUTF8: WebFunction<"UnloadUTF8"> = delegate("UnloadUTF8");
export const LoadCodepoints: WebFunction<"LoadCodepoints"> = delegate(
  "LoadCodepoints",
);
export const UnloadCodepoints: WebFunction<"UnloadCodepoints"> = delegate(
  "UnloadCodepoints",
);
export const GetCodepointCount: WebFunction<"GetCodepointCount"> = delegate(
  "GetCodepointCount",
);
export const GetCodepoint: WebFunction<"GetCodepoint"> = delegate(
  "GetCodepoint",
);
export const GetCodepointNext: WebFunction<"GetCodepointNext"> = delegate(
  "GetCodepointNext",
);
export const GetCodepointPrevious: WebFunction<"GetCodepointPrevious"> =
  delegate("GetCodepointPrevious");
export const CodepointToUTF8: WebFunction<"CodepointToUTF8"> = delegate(
  "CodepointToUTF8",
);
export const LoadTextLines: WebFunction<"LoadTextLines"> = delegate(
  "LoadTextLines",
);
export const UnloadTextLines: WebFunction<"UnloadTextLines"> = delegate(
  "UnloadTextLines",
);
export const TextCopy: WebFunction<"TextCopy"> = delegate("TextCopy");
export const TextIsEqual: WebFunction<"TextIsEqual"> = delegate("TextIsEqual");
export const TextLength: WebFunction<"TextLength"> = delegate("TextLength");
export const TextFormat: WebFunction<"TextFormat"> = delegate("TextFormat");
export const TextSubtext: WebFunction<"TextSubtext"> = delegate("TextSubtext");
export const TextRemoveSpaces: WebFunction<"TextRemoveSpaces"> = delegate(
  "TextRemoveSpaces",
);
export const GetTextBetween: WebFunction<"GetTextBetween"> = delegate(
  "GetTextBetween",
);
export const TextReplace: WebFunction<"TextReplace"> = delegate("TextReplace");
export const TextReplaceAlloc: WebFunction<"TextReplaceAlloc"> = delegate(
  "TextReplaceAlloc",
);
export const TextReplaceBetween: WebFunction<"TextReplaceBetween"> = delegate(
  "TextReplaceBetween",
);
export const TextReplaceBetweenAlloc: WebFunction<"TextReplaceBetweenAlloc"> =
  delegate("TextReplaceBetweenAlloc");
export const TextInsert: WebFunction<"TextInsert"> = delegate("TextInsert");
export const TextInsertAlloc: WebFunction<"TextInsertAlloc"> = delegate(
  "TextInsertAlloc",
);
export const TextJoin: WebFunction<"TextJoin"> = delegate("TextJoin");
export const TextSplit: WebFunction<"TextSplit"> = delegate("TextSplit");
export const TextAppend: WebFunction<"TextAppend"> = delegate("TextAppend");
export const TextFindIndex: WebFunction<"TextFindIndex"> = delegate(
  "TextFindIndex",
);
export const TextToUpper: WebFunction<"TextToUpper"> = delegate("TextToUpper");
export const TextToLower: WebFunction<"TextToLower"> = delegate("TextToLower");
export const TextToPascal: WebFunction<"TextToPascal"> = delegate(
  "TextToPascal",
);
export const TextToSnake: WebFunction<"TextToSnake"> = delegate("TextToSnake");
export const TextToCamel: WebFunction<"TextToCamel"> = delegate("TextToCamel");
export const TextToInteger: WebFunction<"TextToInteger"> = delegate(
  "TextToInteger",
);
export const TextToFloat: WebFunction<"TextToFloat"> = delegate("TextToFloat");
export const DrawLine3D: WebFunction<"DrawLine3D"> = delegate("DrawLine3D");
export const DrawPoint3D: WebFunction<"DrawPoint3D"> = delegate("DrawPoint3D");
export const DrawCircle3D: WebFunction<"DrawCircle3D"> = delegate(
  "DrawCircle3D",
);
export const DrawTriangle3D: WebFunction<"DrawTriangle3D"> = delegate(
  "DrawTriangle3D",
);
export const DrawTriangleStrip3D: WebFunction<"DrawTriangleStrip3D"> = delegate(
  "DrawTriangleStrip3D",
);
export const DrawCube: WebFunction<"DrawCube"> = delegate("DrawCube");
export const DrawCubeV: WebFunction<"DrawCubeV"> = delegate("DrawCubeV");
export const DrawCubeWires: WebFunction<"DrawCubeWires"> = delegate(
  "DrawCubeWires",
);
export const DrawCubeWiresV: WebFunction<"DrawCubeWiresV"> = delegate(
  "DrawCubeWiresV",
);
export const DrawSphere: WebFunction<"DrawSphere"> = delegate("DrawSphere");
export const DrawSphereEx: WebFunction<"DrawSphereEx"> = delegate(
  "DrawSphereEx",
);
export const DrawSphereWires: WebFunction<"DrawSphereWires"> = delegate(
  "DrawSphereWires",
);
export const DrawCylinder: WebFunction<"DrawCylinder"> = delegate(
  "DrawCylinder",
);
export const DrawCylinderEx: WebFunction<"DrawCylinderEx"> = delegate(
  "DrawCylinderEx",
);
export const DrawCylinderWires: WebFunction<"DrawCylinderWires"> = delegate(
  "DrawCylinderWires",
);
export const DrawCylinderWiresEx: WebFunction<"DrawCylinderWiresEx"> = delegate(
  "DrawCylinderWiresEx",
);
export const DrawCapsule: WebFunction<"DrawCapsule"> = delegate("DrawCapsule");
export const DrawCapsuleWires: WebFunction<"DrawCapsuleWires"> = delegate(
  "DrawCapsuleWires",
);
export const DrawPlane: WebFunction<"DrawPlane"> = delegate("DrawPlane");
export const DrawRay: WebFunction<"DrawRay"> = delegate("DrawRay");
export const DrawGrid: WebFunction<"DrawGrid"> = delegate("DrawGrid");
export const LoadModel: WebFunction<"LoadModel"> = delegate("LoadModel");
export const LoadModelFromMesh: WebFunction<"LoadModelFromMesh"> = delegate(
  "LoadModelFromMesh",
);
export const IsModelValid: WebFunction<"IsModelValid"> = delegate(
  "IsModelValid",
);
export const UnloadModel: WebFunction<"UnloadModel"> = delegate("UnloadModel");
export const GetModelBoundingBox: WebFunction<"GetModelBoundingBox"> = delegate(
  "GetModelBoundingBox",
);
export const DrawModel: WebFunction<"DrawModel"> = delegate("DrawModel");
export const DrawModelEx: WebFunction<"DrawModelEx"> = delegate("DrawModelEx");
export const DrawModelWires: WebFunction<"DrawModelWires"> = delegate(
  "DrawModelWires",
);
export const DrawModelWiresEx: WebFunction<"DrawModelWiresEx"> = delegate(
  "DrawModelWiresEx",
);
export const DrawBoundingBox: WebFunction<"DrawBoundingBox"> = delegate(
  "DrawBoundingBox",
);
export const DrawBillboard: WebFunction<"DrawBillboard"> = delegate(
  "DrawBillboard",
);
export const DrawBillboardRec: WebFunction<"DrawBillboardRec"> = delegate(
  "DrawBillboardRec",
);
export const DrawBillboardPro: WebFunction<"DrawBillboardPro"> = delegate(
  "DrawBillboardPro",
);
export const UploadMesh: WebFunction<"UploadMesh"> = delegate("UploadMesh");
export const UpdateMeshBuffer: WebFunction<"UpdateMeshBuffer"> = delegate(
  "UpdateMeshBuffer",
);
export const UnloadMesh: WebFunction<"UnloadMesh"> = delegate("UnloadMesh");
export const DrawMesh: WebFunction<"DrawMesh"> = delegate("DrawMesh");
export const DrawMeshInstanced: WebFunction<"DrawMeshInstanced"> = delegate(
  "DrawMeshInstanced",
);
export const GetMeshBoundingBox: WebFunction<"GetMeshBoundingBox"> = delegate(
  "GetMeshBoundingBox",
);
export const GenMeshTangents: WebFunction<"GenMeshTangents"> = delegate(
  "GenMeshTangents",
);
export const ExportMesh: WebFunction<"ExportMesh"> = delegate("ExportMesh");
export const ExportMeshAsCode: WebFunction<"ExportMeshAsCode"> = delegate(
  "ExportMeshAsCode",
);
export const GenMeshPoly: WebFunction<"GenMeshPoly"> = delegate("GenMeshPoly");
export const GenMeshPlane: WebFunction<"GenMeshPlane"> = delegate(
  "GenMeshPlane",
);
export const GenMeshCube: WebFunction<"GenMeshCube"> = delegate("GenMeshCube");
export const GenMeshSphere: WebFunction<"GenMeshSphere"> = delegate(
  "GenMeshSphere",
);
export const GenMeshHemiSphere: WebFunction<"GenMeshHemiSphere"> = delegate(
  "GenMeshHemiSphere",
);
export const GenMeshCylinder: WebFunction<"GenMeshCylinder"> = delegate(
  "GenMeshCylinder",
);
export const GenMeshCone: WebFunction<"GenMeshCone"> = delegate("GenMeshCone");
export const GenMeshTorus: WebFunction<"GenMeshTorus"> = delegate(
  "GenMeshTorus",
);
export const GenMeshKnot: WebFunction<"GenMeshKnot"> = delegate("GenMeshKnot");
export const GenMeshHeightmap: WebFunction<"GenMeshHeightmap"> = delegate(
  "GenMeshHeightmap",
);
export const GenMeshCubicmap: WebFunction<"GenMeshCubicmap"> = delegate(
  "GenMeshCubicmap",
);
export const LoadMaterials: WebFunction<"LoadMaterials"> = delegate(
  "LoadMaterials",
);
export const LoadMaterialDefault: WebFunction<"LoadMaterialDefault"> = delegate(
  "LoadMaterialDefault",
);
export const IsMaterialValid: WebFunction<"IsMaterialValid"> = delegate(
  "IsMaterialValid",
);
export const UnloadMaterial: WebFunction<"UnloadMaterial"> = delegate(
  "UnloadMaterial",
);
export const SetMaterialTexture: WebFunction<"SetMaterialTexture"> = delegate(
  "SetMaterialTexture",
);
export const SetModelMeshMaterial: WebFunction<"SetModelMeshMaterial"> =
  delegate("SetModelMeshMaterial");
export const LoadModelAnimations: WebFunction<"LoadModelAnimations"> = delegate(
  "LoadModelAnimations",
);
export const UpdateModelAnimation: WebFunction<"UpdateModelAnimation"> =
  delegate("UpdateModelAnimation");
export const UpdateModelAnimationEx: WebFunction<"UpdateModelAnimationEx"> =
  delegate("UpdateModelAnimationEx");
export const UnloadModelAnimations: WebFunction<"UnloadModelAnimations"> =
  delegate("UnloadModelAnimations");
export const IsModelAnimationValid: WebFunction<"IsModelAnimationValid"> =
  delegate("IsModelAnimationValid");
export const CheckCollisionSpheres: WebFunction<"CheckCollisionSpheres"> =
  delegate("CheckCollisionSpheres");
export const CheckCollisionBoxes: WebFunction<"CheckCollisionBoxes"> = delegate(
  "CheckCollisionBoxes",
);
export const CheckCollisionBoxSphere: WebFunction<"CheckCollisionBoxSphere"> =
  delegate("CheckCollisionBoxSphere");
export const GetRayCollisionSphere: WebFunction<"GetRayCollisionSphere"> =
  delegate("GetRayCollisionSphere");
export const GetRayCollisionBox: WebFunction<"GetRayCollisionBox"> = delegate(
  "GetRayCollisionBox",
);
export const GetRayCollisionMesh: WebFunction<"GetRayCollisionMesh"> = delegate(
  "GetRayCollisionMesh",
);
export const GetRayCollisionTriangle: WebFunction<"GetRayCollisionTriangle"> =
  delegate("GetRayCollisionTriangle");
export const GetRayCollisionQuad: WebFunction<"GetRayCollisionQuad"> = delegate(
  "GetRayCollisionQuad",
);
export const InitAudioDevice: WebFunction<"InitAudioDevice"> = delegate(
  "InitAudioDevice",
);
export const CloseAudioDevice: WebFunction<"CloseAudioDevice"> = delegate(
  "CloseAudioDevice",
);
export const IsAudioDeviceReady: WebFunction<"IsAudioDeviceReady"> = delegate(
  "IsAudioDeviceReady",
);
export const SetMasterVolume: WebFunction<"SetMasterVolume"> = delegate(
  "SetMasterVolume",
);
export const GetMasterVolume: WebFunction<"GetMasterVolume"> = delegate(
  "GetMasterVolume",
);
export const LoadWave: WebFunction<"LoadWave"> = delegate("LoadWave");
export const LoadWaveFromMemory: WebFunction<"LoadWaveFromMemory"> = delegate(
  "LoadWaveFromMemory",
);
export const IsWaveValid: WebFunction<"IsWaveValid"> = delegate("IsWaveValid");
export const LoadSound: WebFunction<"LoadSound"> = delegate("LoadSound");
export const LoadSoundFromWave: WebFunction<"LoadSoundFromWave"> = delegate(
  "LoadSoundFromWave",
);
export const LoadSoundAlias: WebFunction<"LoadSoundAlias"> = delegate(
  "LoadSoundAlias",
);
export const IsSoundValid: WebFunction<"IsSoundValid"> = delegate(
  "IsSoundValid",
);
export const UpdateSound: WebFunction<"UpdateSound"> = delegate("UpdateSound");
export const UnloadWave: WebFunction<"UnloadWave"> = delegate("UnloadWave");
export const UnloadSound: WebFunction<"UnloadSound"> = delegate("UnloadSound");
export const UnloadSoundAlias: WebFunction<"UnloadSoundAlias"> = delegate(
  "UnloadSoundAlias",
);
export const ExportWave: WebFunction<"ExportWave"> = delegate("ExportWave");
export const ExportWaveAsCode: WebFunction<"ExportWaveAsCode"> = delegate(
  "ExportWaveAsCode",
);
export const PlaySound: WebFunction<"PlaySound"> = delegate("PlaySound");
export const StopSound: WebFunction<"StopSound"> = delegate("StopSound");
export const PauseSound: WebFunction<"PauseSound"> = delegate("PauseSound");
export const ResumeSound: WebFunction<"ResumeSound"> = delegate("ResumeSound");
export const IsSoundPlaying: WebFunction<"IsSoundPlaying"> = delegate(
  "IsSoundPlaying",
);
export const SetSoundVolume: WebFunction<"SetSoundVolume"> = delegate(
  "SetSoundVolume",
);
export const SetSoundPitch: WebFunction<"SetSoundPitch"> = delegate(
  "SetSoundPitch",
);
export const SetSoundPan: WebFunction<"SetSoundPan"> = delegate("SetSoundPan");
export const WaveCopy: WebFunction<"WaveCopy"> = delegate("WaveCopy");
export const WaveCrop: WebFunction<"WaveCrop"> = delegate("WaveCrop");
export const WaveFormat: WebFunction<"WaveFormat"> = delegate("WaveFormat");
export const LoadWaveSamples: WebFunction<"LoadWaveSamples"> = delegate(
  "LoadWaveSamples",
);
export const UnloadWaveSamples: WebFunction<"UnloadWaveSamples"> = delegate(
  "UnloadWaveSamples",
);
export const LoadMusicStream: WebFunction<"LoadMusicStream"> = delegate(
  "LoadMusicStream",
);
export const LoadMusicStreamFromMemory: WebFunction<
  "LoadMusicStreamFromMemory"
> = delegate("LoadMusicStreamFromMemory");
export const IsMusicValid: WebFunction<"IsMusicValid"> = delegate(
  "IsMusicValid",
);
export const UnloadMusicStream: WebFunction<"UnloadMusicStream"> = delegate(
  "UnloadMusicStream",
);
export const PlayMusicStream: WebFunction<"PlayMusicStream"> = delegate(
  "PlayMusicStream",
);
export const IsMusicStreamPlaying: WebFunction<"IsMusicStreamPlaying"> =
  delegate("IsMusicStreamPlaying");
export const UpdateMusicStream: WebFunction<"UpdateMusicStream"> = delegate(
  "UpdateMusicStream",
);
export const StopMusicStream: WebFunction<"StopMusicStream"> = delegate(
  "StopMusicStream",
);
export const PauseMusicStream: WebFunction<"PauseMusicStream"> = delegate(
  "PauseMusicStream",
);
export const ResumeMusicStream: WebFunction<"ResumeMusicStream"> = delegate(
  "ResumeMusicStream",
);
export const SeekMusicStream: WebFunction<"SeekMusicStream"> = delegate(
  "SeekMusicStream",
);
export const SetMusicVolume: WebFunction<"SetMusicVolume"> = delegate(
  "SetMusicVolume",
);
export const SetMusicPitch: WebFunction<"SetMusicPitch"> = delegate(
  "SetMusicPitch",
);
export const SetMusicPan: WebFunction<"SetMusicPan"> = delegate("SetMusicPan");
export const GetMusicTimeLength: WebFunction<"GetMusicTimeLength"> = delegate(
  "GetMusicTimeLength",
);
export const GetMusicTimePlayed: WebFunction<"GetMusicTimePlayed"> = delegate(
  "GetMusicTimePlayed",
);
export const LoadAudioStream: WebFunction<"LoadAudioStream"> = delegate(
  "LoadAudioStream",
);
export const IsAudioStreamValid: WebFunction<"IsAudioStreamValid"> = delegate(
  "IsAudioStreamValid",
);
export const UnloadAudioStream: WebFunction<"UnloadAudioStream"> = delegate(
  "UnloadAudioStream",
);
export const UpdateAudioStream: WebFunction<"UpdateAudioStream"> = delegate(
  "UpdateAudioStream",
);
export const IsAudioStreamProcessed: WebFunction<"IsAudioStreamProcessed"> =
  delegate("IsAudioStreamProcessed");
export const PlayAudioStream: WebFunction<"PlayAudioStream"> = delegate(
  "PlayAudioStream",
);
export const PauseAudioStream: WebFunction<"PauseAudioStream"> = delegate(
  "PauseAudioStream",
);
export const ResumeAudioStream: WebFunction<"ResumeAudioStream"> = delegate(
  "ResumeAudioStream",
);
export const IsAudioStreamPlaying: WebFunction<"IsAudioStreamPlaying"> =
  delegate("IsAudioStreamPlaying");
export const StopAudioStream: WebFunction<"StopAudioStream"> = delegate(
  "StopAudioStream",
);
export const SetAudioStreamVolume: WebFunction<"SetAudioStreamVolume"> =
  delegate("SetAudioStreamVolume");
export const SetAudioStreamPitch: WebFunction<"SetAudioStreamPitch"> = delegate(
  "SetAudioStreamPitch",
);
export const SetAudioStreamPan: WebFunction<"SetAudioStreamPan"> = delegate(
  "SetAudioStreamPan",
);
export const SetAudioStreamBufferSizeDefault: WebFunction<
  "SetAudioStreamBufferSizeDefault"
> = delegate("SetAudioStreamBufferSizeDefault");
export const SetAudioStreamCallback: WebFunction<"SetAudioStreamCallback"> =
  delegate("SetAudioStreamCallback");
export const AttachAudioStreamProcessor: WebFunction<
  "AttachAudioStreamProcessor"
> = delegate("AttachAudioStreamProcessor");
export const DetachAudioStreamProcessor: WebFunction<
  "DetachAudioStreamProcessor"
> = delegate("DetachAudioStreamProcessor");
export const AttachAudioMixedProcessor: WebFunction<
  "AttachAudioMixedProcessor"
> = delegate("AttachAudioMixedProcessor");
export const DetachAudioMixedProcessor: WebFunction<
  "DetachAudioMixedProcessor"
> = delegate("DetachAudioMixedProcessor");
export const Clamp: WebFunction<"Clamp"> = delegate("Clamp");
export const Lerp: WebFunction<"Lerp"> = delegate("Lerp");
export const Normalize: WebFunction<"Normalize"> = delegate("Normalize");
export const Remap: WebFunction<"Remap"> = delegate("Remap");
export const Wrap: WebFunction<"Wrap"> = delegate("Wrap");
export const FloatEquals: WebFunction<"FloatEquals"> = delegate("FloatEquals");
export const Vector2Zero: WebFunction<"Vector2Zero"> = delegate("Vector2Zero");
export const Vector2One: WebFunction<"Vector2One"> = delegate("Vector2One");
export const Vector2Add: WebFunction<"Vector2Add"> = delegate("Vector2Add");
export const Vector2AddValue: WebFunction<"Vector2AddValue"> = delegate(
  "Vector2AddValue",
);
export const Vector2Subtract: WebFunction<"Vector2Subtract"> = delegate(
  "Vector2Subtract",
);
export const Vector2SubtractValue: WebFunction<"Vector2SubtractValue"> =
  delegate("Vector2SubtractValue");
export const Vector2Length: WebFunction<"Vector2Length"> = delegate(
  "Vector2Length",
);
export const Vector2LengthSqr: WebFunction<"Vector2LengthSqr"> = delegate(
  "Vector2LengthSqr",
);
export const Vector2DotProduct: WebFunction<"Vector2DotProduct"> = delegate(
  "Vector2DotProduct",
);
export const Vector2CrossProduct: WebFunction<"Vector2CrossProduct"> = delegate(
  "Vector2CrossProduct",
);
export const Vector2Distance: WebFunction<"Vector2Distance"> = delegate(
  "Vector2Distance",
);
export const Vector2DistanceSqr: WebFunction<"Vector2DistanceSqr"> = delegate(
  "Vector2DistanceSqr",
);
export const Vector2Angle: WebFunction<"Vector2Angle"> = delegate(
  "Vector2Angle",
);
export const Vector2LineAngle: WebFunction<"Vector2LineAngle"> = delegate(
  "Vector2LineAngle",
);
export const Vector2Scale: WebFunction<"Vector2Scale"> = delegate(
  "Vector2Scale",
);
export const Vector2Multiply: WebFunction<"Vector2Multiply"> = delegate(
  "Vector2Multiply",
);
export const Vector2Negate: WebFunction<"Vector2Negate"> = delegate(
  "Vector2Negate",
);
export const Vector2Divide: WebFunction<"Vector2Divide"> = delegate(
  "Vector2Divide",
);
export const Vector2Normalize: WebFunction<"Vector2Normalize"> = delegate(
  "Vector2Normalize",
);
export const Vector2Transform: WebFunction<"Vector2Transform"> = delegate(
  "Vector2Transform",
);
export const Vector2Lerp: WebFunction<"Vector2Lerp"> = delegate("Vector2Lerp");
export const Vector2Reflect: WebFunction<"Vector2Reflect"> = delegate(
  "Vector2Reflect",
);
export const Vector2Min: WebFunction<"Vector2Min"> = delegate("Vector2Min");
export const Vector2Max: WebFunction<"Vector2Max"> = delegate("Vector2Max");
export const Vector2Rotate: WebFunction<"Vector2Rotate"> = delegate(
  "Vector2Rotate",
);
export const Vector2MoveTowards: WebFunction<"Vector2MoveTowards"> = delegate(
  "Vector2MoveTowards",
);
export const Vector2Invert: WebFunction<"Vector2Invert"> = delegate(
  "Vector2Invert",
);
export const Vector2Clamp: WebFunction<"Vector2Clamp"> = delegate(
  "Vector2Clamp",
);
export const Vector2ClampValue: WebFunction<"Vector2ClampValue"> = delegate(
  "Vector2ClampValue",
);
export const Vector2Equals: WebFunction<"Vector2Equals"> = delegate(
  "Vector2Equals",
);
export const Vector2Refract: WebFunction<"Vector2Refract"> = delegate(
  "Vector2Refract",
);
export const Vector3Zero: WebFunction<"Vector3Zero"> = delegate("Vector3Zero");
export const Vector3One: WebFunction<"Vector3One"> = delegate("Vector3One");
export const Vector3Add: WebFunction<"Vector3Add"> = delegate("Vector3Add");
export const Vector3AddValue: WebFunction<"Vector3AddValue"> = delegate(
  "Vector3AddValue",
);
export const Vector3Subtract: WebFunction<"Vector3Subtract"> = delegate(
  "Vector3Subtract",
);
export const Vector3SubtractValue: WebFunction<"Vector3SubtractValue"> =
  delegate("Vector3SubtractValue");
export const Vector3Scale: WebFunction<"Vector3Scale"> = delegate(
  "Vector3Scale",
);
export const Vector3Multiply: WebFunction<"Vector3Multiply"> = delegate(
  "Vector3Multiply",
);
export const Vector3CrossProduct: WebFunction<"Vector3CrossProduct"> = delegate(
  "Vector3CrossProduct",
);
export const Vector3Perpendicular: WebFunction<"Vector3Perpendicular"> =
  delegate("Vector3Perpendicular");
export const Vector3Length: WebFunction<"Vector3Length"> = delegate(
  "Vector3Length",
);
export const Vector3LengthSqr: WebFunction<"Vector3LengthSqr"> = delegate(
  "Vector3LengthSqr",
);
export const Vector3DotProduct: WebFunction<"Vector3DotProduct"> = delegate(
  "Vector3DotProduct",
);
export const Vector3Distance: WebFunction<"Vector3Distance"> = delegate(
  "Vector3Distance",
);
export const Vector3DistanceSqr: WebFunction<"Vector3DistanceSqr"> = delegate(
  "Vector3DistanceSqr",
);
export const Vector3Angle: WebFunction<"Vector3Angle"> = delegate(
  "Vector3Angle",
);
export const Vector3Negate: WebFunction<"Vector3Negate"> = delegate(
  "Vector3Negate",
);
export const Vector3Divide: WebFunction<"Vector3Divide"> = delegate(
  "Vector3Divide",
);
export const Vector3Normalize: WebFunction<"Vector3Normalize"> = delegate(
  "Vector3Normalize",
);
export const Vector3Project: WebFunction<"Vector3Project"> = delegate(
  "Vector3Project",
);
export const Vector3Reject: WebFunction<"Vector3Reject"> = delegate(
  "Vector3Reject",
);
export const Vector3OrthoNormalize: WebFunction<"Vector3OrthoNormalize"> =
  delegate("Vector3OrthoNormalize");
export const Vector3Transform: WebFunction<"Vector3Transform"> = delegate(
  "Vector3Transform",
);
export const Vector3RotateByQuaternion: WebFunction<
  "Vector3RotateByQuaternion"
> = delegate("Vector3RotateByQuaternion");
export const Vector3RotateByAxisAngle: WebFunction<"Vector3RotateByAxisAngle"> =
  delegate("Vector3RotateByAxisAngle");
export const Vector3MoveTowards: WebFunction<"Vector3MoveTowards"> = delegate(
  "Vector3MoveTowards",
);
export const Vector3Lerp: WebFunction<"Vector3Lerp"> = delegate("Vector3Lerp");
export const Vector3CubicHermite: WebFunction<"Vector3CubicHermite"> = delegate(
  "Vector3CubicHermite",
);
export const Vector3Reflect: WebFunction<"Vector3Reflect"> = delegate(
  "Vector3Reflect",
);
export const Vector3Min: WebFunction<"Vector3Min"> = delegate("Vector3Min");
export const Vector3Max: WebFunction<"Vector3Max"> = delegate("Vector3Max");
export const Vector3Barycenter: WebFunction<"Vector3Barycenter"> = delegate(
  "Vector3Barycenter",
);
export const Vector3Unproject: WebFunction<"Vector3Unproject"> = delegate(
  "Vector3Unproject",
);
export const Vector3ToFloatV: WebFunction<"Vector3ToFloatV"> = delegate(
  "Vector3ToFloatV",
);
export const Vector3Invert: WebFunction<"Vector3Invert"> = delegate(
  "Vector3Invert",
);
export const Vector3Clamp: WebFunction<"Vector3Clamp"> = delegate(
  "Vector3Clamp",
);
export const Vector3ClampValue: WebFunction<"Vector3ClampValue"> = delegate(
  "Vector3ClampValue",
);
export const Vector3Equals: WebFunction<"Vector3Equals"> = delegate(
  "Vector3Equals",
);
export const Vector3Refract: WebFunction<"Vector3Refract"> = delegate(
  "Vector3Refract",
);
export const Vector4Zero: WebFunction<"Vector4Zero"> = delegate("Vector4Zero");
export const Vector4One: WebFunction<"Vector4One"> = delegate("Vector4One");
export const Vector4Add: WebFunction<"Vector4Add"> = delegate("Vector4Add");
export const Vector4AddValue: WebFunction<"Vector4AddValue"> = delegate(
  "Vector4AddValue",
);
export const Vector4Subtract: WebFunction<"Vector4Subtract"> = delegate(
  "Vector4Subtract",
);
export const Vector4SubtractValue: WebFunction<"Vector4SubtractValue"> =
  delegate("Vector4SubtractValue");
export const Vector4Length: WebFunction<"Vector4Length"> = delegate(
  "Vector4Length",
);
export const Vector4LengthSqr: WebFunction<"Vector4LengthSqr"> = delegate(
  "Vector4LengthSqr",
);
export const Vector4DotProduct: WebFunction<"Vector4DotProduct"> = delegate(
  "Vector4DotProduct",
);
export const Vector4Distance: WebFunction<"Vector4Distance"> = delegate(
  "Vector4Distance",
);
export const Vector4DistanceSqr: WebFunction<"Vector4DistanceSqr"> = delegate(
  "Vector4DistanceSqr",
);
export const Vector4Scale: WebFunction<"Vector4Scale"> = delegate(
  "Vector4Scale",
);
export const Vector4Multiply: WebFunction<"Vector4Multiply"> = delegate(
  "Vector4Multiply",
);
export const Vector4Negate: WebFunction<"Vector4Negate"> = delegate(
  "Vector4Negate",
);
export const Vector4Divide: WebFunction<"Vector4Divide"> = delegate(
  "Vector4Divide",
);
export const Vector4Normalize: WebFunction<"Vector4Normalize"> = delegate(
  "Vector4Normalize",
);
export const Vector4Min: WebFunction<"Vector4Min"> = delegate("Vector4Min");
export const Vector4Max: WebFunction<"Vector4Max"> = delegate("Vector4Max");
export const Vector4Lerp: WebFunction<"Vector4Lerp"> = delegate("Vector4Lerp");
export const Vector4MoveTowards: WebFunction<"Vector4MoveTowards"> = delegate(
  "Vector4MoveTowards",
);
export const Vector4Invert: WebFunction<"Vector4Invert"> = delegate(
  "Vector4Invert",
);
export const Vector4Equals: WebFunction<"Vector4Equals"> = delegate(
  "Vector4Equals",
);
export const MatrixDeterminant: WebFunction<"MatrixDeterminant"> = delegate(
  "MatrixDeterminant",
);
export const MatrixTrace: WebFunction<"MatrixTrace"> = delegate("MatrixTrace");
export const MatrixTranspose: WebFunction<"MatrixTranspose"> = delegate(
  "MatrixTranspose",
);
export const MatrixInvert: WebFunction<"MatrixInvert"> = delegate(
  "MatrixInvert",
);
export const MatrixIdentity: WebFunction<"MatrixIdentity"> = delegate(
  "MatrixIdentity",
);
export const MatrixAdd: WebFunction<"MatrixAdd"> = delegate("MatrixAdd");
export const MatrixSubtract: WebFunction<"MatrixSubtract"> = delegate(
  "MatrixSubtract",
);
export const MatrixMultiply: WebFunction<"MatrixMultiply"> = delegate(
  "MatrixMultiply",
);
export const MatrixMultiplyValue: WebFunction<"MatrixMultiplyValue"> = delegate(
  "MatrixMultiplyValue",
);
export const MatrixTranslate: WebFunction<"MatrixTranslate"> = delegate(
  "MatrixTranslate",
);
export const MatrixRotate: WebFunction<"MatrixRotate"> = delegate(
  "MatrixRotate",
);
export const MatrixRotateX: WebFunction<"MatrixRotateX"> = delegate(
  "MatrixRotateX",
);
export const MatrixRotateY: WebFunction<"MatrixRotateY"> = delegate(
  "MatrixRotateY",
);
export const MatrixRotateZ: WebFunction<"MatrixRotateZ"> = delegate(
  "MatrixRotateZ",
);
export const MatrixRotateXYZ: WebFunction<"MatrixRotateXYZ"> = delegate(
  "MatrixRotateXYZ",
);
export const MatrixRotateZYX: WebFunction<"MatrixRotateZYX"> = delegate(
  "MatrixRotateZYX",
);
export const MatrixScale: WebFunction<"MatrixScale"> = delegate("MatrixScale");
export const MatrixFrustum: WebFunction<"MatrixFrustum"> = delegate(
  "MatrixFrustum",
);
export const MatrixPerspective: WebFunction<"MatrixPerspective"> = delegate(
  "MatrixPerspective",
);
export const MatrixOrtho: WebFunction<"MatrixOrtho"> = delegate("MatrixOrtho");
export const MatrixLookAt: WebFunction<"MatrixLookAt"> = delegate(
  "MatrixLookAt",
);
export const MatrixToFloatV: WebFunction<"MatrixToFloatV"> = delegate(
  "MatrixToFloatV",
);
export const QuaternionAdd: WebFunction<"QuaternionAdd"> = delegate(
  "QuaternionAdd",
);
export const QuaternionAddValue: WebFunction<"QuaternionAddValue"> = delegate(
  "QuaternionAddValue",
);
export const QuaternionSubtract: WebFunction<"QuaternionSubtract"> = delegate(
  "QuaternionSubtract",
);
export const QuaternionSubtractValue: WebFunction<"QuaternionSubtractValue"> =
  delegate("QuaternionSubtractValue");
export const QuaternionIdentity: WebFunction<"QuaternionIdentity"> = delegate(
  "QuaternionIdentity",
);
export const QuaternionLength: WebFunction<"QuaternionLength"> = delegate(
  "QuaternionLength",
);
export const QuaternionNormalize: WebFunction<"QuaternionNormalize"> = delegate(
  "QuaternionNormalize",
);
export const QuaternionInvert: WebFunction<"QuaternionInvert"> = delegate(
  "QuaternionInvert",
);
export const QuaternionMultiply: WebFunction<"QuaternionMultiply"> = delegate(
  "QuaternionMultiply",
);
export const QuaternionScale: WebFunction<"QuaternionScale"> = delegate(
  "QuaternionScale",
);
export const QuaternionDivide: WebFunction<"QuaternionDivide"> = delegate(
  "QuaternionDivide",
);
export const QuaternionLerp: WebFunction<"QuaternionLerp"> = delegate(
  "QuaternionLerp",
);
export const QuaternionNlerp: WebFunction<"QuaternionNlerp"> = delegate(
  "QuaternionNlerp",
);
export const QuaternionSlerp: WebFunction<"QuaternionSlerp"> = delegate(
  "QuaternionSlerp",
);
export const QuaternionCubicHermiteSpline: WebFunction<
  "QuaternionCubicHermiteSpline"
> = delegate("QuaternionCubicHermiteSpline");
export const QuaternionFromVector3ToVector3: WebFunction<
  "QuaternionFromVector3ToVector3"
> = delegate("QuaternionFromVector3ToVector3");
export const QuaternionFromMatrix: WebFunction<"QuaternionFromMatrix"> =
  delegate("QuaternionFromMatrix");
export const QuaternionToMatrix: WebFunction<"QuaternionToMatrix"> = delegate(
  "QuaternionToMatrix",
);
export const QuaternionFromAxisAngle: WebFunction<"QuaternionFromAxisAngle"> =
  delegate("QuaternionFromAxisAngle");
export const QuaternionToAxisAngle: WebFunction<"QuaternionToAxisAngle"> =
  delegate("QuaternionToAxisAngle");
export const QuaternionFromEuler: WebFunction<"QuaternionFromEuler"> = delegate(
  "QuaternionFromEuler",
);
export const QuaternionToEuler: WebFunction<"QuaternionToEuler"> = delegate(
  "QuaternionToEuler",
);
export const QuaternionTransform: WebFunction<"QuaternionTransform"> = delegate(
  "QuaternionTransform",
);
export const QuaternionEquals: WebFunction<"QuaternionEquals"> = delegate(
  "QuaternionEquals",
);
export const MatrixCompose: WebFunction<"MatrixCompose"> = delegate(
  "MatrixCompose",
);
export const MatrixDecompose: WebFunction<"MatrixDecompose"> = delegate(
  "MatrixDecompose",
);
export const GetCameraForward: WebFunction<"GetCameraForward"> = delegate(
  "GetCameraForward",
);
export const GetCameraUp: WebFunction<"GetCameraUp"> = delegate("GetCameraUp");
export const GetCameraRight: WebFunction<"GetCameraRight"> = delegate(
  "GetCameraRight",
);
export const CameraMoveForward: WebFunction<"CameraMoveForward"> = delegate(
  "CameraMoveForward",
);
export const CameraMoveUp: WebFunction<"CameraMoveUp"> = delegate(
  "CameraMoveUp",
);
export const CameraMoveRight: WebFunction<"CameraMoveRight"> = delegate(
  "CameraMoveRight",
);
export const CameraMoveToTarget: WebFunction<"CameraMoveToTarget"> = delegate(
  "CameraMoveToTarget",
);
export const CameraYaw: WebFunction<"CameraYaw"> = delegate("CameraYaw");
export const CameraPitch: WebFunction<"CameraPitch"> = delegate("CameraPitch");
export const CameraRoll: WebFunction<"CameraRoll"> = delegate("CameraRoll");
export const GetCameraViewMatrix: WebFunction<"GetCameraViewMatrix"> = delegate(
  "GetCameraViewMatrix",
);
export const GetCameraProjectionMatrix: WebFunction<
  "GetCameraProjectionMatrix"
> = delegate("GetCameraProjectionMatrix");
export const rlMatrixMode: WebFunction<"rlMatrixMode"> = delegate(
  "rlMatrixMode",
);
export const rlPushMatrix: WebFunction<"rlPushMatrix"> = delegate(
  "rlPushMatrix",
);
export const rlPopMatrix: WebFunction<"rlPopMatrix"> = delegate("rlPopMatrix");
export const rlLoadIdentity: WebFunction<"rlLoadIdentity"> = delegate(
  "rlLoadIdentity",
);
export const rlTranslatef: WebFunction<"rlTranslatef"> = delegate(
  "rlTranslatef",
);
export const rlRotatef: WebFunction<"rlRotatef"> = delegate("rlRotatef");
export const rlScalef: WebFunction<"rlScalef"> = delegate("rlScalef");
export const rlMultMatrixf: WebFunction<"rlMultMatrixf"> = delegate(
  "rlMultMatrixf",
);
export const rlFrustum: WebFunction<"rlFrustum"> = delegate("rlFrustum");
export const rlOrtho: WebFunction<"rlOrtho"> = delegate("rlOrtho");
export const rlViewport: WebFunction<"rlViewport"> = delegate("rlViewport");
export const rlSetClipPlanes: WebFunction<"rlSetClipPlanes"> = delegate(
  "rlSetClipPlanes",
);
export const rlGetCullDistanceNear: WebFunction<"rlGetCullDistanceNear"> =
  delegate("rlGetCullDistanceNear");
export const rlGetCullDistanceFar: WebFunction<"rlGetCullDistanceFar"> =
  delegate("rlGetCullDistanceFar");
export const rlBegin: WebFunction<"rlBegin"> = delegate("rlBegin");
export const rlEnd: WebFunction<"rlEnd"> = delegate("rlEnd");
export const rlVertex2i: WebFunction<"rlVertex2i"> = delegate("rlVertex2i");
export const rlVertex2f: WebFunction<"rlVertex2f"> = delegate("rlVertex2f");
export const rlVertex3f: WebFunction<"rlVertex3f"> = delegate("rlVertex3f");
export const rlTexCoord2f: WebFunction<"rlTexCoord2f"> = delegate(
  "rlTexCoord2f",
);
export const rlNormal3f: WebFunction<"rlNormal3f"> = delegate("rlNormal3f");
export const rlColor4ub: WebFunction<"rlColor4ub"> = delegate("rlColor4ub");
export const rlColor3f: WebFunction<"rlColor3f"> = delegate("rlColor3f");
export const rlColor4f: WebFunction<"rlColor4f"> = delegate("rlColor4f");
export const rlEnableVertexArray: WebFunction<"rlEnableVertexArray"> = delegate(
  "rlEnableVertexArray",
);
export const rlDisableVertexArray: WebFunction<"rlDisableVertexArray"> =
  delegate("rlDisableVertexArray");
export const rlEnableVertexBuffer: WebFunction<"rlEnableVertexBuffer"> =
  delegate("rlEnableVertexBuffer");
export const rlDisableVertexBuffer: WebFunction<"rlDisableVertexBuffer"> =
  delegate("rlDisableVertexBuffer");
export const rlEnableVertexBufferElement: WebFunction<
  "rlEnableVertexBufferElement"
> = delegate("rlEnableVertexBufferElement");
export const rlDisableVertexBufferElement: WebFunction<
  "rlDisableVertexBufferElement"
> = delegate("rlDisableVertexBufferElement");
export const rlEnableVertexAttribute: WebFunction<"rlEnableVertexAttribute"> =
  delegate("rlEnableVertexAttribute");
export const rlDisableVertexAttribute: WebFunction<"rlDisableVertexAttribute"> =
  delegate("rlDisableVertexAttribute");
export const rlEnableStatePointer: WebFunction<"rlEnableStatePointer"> =
  delegate("rlEnableStatePointer");
export const rlDisableStatePointer: WebFunction<"rlDisableStatePointer"> =
  delegate("rlDisableStatePointer");
export const rlActiveTextureSlot: WebFunction<"rlActiveTextureSlot"> = delegate(
  "rlActiveTextureSlot",
);
export const rlEnableTexture: WebFunction<"rlEnableTexture"> = delegate(
  "rlEnableTexture",
);
export const rlDisableTexture: WebFunction<"rlDisableTexture"> = delegate(
  "rlDisableTexture",
);
export const rlEnableTextureCubemap: WebFunction<"rlEnableTextureCubemap"> =
  delegate("rlEnableTextureCubemap");
export const rlDisableTextureCubemap: WebFunction<"rlDisableTextureCubemap"> =
  delegate("rlDisableTextureCubemap");
export const rlTextureParameters: WebFunction<"rlTextureParameters"> = delegate(
  "rlTextureParameters",
);
export const rlCubemapParameters: WebFunction<"rlCubemapParameters"> = delegate(
  "rlCubemapParameters",
);
export const rlEnableShader: WebFunction<"rlEnableShader"> = delegate(
  "rlEnableShader",
);
export const rlDisableShader: WebFunction<"rlDisableShader"> = delegate(
  "rlDisableShader",
);
export const rlEnableFramebuffer: WebFunction<"rlEnableFramebuffer"> = delegate(
  "rlEnableFramebuffer",
);
export const rlDisableFramebuffer: WebFunction<"rlDisableFramebuffer"> =
  delegate("rlDisableFramebuffer");
export const rlGetActiveFramebuffer: WebFunction<"rlGetActiveFramebuffer"> =
  delegate("rlGetActiveFramebuffer");
export const rlActiveDrawBuffers: WebFunction<"rlActiveDrawBuffers"> = delegate(
  "rlActiveDrawBuffers",
);
export const rlBlitFramebuffer: WebFunction<"rlBlitFramebuffer"> = delegate(
  "rlBlitFramebuffer",
);
export const rlBindFramebuffer: WebFunction<"rlBindFramebuffer"> = delegate(
  "rlBindFramebuffer",
);
export const rlEnableColorBlend: WebFunction<"rlEnableColorBlend"> = delegate(
  "rlEnableColorBlend",
);
export const rlDisableColorBlend: WebFunction<"rlDisableColorBlend"> = delegate(
  "rlDisableColorBlend",
);
export const rlEnableDepthTest: WebFunction<"rlEnableDepthTest"> = delegate(
  "rlEnableDepthTest",
);
export const rlDisableDepthTest: WebFunction<"rlDisableDepthTest"> = delegate(
  "rlDisableDepthTest",
);
export const rlEnableDepthMask: WebFunction<"rlEnableDepthMask"> = delegate(
  "rlEnableDepthMask",
);
export const rlDisableDepthMask: WebFunction<"rlDisableDepthMask"> = delegate(
  "rlDisableDepthMask",
);
export const rlEnableBackfaceCulling: WebFunction<"rlEnableBackfaceCulling"> =
  delegate("rlEnableBackfaceCulling");
export const rlDisableBackfaceCulling: WebFunction<"rlDisableBackfaceCulling"> =
  delegate("rlDisableBackfaceCulling");
export const rlColorMask: WebFunction<"rlColorMask"> = delegate("rlColorMask");
export const rlSetCullFace: WebFunction<"rlSetCullFace"> = delegate(
  "rlSetCullFace",
);
export const rlEnableScissorTest: WebFunction<"rlEnableScissorTest"> = delegate(
  "rlEnableScissorTest",
);
export const rlDisableScissorTest: WebFunction<"rlDisableScissorTest"> =
  delegate("rlDisableScissorTest");
export const rlScissor: WebFunction<"rlScissor"> = delegate("rlScissor");
export const rlEnablePointMode: WebFunction<"rlEnablePointMode"> = delegate(
  "rlEnablePointMode",
);
export const rlDisablePointMode: WebFunction<"rlDisablePointMode"> = delegate(
  "rlDisablePointMode",
);
export const rlSetPointSize: WebFunction<"rlSetPointSize"> = delegate(
  "rlSetPointSize",
);
export const rlGetPointSize: WebFunction<"rlGetPointSize"> = delegate(
  "rlGetPointSize",
);
export const rlEnableWireMode: WebFunction<"rlEnableWireMode"> = delegate(
  "rlEnableWireMode",
);
export const rlDisableWireMode: WebFunction<"rlDisableWireMode"> = delegate(
  "rlDisableWireMode",
);
export const rlSetLineWidth: WebFunction<"rlSetLineWidth"> = delegate(
  "rlSetLineWidth",
);
export const rlGetLineWidth: WebFunction<"rlGetLineWidth"> = delegate(
  "rlGetLineWidth",
);
export const rlEnableSmoothLines: WebFunction<"rlEnableSmoothLines"> = delegate(
  "rlEnableSmoothLines",
);
export const rlDisableSmoothLines: WebFunction<"rlDisableSmoothLines"> =
  delegate("rlDisableSmoothLines");
export const rlEnableStereoRender: WebFunction<"rlEnableStereoRender"> =
  delegate("rlEnableStereoRender");
export const rlDisableStereoRender: WebFunction<"rlDisableStereoRender"> =
  delegate("rlDisableStereoRender");
export const rlIsStereoRenderEnabled: WebFunction<"rlIsStereoRenderEnabled"> =
  delegate("rlIsStereoRenderEnabled");
export const rlClearColor: WebFunction<"rlClearColor"> = delegate(
  "rlClearColor",
);
export const rlClearScreenBuffers: WebFunction<"rlClearScreenBuffers"> =
  delegate("rlClearScreenBuffers");
export const rlCheckErrors: WebFunction<"rlCheckErrors"> = delegate(
  "rlCheckErrors",
);
export const rlSetBlendMode: WebFunction<"rlSetBlendMode"> = delegate(
  "rlSetBlendMode",
);
export const rlSetBlendFactors: WebFunction<"rlSetBlendFactors"> = delegate(
  "rlSetBlendFactors",
);
export const rlSetBlendFactorsSeparate: WebFunction<
  "rlSetBlendFactorsSeparate"
> = delegate("rlSetBlendFactorsSeparate");
export const rlglInit: WebFunction<"rlglInit"> = delegate("rlglInit");
export const rlglClose: WebFunction<"rlglClose"> = delegate("rlglClose");
export const rlLoadExtensions: WebFunction<"rlLoadExtensions"> = delegate(
  "rlLoadExtensions",
);
export const rlGetProcAddress: WebFunction<"rlGetProcAddress"> = delegate(
  "rlGetProcAddress",
);
export const rlGetVersion: WebFunction<"rlGetVersion"> = delegate(
  "rlGetVersion",
);
export const rlSetFramebufferWidth: WebFunction<"rlSetFramebufferWidth"> =
  delegate("rlSetFramebufferWidth");
export const rlGetFramebufferWidth: WebFunction<"rlGetFramebufferWidth"> =
  delegate("rlGetFramebufferWidth");
export const rlSetFramebufferHeight: WebFunction<"rlSetFramebufferHeight"> =
  delegate("rlSetFramebufferHeight");
export const rlGetFramebufferHeight: WebFunction<"rlGetFramebufferHeight"> =
  delegate("rlGetFramebufferHeight");
export const rlGetTextureIdDefault: WebFunction<"rlGetTextureIdDefault"> =
  delegate("rlGetTextureIdDefault");
export const rlGetShaderIdDefault: WebFunction<"rlGetShaderIdDefault"> =
  delegate("rlGetShaderIdDefault");
export const rlGetShaderLocsDefault: WebFunction<"rlGetShaderLocsDefault"> =
  delegate("rlGetShaderLocsDefault");
export const rlLoadRenderBatch: WebFunction<"rlLoadRenderBatch"> = delegate(
  "rlLoadRenderBatch",
);
export const rlUnloadRenderBatch: WebFunction<"rlUnloadRenderBatch"> = delegate(
  "rlUnloadRenderBatch",
);
export const rlDrawRenderBatch: WebFunction<"rlDrawRenderBatch"> = delegate(
  "rlDrawRenderBatch",
);
export const rlSetRenderBatchActive: WebFunction<"rlSetRenderBatchActive"> =
  delegate("rlSetRenderBatchActive");
export const rlDrawRenderBatchActive: WebFunction<"rlDrawRenderBatchActive"> =
  delegate("rlDrawRenderBatchActive");
export const rlCheckRenderBatchLimit: WebFunction<"rlCheckRenderBatchLimit"> =
  delegate("rlCheckRenderBatchLimit");
export const rlSetTexture: WebFunction<"rlSetTexture"> = delegate(
  "rlSetTexture",
);
export const rlLoadVertexArray: WebFunction<"rlLoadVertexArray"> = delegate(
  "rlLoadVertexArray",
);
export const rlLoadVertexBuffer: WebFunction<"rlLoadVertexBuffer"> = delegate(
  "rlLoadVertexBuffer",
);
export const rlLoadVertexBufferElement: WebFunction<
  "rlLoadVertexBufferElement"
> = delegate("rlLoadVertexBufferElement");
export const rlUpdateVertexBuffer: WebFunction<"rlUpdateVertexBuffer"> =
  delegate("rlUpdateVertexBuffer");
export const rlUpdateVertexBufferElements: WebFunction<
  "rlUpdateVertexBufferElements"
> = delegate("rlUpdateVertexBufferElements");
export const rlUnloadVertexArray: WebFunction<"rlUnloadVertexArray"> = delegate(
  "rlUnloadVertexArray",
);
export const rlUnloadVertexBuffer: WebFunction<"rlUnloadVertexBuffer"> =
  delegate("rlUnloadVertexBuffer");
export const rlSetVertexAttribute: WebFunction<"rlSetVertexAttribute"> =
  delegate("rlSetVertexAttribute");
export const rlSetVertexAttributeDivisor: WebFunction<
  "rlSetVertexAttributeDivisor"
> = delegate("rlSetVertexAttributeDivisor");
export const rlSetVertexAttributeDefault: WebFunction<
  "rlSetVertexAttributeDefault"
> = delegate("rlSetVertexAttributeDefault");
export const rlDrawVertexArray: WebFunction<"rlDrawVertexArray"> = delegate(
  "rlDrawVertexArray",
);
export const rlDrawVertexArrayElements: WebFunction<
  "rlDrawVertexArrayElements"
> = delegate("rlDrawVertexArrayElements");
export const rlDrawVertexArrayInstanced: WebFunction<
  "rlDrawVertexArrayInstanced"
> = delegate("rlDrawVertexArrayInstanced");
export const rlDrawVertexArrayElementsInstanced: WebFunction<
  "rlDrawVertexArrayElementsInstanced"
> = delegate("rlDrawVertexArrayElementsInstanced");
export const rlLoadTexture: WebFunction<"rlLoadTexture"> = delegate(
  "rlLoadTexture",
);
export const rlLoadTextureDepth: WebFunction<"rlLoadTextureDepth"> = delegate(
  "rlLoadTextureDepth",
);
export const rlLoadTextureCubemap: WebFunction<"rlLoadTextureCubemap"> =
  delegate("rlLoadTextureCubemap");
export const rlUpdateTexture: WebFunction<"rlUpdateTexture"> = delegate(
  "rlUpdateTexture",
);
export const rlGetGlTextureFormats: WebFunction<"rlGetGlTextureFormats"> =
  delegate("rlGetGlTextureFormats");
export const rlGetPixelFormatName: WebFunction<"rlGetPixelFormatName"> =
  delegate("rlGetPixelFormatName");
export const rlUnloadTexture: WebFunction<"rlUnloadTexture"> = delegate(
  "rlUnloadTexture",
);
export const rlGenTextureMipmaps: WebFunction<"rlGenTextureMipmaps"> = delegate(
  "rlGenTextureMipmaps",
);
export const rlReadTexturePixels: WebFunction<"rlReadTexturePixels"> = delegate(
  "rlReadTexturePixels",
);
export const rlReadScreenPixels: WebFunction<"rlReadScreenPixels"> = delegate(
  "rlReadScreenPixels",
);
export const rlLoadFramebuffer: WebFunction<"rlLoadFramebuffer"> = delegate(
  "rlLoadFramebuffer",
);
export const rlFramebufferAttach: WebFunction<"rlFramebufferAttach"> = delegate(
  "rlFramebufferAttach",
);
export const rlFramebufferComplete: WebFunction<"rlFramebufferComplete"> =
  delegate("rlFramebufferComplete");
export const rlUnloadFramebuffer: WebFunction<"rlUnloadFramebuffer"> = delegate(
  "rlUnloadFramebuffer",
);
export const rlCopyFramebuffer: WebFunction<"rlCopyFramebuffer"> = delegate(
  "rlCopyFramebuffer",
);
export const rlResizeFramebuffer: WebFunction<"rlResizeFramebuffer"> = delegate(
  "rlResizeFramebuffer",
);
export const rlLoadShader: WebFunction<"rlLoadShader"> = delegate(
  "rlLoadShader",
);
export const rlLoadShaderProgram: WebFunction<"rlLoadShaderProgram"> = delegate(
  "rlLoadShaderProgram",
);
export const rlLoadShaderProgramEx: WebFunction<"rlLoadShaderProgramEx"> =
  delegate("rlLoadShaderProgramEx");
export const rlLoadShaderProgramCompute: WebFunction<
  "rlLoadShaderProgramCompute"
> = delegate("rlLoadShaderProgramCompute");
export const rlUnloadShader: WebFunction<"rlUnloadShader"> = delegate(
  "rlUnloadShader",
);
export const rlUnloadShaderProgram: WebFunction<"rlUnloadShaderProgram"> =
  delegate("rlUnloadShaderProgram");
export const rlGetLocationUniform: WebFunction<"rlGetLocationUniform"> =
  delegate("rlGetLocationUniform");
export const rlGetLocationAttrib: WebFunction<"rlGetLocationAttrib"> = delegate(
  "rlGetLocationAttrib",
);
export const rlSetUniform: WebFunction<"rlSetUniform"> = delegate(
  "rlSetUniform",
);
export const rlSetUniformMatrix: WebFunction<"rlSetUniformMatrix"> = delegate(
  "rlSetUniformMatrix",
);
export const rlSetUniformMatrices: WebFunction<"rlSetUniformMatrices"> =
  delegate("rlSetUniformMatrices");
export const rlSetUniformSampler: WebFunction<"rlSetUniformSampler"> = delegate(
  "rlSetUniformSampler",
);
export const rlSetShader: WebFunction<"rlSetShader"> = delegate("rlSetShader");
export const rlComputeShaderDispatch: WebFunction<"rlComputeShaderDispatch"> =
  delegate("rlComputeShaderDispatch");
export const rlLoadShaderBuffer: WebFunction<"rlLoadShaderBuffer"> = delegate(
  "rlLoadShaderBuffer",
);
export const rlUnloadShaderBuffer: WebFunction<"rlUnloadShaderBuffer"> =
  delegate("rlUnloadShaderBuffer");
export const rlUpdateShaderBuffer: WebFunction<"rlUpdateShaderBuffer"> =
  delegate("rlUpdateShaderBuffer");
export const rlBindShaderBuffer: WebFunction<"rlBindShaderBuffer"> = delegate(
  "rlBindShaderBuffer",
);
export const rlReadShaderBuffer: WebFunction<"rlReadShaderBuffer"> = delegate(
  "rlReadShaderBuffer",
);
export const rlCopyShaderBuffer: WebFunction<"rlCopyShaderBuffer"> = delegate(
  "rlCopyShaderBuffer",
);
export const rlGetShaderBufferSize: WebFunction<"rlGetShaderBufferSize"> =
  delegate("rlGetShaderBufferSize");
export const rlBindImageTexture: WebFunction<"rlBindImageTexture"> = delegate(
  "rlBindImageTexture",
);
export const rlGetMatrixModelview: WebFunction<"rlGetMatrixModelview"> =
  delegate("rlGetMatrixModelview");
export const rlGetMatrixProjection: WebFunction<"rlGetMatrixProjection"> =
  delegate("rlGetMatrixProjection");
export const rlGetMatrixTransform: WebFunction<"rlGetMatrixTransform"> =
  delegate("rlGetMatrixTransform");
export const rlGetMatrixProjectionStereo: WebFunction<
  "rlGetMatrixProjectionStereo"
> = delegate("rlGetMatrixProjectionStereo");
export const rlGetMatrixViewOffsetStereo: WebFunction<
  "rlGetMatrixViewOffsetStereo"
> = delegate("rlGetMatrixViewOffsetStereo");
export const rlSetMatrixProjection: WebFunction<"rlSetMatrixProjection"> =
  delegate("rlSetMatrixProjection");
export const rlSetMatrixModelview: WebFunction<"rlSetMatrixModelview"> =
  delegate("rlSetMatrixModelview");
export const rlSetMatrixProjectionStereo: WebFunction<
  "rlSetMatrixProjectionStereo"
> = delegate("rlSetMatrixProjectionStereo");
export const rlSetMatrixViewOffsetStereo: WebFunction<
  "rlSetMatrixViewOffsetStereo"
> = delegate("rlSetMatrixViewOffsetStereo");
export const rlLoadDrawCube: WebFunction<"rlLoadDrawCube"> = delegate(
  "rlLoadDrawCube",
);
export const rlLoadDrawQuad: WebFunction<"rlLoadDrawQuad"> = delegate(
  "rlLoadDrawQuad",
);
