// This file is generated by generate_webapp.ts
export * from "./constants.ts";
export * from "./functions.ts";
export * from "./structs.ts";
export {
  RenderTexture as RenderTexture2D,
  Texture as Texture2D,
  Texture as TextureCubemap,
  Vector4 as Quaternion,
} from "./structs.ts";
export type float = number;
export type int = number;
export type bool = boolean;
export type char = string;
export const RAYLIB_VERSION_MAJOR = 6;
export const RAYLIB_VERSION_MINOR = 0;
export const RAYLIB_VERSION_PATCH = 0;
export const RAYLIB_VERSION = "6.0";
